export default {
  'zh-CN': {
    rootuser: {
      title: '注册用户管理',
      placeholdername: '请输入姓名或手机号',
      name: '姓名',
      mobileNo: '手机号',
      idNo: '证件号码',
      genderDesc: '性别',
      birthDate: '出生日期',
      email: '邮箱',
      statusDesc: '用户状态',
      draft: '编辑',
      valid: '生效',
      import: '导入',
      invalid: '失效',
      add: '新增',
      memo: '备注',
      pgender: '请选择性别',
      pmobileNo: '请填写手机号',
      pname: '请填写真实姓名',
      idType: '证件类型"',
      ppidType: '请选择证件类型',
      pidNo: '请填写证件号码',
      pbirthDate: '请选择出生日期',
      pemail: '请填写邮箱',
      pcropedImg: '点击上传头像',
      pmemo: '请填写备注',
      cstatusDesc: '请选择状态',
      cpmobileNo: '请填写正确的手机号',
      cidNo: '请填写正确的证件号码',
      cemail: '请填写正确的邮箱',
      platRolecontCode: '',
    },
    rootrole: {
      title1: '超级用户管理',
      title2: '管理员角色管理',
      title3: '管理员角色组',
      title4: '管理员用户管理',
      loginName: '用户登陆名',
      sysRootvalidDis: 'ROOT是否有效',
      searchText: '请输入用户姓名',
      information: '用户信息',
      proleCode: '请输入角色编码',
      proleCname: '请输入角色名称',
      roleCode: '角色编码',
      companyIdDis: '所属公司',
      roleCname: '角色名称中文',
      roleEname: '角色名称英文',
      roleTypeDis: '角色类型',
      validDis: '是否有效',
      invdate: '失效日期',
      assauth: '分配权限',
      delTips: '请确认删除该条数据',
      pcompanyIdDis: '请选择所属公司',
      readCheck: '新增保存后，选择的所属公司将不可修改，请按照实际所属公司选择',
      proleCnamec: '请输入角色中文名称',
      proleEname: '请输入角色英文名称',
      pvalid: '选择是否有效',
      pinvdate: '选择失效日期',
      proleDesc: '请输入角色描述',
      pinvreason: '请输入失效原因',
      pcomment: '请输入备注',
      roleDesc: '角色描述',
      invreason: '失效原因',
      proleTypeDis: '请输入选择角色类型',
      expand: '展开',
      disExpand: '收回',
      allPick: '全选',
      resetTree: '重置',
      checkReC: '反选',
    },
    rootgrprole: {
      prolegrpCode: '请输入角色组编码',
      prolegrpCname: '请输入角色组名称',
      searchText: '请输入角色名称',
      roleCname: '角色',
      rolegrpCode: '角色组编码',
      companyIdDis: '所属公司',
      rolegrpCname: '角色组名称中文',
      rolegrpEname: '角色组名称英文',
      rolegrpTypeDis: '角色组类型',
      validDis: '是否有效',
      invdate: '失效日期',
      pcompanyIdDis: '请选择所属公司',
      readCheck: '新增保存后，选择的所属公司将不可修改，请按照实际所属公司选择',
      pprolegrpCname: '请输入角色组中文名称',
      prolegrpEname: '请输入角色组英文名称',
      rolegrpDesc: '角色组描述',
      prolegrpDesc: '请输入角色组描述',
      valid: '选择是否有效',
      pinvdate: '选择失效日期',
      invreason: '失效原因',
      pinvreason: '请输入失效原因',
    },
    rootuserrole: {
      searchText: '请输入角色名称',
      authGrpDis: '角色组',
      readCheck: '新增保存后，选择的所属公司将不可修改，请按照实际所属公司选择',
      loginName: '用户登录名',
      sysUsadrolegrpDis: '管理员角色组',
      puserName: '请选择用户信息',
      sysAdminvalid: '选择用户状态',
      placeholdername: '',
      psysUsadrolegrpDis: '请选择角色组',
      recomp: '请先选择所属公司',

    },
  },
  'en-US': {
    rootuserrole: {
      searchText: 'Please enter the role name',
      authGrpDis: 'Character set',
      readCheck: 'After the new save, the selected company will not be modified, please choose according to the actual company',
      loginName: 'User login',
      sysUsadrolegrpDis: 'Administrator role group',
      puserName: 'Please select user information',
      sysAdminvalid: 'Select user status',
      placeholdername: '',
      recomp: 'Please select your company first',
      psysUsadrolegrpDis: 'Select the role group',
    },
    rootgrprole: {
      prolegrpCode: 'Please enter the role group code',
      prolegrpCname: 'Please enter the role group name',
      searchText: 'Please enter the role name',
      roleCname: 'role',
      rolegrpCode: 'Role group coding',
      companyIdDis: 'The role group belongs to the company',
      rolegrpCname: 'Role group name in Chinese',
      rolegrpEname: 'Role group name in English',
      rolegrpTypeDis: 'Role group type',
      validDis: 'The validity of',
      invdate: 'Expiry date',
      pcompanyIdDis: 'Please select your company',
      readCheck: 'After the new save, the selected company will not be modified, please choose according to the actual company',
      pprolegrpCname: 'Please enter the Chinese name of the role group',
      prolegrpEname: 'Please enter the English name of the role group',
      rolegrpDesc: 'Role group description',
      prolegrpDesc: 'Enter the group role description',
      valid: 'Whether the selection is valid or not',
      pinvdate: 'Select expiration date',
      invreason: 'The failure reason',
      pinvreason: 'Please enter the reason for failure',
    },
    rootuser: {
      title: 'Registered User Management',
      placeholdername: 'Please enter your name or cell phone number.',
      name: 'name',
      mobileNo: 'mobile',
      idNo: 'Identification Number',
      genderDesc: 'Gender',
      birthDate: 'Date of birth',
      email: 'email',
      statusDesc: 'status',
      draft: 'edit',
      valid: 'Take effect',
      import: 'Import',
      invalid: 'Invalid',
      add: 'add',
      memo: 'Remarks',
      pgender: 'Please choose gender.',
      pmobileNo: 'Please fill in your cell phone number.',
      pname: 'Please fill in your real name.',
      idType: 'Document type',
      ppidType: 'Please select the type of certificate',
      pidNo: 'Please fill in the ID number.',
      pbirthDate: 'Please choose the date of birth',
      pemail: 'Please fill in the mailbox',
      pcropedImg: 'Click Upload Portrait ',
      pmemo: 'Please fill in the notes.',
      cstatusDesc: 'Please select the status',
      cpmobileNo: 'Please fill in the correct cell phone number',
      cidNo: 'Please fill in the correct ID number',
      cemail: 'Please fill in the correct email address',
    },
    rootrole: {
      title1: 'Super User Management',
      title2: 'Administrator role management',
      title3: 'Administrator role group',
      title4: 'Administrator User Management',
      loginName: 'User login name',
      sysRootvalidDis: 'Is ROOT Effective',
      searchText: 'Please enter the user name',
      information: 'User information',
      proleCode: 'Please enter the role code',
      proleCname: 'Please enter the role name',
      roleCode: 'Character encoding',
      companyIdDis: 'Company to which the role belongs',
      roleCname: 'Role name Chinese',
      roleEname: 'Role name English',
      roleTypeDis: 'types of role',
      validDis: 'effective',
      invdate: 'Expiry date',
      assauth: 'Assign permissions',
      delTips: 'Please confirm deleting this data',
      pcompanyIdDis: 'Please select your company',
      readCheck: 'After the new save, the selected company will not be modified, please choose according to the actual company',
      proleCnamec: 'Please enter the Chinese name of the character',
      proleEname: 'Please enter the English name of the role',
      pvalid: 'Whether the selection is valid or not',
      pinvdate: 'Select expiration date',
      proleDesc: 'Please enter the role description',
      pinvreason: 'Please enter the reason for failure',
      pcomment: 'Please enter remarks',
      roleDesc: 'Role description',
      invreason: 'The failure reason',
      proleTypeDis: 'Please enter the selected role type',
      expand: 'an',
      disExpand: 'Take',
      allPick: 'Future',
      resetTree: 'reset',
      checkReC: 'selected',
    },
  },
}
