export default {
  'zh-CN': {
    knowlegeType: {
      title: '知识类型管理',
      treeTitle: '全部知识类型',
      cmutKntypeCode: '知识库类型编码',
      cmutKntypeName: '知识库类型名称',
      cmutKntypeBusprop: '工单业务性质',
      cmutWorkodprop: '类型属性',
      cmutKntypePid: '所属知识库类型',
      cmutKntypePic: '知识库类型图标',
      cmutKntypeDesc: '简要说明',
      comment: '备注',
      flowName: '流程名称',
      // searchTable
      businessFlow: '业务流程',
      selectPic: '选择图标',
      searchText1: '请输入功能节点名称',
      cmutKntypeCodeDis: '请输入知识库类型编码',
      cmutKntypeNameDis: '请输入知识库类型名称',
      cmutKntypeBuspropDis: '请选择工单业务性质',
      cmutWorkodpropDis: '请选择类型属性',
      cmutKntypePidDis: '请选择所属知识库类型',
      cmutKntypePicDis: '请选择知识库类型图标',
      cmutKntypeDescDis: '请输入简要说明',
      commentDis: '请输入备注',
      searchText: '请输入知识库类型名称或者编码',
      flowNameDis: '请选择业务流程',
    },
    knowlegebase: {
      title: '知识入库申请',
      title2: '知识入库确认',
      title3: '知识发布管理',
      title4: '知识失效管理',
      title5: '知识库检索',
      cmutKldOrder: '序号',
      cmutKldPubcomp: '发布公司',
      cmutKldPublish: '发布日期',
      cmutKldLosttime: '失效日期',
      publishAuthor: '发布人',
      cmutKldType: '知识库类型',
      cmutKldTitle: '知识点标题',
      cmutKldKeyword: '检索关键字',
      cmutKldContent: '内容',
      cmutKldAttach: '附件',
      cmutKldState: '状态',
      cmutKldAuth: '是否控制权限',
      cmutKldAuthtype: '权限类型',
      cmutKldNote: '备注',
      // dis
      cmutKldOrderDis: '请输入序号',
      cmutKldPubcompDis: '请选择发布公司',
      cmutKldPublishDis: '请选择发布日期',
      cmutKldLosttimeDis: '请选择失效日期',
      publishAuthorDis: '请选择发布人',
      cmutKldTypeDis: '请选择知识库类型',
      cmutKldTitleDis: '请输入知识点标题',
      cmutKldKeywordDis: '请输入检索关键字',
      cmutKldContentDis: '请输入内容',
      cmutKldAttachDis: '请选择附件',
      cmutKldStateDis: '请选择状态',
      cmutKldAuthDis: '请选择是否控制权限',
      cmutKldAuthtypeDis: '请选择权限类型',
      cmutKldNoteDis: '请选择备注',
      // reminder
      authRemind: '至少选择一个控制权限类型',
      pelConfir: '请确认',
      data: '数据',
    },
    knowlegeStatistic: {
      title: '知识库分析',
      paneTitle1: '数量统计',
      paneTitle2: '点击量统计',
      label1: '柱状图',
      label2: '饼状图',
      seriesName: '知识大类统计',
    },
    workOrderType: {
      title: '工单类型管理',
      treeTitle: '全部工单类型',
      cmutKntypeCode: '类型编码',
      cmutKntypeName: '类型名称',
      cmutKntypeBusprop: '工单业务性质',
      cmutKntypeProcessid: '业务工单',
      cmutWorkodprop: '类型属性',
      cmutKntypePid: '所属类型',
      cmutKntypeStdprice: '工单服务标准价格',
      cmutKntypeStddltime: '工单标准处理时间',
      cmutKntypeCaudltime: '工单警示处理时间',
      cmutKntypePic: '工单类型图标',
      cmutKntypeDesc: '简要说明',
      comment: '备注',
      flowName: '流程名称',
      // searchTable
      businessFlow: '业务流程',
      selectPic: '选择图标',
      searchText1: '请输入功能节点名称',
      cmutKntypeCodeDis: '请输入知识库类型编码',
      cmutKntypeNameDis: '请输入知识库类型名称',
      cmutKntypeBuspropDis: '请选择工单业务性质',
      cmutWorkodpropDis: '请选择类型属性',
      cmutKntypePidDis: '请选择所属知识库类型',
      cmutKntypePicDis: '请选择知识库类型图标',
      cmutKntypeDescDis: '请输入简要说明',
      cmutKntypeProcessidDis: '请选择业务工单',
      cmutKntypeStdpriceDis: '请输入工单服务标准价格',
      cmutKntypeStddltimeDis: '请输入工单标准处理时间',
      cmutKntypeCaudltimeDis: '请输入工单警示处理时间',
      commentDis: '请输入备注',
      searchText: '请输入工单类型名称或者编码',
      flowNameDis: '请选择业务流程',
      // searchTitle
      funLancode: '工单名称',
      funCode: '工单节点编号',
      searchTitle4: '选择业务工单',
      searchText4: '请输入业务工单名称'
    },
  },
  'en-US': {
    knowlegeType: {
      title: 'Knowledge type management',
      treeTitle: 'Total knowledge type',
      cmutKntypeCode: 'KB type encoding',
      cmutKntypeName: 'KB type name',
      cmutKntypeBusprop: 'Nature of work order business',
      cmutWorkodprop: 'The type attribute',
      cmutKntypePid: 'Type of knowledge base',
      cmutKntypePic: 'KB type icon',
      cmutKntypeDesc: 'Brief description',
      comment: 'note',
      flowName: 'Flow Name',
      // searchTable
      businessFlow: 'Business Flow',
      selectPic: 'Choose the Icon',
      searchText1: 'Please enter the function node name',
      cmutKntypeCode: 'Enter the KB type code',
      cmutKntypeName: 'Enter the knowledge base type name',
      cmutKntypeBusprop: 'Please select the nature of work order business',
      cmutWorkodprop: 'Select the type attribute',
      cmutKntypePid: 'Select the type of knowledge base to which you belong',
      cmutKntypePic: 'Select the KB type icon',
      cmutKntypeDesc: 'Please enter a brief description',
      comment: 'Please enter remarks',
      searchText: 'Please enter the knowledge base type name or code',
      flowNameDis: 'Please select businese flow',
    },
    knowlegebase: {
      title: 'Knowledge entry application',
      title2: 'Knowledge entry confirmation',
      title3: 'Knowledge release management',
      title4: 'Knowledge failure management',
      title5: 'Knowledge query',
      cmutKldOrder: 'Order',
      cmutKldPubcomp: 'Publish company',
      cmutKldPublish: 'Publish date',
      cmutKldLosttime: 'Expiry date',
      publishAuthor: 'Pubisher',
      cmutKldType: 'KB type',
      cmutKldTitle: 'Topic title',
      cmutKldKeyword: 'Search key',
      cmutKldContent: 'Content',
      cmutKldAttach: 'Attachment',
      cmutKldState: 'Status',
      cmutKldAuth: 'Control permissions ?',
      cmutKldAuthtype: 'Permission types',
      cmutKldNote: 'Comment',
      // dis
      cmutKldOrderDis: 'Please enter the serial number',
      cmutKldPubcompDis: 'Please select the publishing company',
      cmutKldPublishDis: 'Please select a release date',
      cmutKldLosttimeDis: 'Please select the expiration date',
      publishAuthorDis: 'Please select the publisher',
      cmutKldTypeDis: 'Select the knowledge base type',
      cmutKldTitleDis: 'Please enter the topic title',
      cmutKldKeywordDis: 'Please enter the search keyword',
      cmutKldContentDis: 'Please enter content',
      cmutKldAttachDis: 'Please select the attachment.',
      cmutKldStateDis: 'Please select state',
      cmutKldAuthDis: 'Please select whether to control permissions',
      cmutKldAuthtypeDis: 'Please select the permission type',
      cmutKldNoteDis: 'Please select comment',
      // reminder
      authRemind: 'Select at least one control permission type',
      pelConfir: 'Please confirm',
      data: 'data',
    },
    knowlegeStatistic: {
      title: 'Knowledge base analysis',
      paneTitle1: 'The number of statistical',
      paneTitle2: 'Click count',
      label1: 'A histogram',
      label2: 'The pie chart',
      seriesName: 'Knowledge statistics',
    },
    workOrderType: {
      title: 'WorkOrder type management',
      treeTitle: 'Total knowledge type',
      cmutKntypeCode: 'KB type encoding',
      cmutKntypeName: 'KB type name',
      cmutKntypeBusprop: 'Nature of work order business',
      cmutKntypeProcessid: 'Business work order',
      cmutWorkodprop: 'The type attribute',
      cmutKntypePid: 'Belongs to type',
      cmutKntypeStdprice: 'Work order service standard price',
      cmutKntypeStddltime: 'Standard processing time for work order',
      cmutKntypeCaudltime: 'Work order warning processing time',
      cmutKntypePic: 'Worksheet type icon',
      cmutKntypeDesc: 'Brief description',
      comment: 'Comment',
      flowName: 'The name of the process',
      businessFlow: 'The business process',
      selectPic: 'Choose the icon',
      searchText1: 'Please enter the function node name',
      cmutKntypeCodeDis: 'Enter the KB type code',
      cmutKntypeNameDis: 'Enter the knowledge base type name',
      cmutKntypeBuspropDis: 'Please select the nature of work order business',
      cmutWorkodpropDis: 'Select the type attribute',
      cmutKntypePidDis: 'Select the type of knowledge base to which you belong',
      cmutKntypeStdpriceDis: 'Please enter service standard price for work order',
      cmutKntypeStddltimeDis: 'Please input standard processing time for work order',
      cmutKntypeCaudltimeDis: 'Please input the work order warning processing time',
      cmutKntypePicDis: 'Select the KB type icon',
      cmutKntypeProcessidDis: 'Please select the business order',
      cmutKntypeDescDis: 'Please enter a brief description',
      commentDis: 'Please enter remarks',
      searchText: 'Please enter work order type name or code',
      flowNameDis: 'Select the business process',
      // searchTitle
      funLancode: 'WorkOrderName',
      funCode: 'WorkOrderCode',
      searchTitle4: 'Select Businese Order',
      searchText4: 'Please enter order name'
    },
  },
}
