export default {
  'zh-CN': {
    adminpmtype: {
      pmtypetitle: '参数类型管理',
      ppmtypeCode: '请输入参数类型编码',
      pmtypeCode: '参数类型编码',
      pmtypeName: '参数类型名称',
      ppmtypeName: '请输入类型名称',
      pmtypeIsupdate: '是否可修改',
      comment: '备注',
      pcomment: '请输入备注',
      placeholdername: '',
    },
    adminpminfo: {
      pminfotitle: '参数信息管理',
      pparamCode: '请输入公共参数编码',
      pparamInfoName: '请输入公共参数名称',
      pparamName: '请选择参数类型',
      paramCode: '公共参数编码',
      paramTypeDis: '公共参数类型',
      paramInfoName: '公共参数名称',
      paramInfoCn: '名称中文显示',
      paramInfoEn: '名称英文显示',
      placeholdername: '',
      pparamInfoCn: '请输入名称中文',
      pparamInfoEn: '请输入名称英文',
    },
    adminrole: {
      title1: '业务角色管理',
      proleCname: '请输入角色名称',
      roleCode: '角色编码',
      roleCname: '角色名称中文',
      roleEname: '角色名称英文',
      roleTypeDis: '角色类型',
      proleTypeDis: '请选择角色类型',
      validDis: '是否有效',
      invdate: '失效日期',
      checkHr: 'HR业务合作伙伴不可删除',
      proleCode: '请输入角色编码',
      pproleCname: '请输入角色中文名称',
      proleEname: '请输入角色英文名称',
      valid: '选择是否有效',
      roleDesc: '角色描述',
      proleDesc: '请输入角色描述',
      pinvdate: '选择失效日期',
      invreason: '失效原因',
      pinvreason: '请输入失效原因',
      flagBox: '分配按钮',
      plalist: '分配列表字段',
      Optional: '可选择字段',
      Optional2: '已选择字段',
      flagBox2: '分配编辑字段',
      flow: '分配流程',
      floauth: '处理权限',
      sffFieldNameDis: '显示名',
      sffPropertyDis: '字段属性',
      sffLayoutDis: '布局类型',
      ffLayo: '字段权限',
      ffLayodis: '默认显示字段权限',
      warcontent: '请选择流程步骤的处理权限后再进行保存',
      wartatle: '保存失败',
      warcontent2: '请选择数据块中的处理权限后再进行保存',
      todotatle1: '可选择待办事项',
      todotitle2: '已选择待办事项',
      autdNo: '事项编号',
      autdName: '事项名称',
      placfun: '分配节点',
      placauthset: '权限配置',
      pletodo: '待办事项分配',
      placeholdername: '',
    },
    admingrprole: {
      title: '业务角色组管理',
      prolegrpCname: '请输入角色组名称',
      searchText: '请输入角色名称',
      roleCname: '角色',
      rolegrpCode: '角色组编码',
      rolegrpCname: '角色组名称中文',
      rolegrpEname: '角色组名称英文',
      rolegrpTypeDis: '角色组类型',
      validDis: '是否有效',
      invdate: '失效日期',
      prolegrpCode: '请输入角色组编码',
      pprolegrpCname: '请输入角色组中文名称',
      prolegrpEname: '请输入角色组英文名称',
      rolegrpDesc: '角色组描述',
      prolegrpDesc: '请输入组角色描述',
      placeholdername: '',
    },
    adminuser: {
      title: '业务用户管理',
      sysUsempidDis: '员工姓名',
      isDataPermissionsDis: '是否全数据权限',
      sysUsbsrolegrpDis: '业务角色组',
      psysUsbsrolegrpDis: '请选择业务角色组',
      sysUsempid: '绑定员工',
      psysUsempid: '请选择绑定员工',
      userName: '请选择用户',
      assignrole: '分配角色',
      assignorg: '分配组织架构',
      assignorg2: '分配成本中心',
      assignorg3: '分配知识库类型',
      assig1: '分配薪资账套',
      passig1: '请输入薪资账套',
      assig2: '分配社保区域',
      passig2: '请输入社保区域编码',
      cost_searchText: '请输入成本中心名称',
      costCode: '成本中心编码',
      cname: '成本中心名称',
      payssCode: '账套编码',
      payssCN: '账套名称中文',
      payssEN: '账套名称英文',
      bfareaCode: '区域编码',
      bfareaCname: '区域名称中文',
      bfareaEname: '区域名称中文',
      placeholdername: '',
    },
    essrole: {
      title: '自助角色管理',
      title2: '自助角色组管理',
      title3: '自助用户管理',
      sysEssRolegrpDis: 'Ess角色组',
      psysEssRolegrpDis: '请选择Ess角色组',
      placeholdername: '',
    },
    cmutnotic: {
      title: '通知公告管理',
      infoTitle: '请输入标题',
      cmutNoticeTitle: '标题',
      cmutNoticeTypeDis: '类型名称',
      cmutNoticePublish: '发布日期',
      cmutNoticeLosttime: '失效日期',
      cmutNoticeStateDis: '状态',
      pcmutNoticePublish: '请选择日期',
      cmutPublishHour: '请选择时间',
      pcmutNoticeLosttime: '请选择失效日期',
      cmutNoticeType: '通知类型',
      pcmutNoticeType: '请选择通知类型',
      pcmutNoticeTitle: '请输入标题',
      cmutNoticeContent: '发布内容',
      handleUpload: '附件管理',
      phandleUpload: '附件上传',
      pcmutNoticeState: '请选择状态',
      pcmutNoticeContent: '请输入发布内容',
      fileerr: '文件格式错误',
      placeholdername: '',
    },
    adminlog: {
      title: '系统操作日志',
      log_opttime: '请选择操作时间',
      log_funname: '功能节点名称',
      log_opttype: '操作类型',
      log_username: '用户名称',
      plog_opttime: '操作时间',
      log_ip: 'IP地址',
      log_content: '操作内容',
      placeholdername: '',
    },
    adminfun: {
      title: '系统功能管理',
      pfunPidDis: '请选择父功能节点',
      pfunCode: '请输入功能节点编号',
      pfunLancodeDis: '请选择功能节点名称',
      funCode: '功能节点编号',
      funLancodeDis: '功能节点名称',
      funPidDis: '父功能节点',
      funTypeDis: '功能节点分类',
      funStyleDis: '功能节点标识',
      funAction: '节点命令标识',
      funIsctrlbtnDis: '是否控制按钮权限',
      funIsrptDis: '是否统计分析节点',
      validDis: '是否有效',
      TabPane: '系统功能维护',
      funType: '请选择节点分类',
      ppfunAction: '功能节点行为',
      pfunAction: '请输入功能节点行为',
      funStyle: '功能节点标识',
      pfunStyle: '选择功能节点标识',
      funIsctrlbtn: '是否控制按钮权限',
      funImg: '节点图标',
      pfunImg: '请输入图标',
      funIsrpt: '是否统计分析节点',
      funIsprocess: '是否流程节点',
      funProcesid: '业务流程',
      pfunProcesid: '请选择业务流程',
      funIsform: '是否配置表单',
      funIsctrlfield: '是否控制字段权限',
      funFormtype: '表单类型',
      pfunFormtype: '选择表单类型',
      funForm: '表单',
      pfunForm: '请选择表单',
      invdate: '失效日期',
      pinvdate: '选择失效日期',
      invreason: '失效原因',
      pinvreason: '请输入失效原因',
      TabPane2: '系统功能按钮',
      btnOrder: '按钮顺序',
      btnLanCn: '按钮中文名',
      btnLanCnEn: '按钮英文名',
      searchText2: '请输入功能节点名称',
      lanCn: '中文名称',
      lanCode: '编码',
      searchText4: '请输入流程名称',
      flowName: '流程名称',
      upMove: '上移',
      downMove: '下移',
      placeholdername: '',
      // searchTable
      searchTitle: '选择功能节点',
      searchText: '请输入节点名称',
      funLancode: '功能节点名称',
      funCode: '功能节点编号',
    },
    suvadmin: {
      title: '调查问卷设置',
      title2: '调查结果查询',
      infoCode: '请输入调查编号',
      infoType: '请选择样式',
      infoTitle: '请输入调查信息标题',
      platSuvCode: '编号',
      platSuvTitle: '调查信息标题',
      platSuvSubtitle: '副标题',
      platSuvStyleDis: '样式',
      platSuvTo: '收件人',
      platSuvScoringDis: '是否计分',
      platSuvGentime: '预览生成时间',
      platSuvSuggestDis: '是否显示意见建议',
      platSuvDiscontDis: '邮件正文中是否隐藏问题及答案',
      platSuvLinkname: '链接名称',
      preView: '预览',
      editans: '编辑信息',
      platQasOrder: '答案排序',
      platQasQustidDis: '所属调查问题',
      platQasAsweren: '答案描述英文',
      pplatQasAsweren: '请输入答案描述英文',
      platQasAswercn: '答案描述中文',
      pplatQasAswercn: '请输入答案描述中文',
      platQasValid: '是否有效',
      platQasNote: '备注',
      platQasQustid: '请输入调查问题',
      pplatQasOrder: '请输入答案排序',
      ppplatQasOrder: '请输入正确的答案排序',
      platCatOrder: '分类序号',
      platCatDesccn: '分类中文描述',
      pplatCatDesccn: '请输入分类中文描述',
      platCatDescen: '分类英文描述',
      pplatCatDescen: '请输入分类英文描述',
      pplatCatOrder: '请输入分类排序',
      ppplatCatOrder: '请输入正确的分类排序',
      stepQue: '（调查问题）',
      stepClass: '（调查分类信息）',
      stepVary: '（调查表变量）',
      stepAns: '（调查答案信息）',
      divstyle: '选择样式',
      divstyle2: '(点击下一步后自动保存，不可返回修改！)',
      choseType: '上一步',
      showNext: '下一步',
      reset: '完成',
      styleTitle: '矩阵显示（不分类）',
      platQusCatidDis: '问题所属分类',
      platQusOrder: '系统排序',
      platQusDisorder: '显示排序',
      platQusDescen: '问题描述英文',
      pplatQusDescen: '请输入问题描述英文',
      platQusDesccn: '问题描述中文',
      pplatQusDesccn: '请输入问题描述中文',
      platQusAstype: '答案布局类型',
      platQusComments: '是否评论',
      platQusScoring: '是否计分',
      platQusIsmust: '是否必选项',
      pplatQusOrder: '请输入系统排序',
      ppplatQusOrder: '请输入正确的系统排序',
      pplatQusDisorder: '请输入显示排序',
      pplatQusAstype: '请选择答案布局类型',
      platSvaName: '变量标识',
      platSvaCname: '变量名称',
      platSvaColumn: '物理字段',
      pplatSvaName: '请输入变量标识',
      pplatSvaCname: '请输入变量名称',
      pplatSvaColumn: '请输入物理字段',
      surveyid: '调查分类id',
      qplatQasAswercn: '回答说明',
      opinion: '意见及建议',
      opinionconten: '您的意见及建议对我们极具价值，它将有利于提高我们的服务。如果您对 SIS 有其他的意见和建议，请填写在下面对话框内。非常感谢您的配合。',
      primarysub: '【提交】',
      attitude1: '非常满意',
      attitude2: '比较满意',
      attitude3: '满意',
      attitude4: '不太满意',
      attitude5: '非常不满意',
      information: '调查信息',
      classification: '调查问题分类',
      label: '调查问题',
      label2: '调查答案信息',
      label3: '调查表变量',
      urveyva: '初始化成功',
      platSuvSubject: '主题',
      platSuvContent: '正文',
      platSuvOptdesc: '选项说明',
      platSuvBottom: '末尾',
      platSuvSuggestitle: '建议标题',
      platSuvIcworkno: '模板中是否包括员工号',
      pplatSuvGentime: '请选择选择日期',
      platSuvDiscont: '邮件正文中是否隐藏问题及答案',
      pplatSuvTo: '请输入收件人',
      pplatSuvSubject: '请输入主题',
      pplatSuvLinkname: '请输入链接名称',
      pplatSuvContent: '请输入正文',
      ppplatSuvGentime: '请输入预览时间',
      pplatSuvSuggestitle: '请输入建议标题',
      placeholdername: '',
    },
    que: {
      pplatRasEmpName: '请输入员工姓名',
      pplatRasEmpNo: '请输入员工号',
      platRasEmpName: '员工姓名',
      platRasEmpNo: '员工唯一编号',
      platRcdSuvidDis: '调查定义标题',
      platRasQustidDis: '问题中文',
      platRasAnsweren: '答案英文',
      platRasAnswercn: '答案中文',
      platRasValue: '分值',
      placeholdername: '',
    },
    imp: {
      title: '导入模板管理',
      paramCode: '请选择系统功能节点',
      pfileName: '请输入文件名称',
      fileName: '文件名',
      fileFuncode: '功能节点编码',
      fileFuncodeDis: '系统功能节点',
      searchText: '请输入参数类型编码',
      pmtypeCode: '参数类型编码',
      pmtypeName: '参数类型名称',
      pfileFuncodeDis: '请选择系统功能节点',
      up1: '上传',
      up2: '文件名称',
      up3: '上传模板',
      comment: '备注',
      pcomment: '请输入备注',
      contentw: '文件必须是xls或xlsx格式',
      downlo: '获取文件失败',
      placeholdername: '',
    },
  },
  'en-US': {
    imp: {
      title: 'Import template management',
      paramCode: 'Please select the system function node',
      pfileName: 'Please enter the file name',
      fileName: 'The file name',
      fileFuncode: 'Function node coding',
      fileFuncodeDis: 'System function node',
      searchText: 'Please enter the parameter type code',
      pmtypeCode: 'Parameter type coding',
      pmtypeName: 'Parameter type name',
      pfileFuncodeDis: 'Please select the system function node',
      up1: 'upload',
      up2: 'The file name',
      up3: 'Upload the template',
      comment: 'remarks',
      pcomment: 'Please enter remarks',
      contentw: 'The file must be in XLS or XLSX format',
      downlo: 'Failed to get file',
      placeholdername: '',
    },
    que: {
      pplatRasEmpName: 'Please enter the employee name',
      pplatRasEmpNo: 'Please enter the employee number',
      platRasEmpName: 'Employee name',
      platRasEmpNo: 'Employees working',
      platRcdSuvidDis: 'Survey definition title',
      platRasQustidDis: 'The problem in Chinese',
      platRasAnsweren: 'The answer in English',
      platRasAnswercn: 'The answer in Chinese',
      platRasValue: 'score',
      placeholdername: '',
    },
    suvadmin: {
      title: 'Questionnaire setting',
      title2: 'Enquiries on survey results',
      infoCode: 'Please enter the survey number',
      infoType: 'Please select style',
      infoTitle: 'Please enter the title of the survey information',
      platSuvCode: 'Serial number',
      platSuvTitle: 'Survey information title',
      platSuvSubtitle: 'subtitle',
      platSuvStyleDis: 'style',
      platSuvTo: 'The recipient',
      platSuvScoringDis: 'Whether the scoring',
      platSuvGentime: 'Preview build time',
      platSuvSuggestDis: 'Whether to display comments and Suggestions',
      platSuvDiscontDis: 'Whether questions and answers are hidden in the body of the message',
      platSuvLinkname: 'The name of the link',
      preView: 'preview',
      editans: 'Edit the information',
      platQasOrder: 'The answer to sort',
      platQasQustidDis: 'Survey questions',
      platQasAsweren: 'Answer description English',
      pplatQasAsweren: 'Please enter the answer description in English',
      platQasAswercn: 'Answer description in Chinese',
      pplatQasAswercn: 'Please enter the answer description in Chinese',
      platQasValid: 'The validity of',
      platQasQustid: 'Please enter the survey questions',
      pplatQasOrder: 'Please enter the answer sort',
      ppplatQasOrder: 'Please enter the correct answer order',
      platCatOrder: 'Classification number',
      platCatDesccn: 'Classification Chinese description',
      pplatCatDesccn: 'Please enter the Chinese description of the classification',
      platCatDescen: 'Classification English description',
      pplatCatDescen: 'Please enter the English description of classification',
      pplatCatOrder: 'Please enter the category order',
      ppplatCatOrder: 'Please enter the correct category order',
      stepQue: '（Survey questions）',
      stepClass: '（Survey classified information）',
      stepVary: '（Questionnaire variable）',
      stepAns: '（Survey answer information）',
      divstyle: 'Choose the style',
      divstyle2: '(Click next to save automatically, can not return to modify!)',
      choseType: 'The previous step',
      showNext: 'The next step',
      reset: 'complete',
      styleTitle: 'Matrix display (not classified)',
      platQusCatidDis: 'Problem classification',
      platQusOrder: 'Sorting system',
      platQusDisorder: 'According to the sorting',
      platQusDescen: 'Problem description English',
      pplatQusDescen: 'Please enter the question description in English',
      platQusDesccn: 'Problem description Chinese',
      pplatQusDesccn: 'Please enter the question description in Chinese',
      platQusAstype: 'Answer layout type',
      platQusComments: 'Whether the comments',
      platQusScoring: 'Whether the scoring',
      platQusIsmust: 'Whether or not required',
      pplatQusOrder: 'Please enter system sort',
      ppplatQusOrder: 'Please enter the correct system sort',
      pplatQusDisorder: 'Please enter display sort',
      pplatQusAstype: 'Select the answer layout type',
      platSvaName: 'Variables identify',
      platSvaCname: 'The variable name',
      platSvaColumn: 'The physical field',
      pplatSvaName: 'Please enter the variable identifier',
      pplatSvaCname: 'Please enter the variable name',
      pplatSvaColumn: 'Please enter the physical field',
      surveyid: 'Survey category id',
      qplatQasAswercn: 'To answer that',
      opinion: 'Comments and Suggestions',
      opinionconten: 'Your comments and Suggestions are of great value to us and will help us improve our service.If you have any other comments or Suggestions about SIS, please fill in the following dialog box.Thank you very much for your cooperation。',
      primarysub: '【submit】',
      attitude1: 'Very satisfied with',
      attitude2: 'satisfied',
      attitude3: 'Satisfied with the',
      attitude4: 'Not satisfied with',
      attitude5: 'Very dissatisfied',
      information: 'The survey information',
      classification: 'Classification of survey questions',
      label: 'Survey questions',
      label2: 'Survey answer information',
      label3: 'Questionnaire variable',
      urveyva: 'Initialization successful',
      platSuvSubject: 'The theme',
      platSuvContent: 'The body of the',
      platSuvOptdesc: 'Option to show',
      platSuvBottom: 'At the end of',
      platSuvSuggestitle: 'Suggest the title',
      platSuvIcworkno: 'Whether the employee number is included in the template',
      pplatSuvGentime: 'Please select the date',
      platSuvDiscont: 'Whether questions and answers are hidden in the body of the message',
      pplatSuvTo: 'Please enter recipient',
      pplatSuvSubject: 'Please enter a subject',
      pplatSuvLinkname: 'Please enter the link name',
      pplatSuvContent: 'Please enter text',
      ppplatSuvGentime: 'Please enter the preview time',
      pplatSuvSuggestitle: 'Please enter the suggested title',
      placeholdername: '',
    },
    adminfun: {
      title: 'System function management',
      pfunPidDis: 'Select the parent function node',
      pfunCode: 'Please enter the function node number',
      pfunLancodeDis: 'Select the function node name',
      funCode: 'Function node number',
      funLancodeDis: 'Function node name',
      funPidDis: 'Parent function node',
      funTypeDis: 'Functional node classification',
      funStyleDis: 'Function node identification',
      funAction: 'Node command identification',
      funIsctrlbtnDis: 'Whether to control button permissions',
      funIsrptDis: 'Whether to statistically analyze nodes',
      validDis: 'The validity of',
      TabPane: 'System function maintenance',
      funType: 'Select node classification',
      ppfunAction: 'Function node behavior',
      pfunAction: 'Please enter the function node behavior',
      funStyle: 'Function node identification',
      pfunStyle: 'Select the function node identity',
      funIsctrlbtn: 'Whether to control button permissions',
      funImg: 'Node icon',
      pfunImg: 'Please enter icon',
      funIsrpt: 'Whether to statistically analyze nodes',
      funIsprocess: 'Whether the process node',
      funProcesid: 'The business process',
      pfunProcesid: 'Select the business process',
      funIsform: 'Whether to configure the form',
      funIsctrlfield: 'Whether field permissions are controlled',
      funFormtype: 'Form type',
      pfunFormtype: 'Select form type',
      funForm: 'The form',
      pfunForm: 'Please select the form',
      invdate: 'Expiry date',
      pinvdate: 'Select expiration date',
      invreason: 'The failure reason',
      pinvreason: 'Please enter the reason for failure',
      TabPane2: 'System function button',
      btnOrder: 'Button order',
      btnLanCn: 'Button Chinese name',
      btnLanCnEn: 'English name of button',
      searchText2: 'Please enter the function node name',
      lanCn: 'Chinese name',
      lanCode: 'coding',
      searchText4: 'Please enter the process name',
      flowName: 'The name of the process',
      upMove: 'Move up',
      downMove: 'Move down',
      placeholdername: '',
      // searchTable
      searchTitle: 'Select function node',
      searchText: 'Please enter the node name',
      funLancode: 'NodeName',
      funCode: 'NodeCode',
    },
    adminlog: {
      title: 'System operation log',
      log_opttime: 'Please select the operation time',
      log_funname: 'Function node name',
      log_opttype: 'Operation type',
      log_username: 'The user name',
      plog_opttime: 'Operating time',
      log_ip: 'The IP address',
      log_content: 'Operating content',
      placeholdername: '',
    },
    cmutnotic: {
      title: 'Please select notification announcement management',
      infoTitle: 'Please enter the title',
      cmutNoticeTitle: 'The title',
      cmutNoticeTypeDis: 'Type the name',
      cmutNoticePublish: 'The release date',
      cmutNoticeLosttime: 'Expiry date',
      cmutNoticeStateDis: 'state',
      pcmutNoticePublish: 'Please select date',
      cmutPublishHour: 'Please select time',
      pcmutNoticeLosttime: 'Please select the expiry date',
      cmutNoticeType: 'Notification type',
      pcmutNoticeType: 'Please select the notification type',
      pcmutNoticeTitle: 'Please enter the title',
      cmutNoticeContent: 'Publish content',
      handleUpload: 'Attachment management',
      phandleUpload: 'The attachment upload',
      pcmutNoticeState: 'Please select the state',
      pcmutNoticeContent: 'Please enter the published content',
      fileerr: 'File format error',
      placeholdername: '',
    },
    essrole: {
      title: 'Self-service role management',
      title2: 'Self-service role group management',
      title3: 'Self-service user management',
      sysEssRolegrpDis: 'Ess character set',
      psysEssRolegrpDis: 'Please select the Ess role group',
      placeholdername: '',
    },
    adminuser: {
      title: 'Business user management',
      sysUsempidDis: 'Employee name',
      isDataPermissionsDis: 'Whether full data permissions',
      sysUsbsrolegrpDis: 'Business role group',
      psysUsbsrolegrpDis: 'Select the business role group',
      sysUsempid: 'Binding employees',
      psysUsempid: 'Select bind employee',
      userName: 'Please select user',
      assignrole: 'Assign roles',
      assignorg: 'Distribution organizational structure',
      assignorg2: 'Distribution cost center',
      assignorg3: 'Assign the knowledge base type',
      assig1: 'Allocate payroll account set',
      passig1: 'Please enter salary account set',
      assig2: 'Allocated social security area',
      passig2: 'Please enter the code of social security area',
      cost_searchText: 'Please enter the name of the cost center',
      costCode: 'Cost center coding',
      cname: 'Chinese name',
      payssCode: 'Zhang set of encoding',
      payssCN: 'Account set name in Chinese',
      payssEN: 'Account set name in English',
      bfareaCode: 'Area code',
      bfareaCname: 'Area name Chinese',
      bfareaEname: 'Area name Chinese',
      placeholdername: '',
    },
    admingrprole: {
      title: 'Business role group management',
      prolegrpCname: 'Please enter the role group name',
      searchText: 'Please enter the role name',
      roleCname: 'role',
      rolegrpCode: 'Role group coding',
      rolegrpCname: 'Role group name in Chinese',
      rolegrpEname: 'Role group name in English',
      rolegrpTypeDis: 'Role group type',
      validDis: 'The validity of',
      invdate: 'Expiry date',
      prolegrpCode: 'Please enter the role group code',
      pprolegrpCname: 'Please enter the Chinese name of the role group',
      prolegrpEname: 'Please enter the English name of the role group',
      rolegrpDesc: 'Role group description',
      prolegrpDesc: 'Enter the group role description',
      placeholdername: '',
    },
    adminrole: {
      title1: 'Business role management',
      proleCname: 'Please enter the role name',
      roleCode: 'Character encoding',
      roleCname: 'Role name Chinese',
      roleEname: 'Role name English',
      roleTypeDis: 'The role type',
      proleTypeDis: 'Please select the role type',
      validDis: 'The validity of',
      invdate: 'Expiry date',
      checkHr: 'HR business partners cannot be deleted',
      proleCode: 'Please enter the role code',
      pproleCname: 'Please enter the Chinese name of the character',
      proleEname: 'Please enter the English name of the role',
      valid: 'Whether the selection is valid or not',
      roleDesc: 'Role description',
      proleDesc: 'Please enter the role description',
      pinvdate: 'Select expiration date',
      invreason: 'The failure reason',
      pinvreason: 'Please enter the reason for failure',
      flagBox: 'Distribution of button',
      plalist: 'Assign list fields',
      Optional: 'Optional field',
      Optional2: 'Selected field',
      flagBox2: 'Assign edit fields',
      flow: 'Allocation process',
      floauth: 'Processing permissions',
      sffFieldNameDis: 'The display name',
      sffPropertyDis: 'The field properties',
      sffLayoutDis: 'The layout type',
      ffLayo: 'Field permissions',
      ffLayodis: 'Default display field permissions',
      warcontent: 'Please select the processing permissions for the process steps before saving',
      wartatle: 'Save failed',
      warcontent2: 'Please select the processing permissions in the data block before saving',
      todotatle1: 'Select to-do items',
      todotitle2: 'To-do items have been selected',
      autdNo: 'Item number',
      autdName: 'Item name',
      placfun: 'Distribution of nodes',
      placauthset: 'Access configuration',
      pletodo: 'To-do assignment',
      placeholdername: '',
    },
    adminpminfo: {
      pminfotitle: 'Parameter information management',
      pparamCode: 'Please enter the common parameter code',
      pparamInfoName: 'Please enter a common parameter name',
      pparamName: 'Please select the parameter type',
      paramCode: 'Common parameter coding',
      paramTypeDis: 'Common parameter type',
      paramInfoName: 'Common parameter name',
      paramInfoCn: 'Name in Chinese',
      paramInfoEn: 'English name display',
      placeholdername: '',
      pparamInfoCn: 'Please enter your name in Chinese',
      pparamInfoEn: 'Please enter your name in English',
    },
    adminpmtype: {
      pmtypetitle: 'Parameter type management',
      ppmtypeCode: 'Please enter the parameter type encoding',
      pmtypeCode: 'Parameter type encoding',
      pmtypeName: 'Parameter type name',
      ppmtypeName: 'Please enter a type name',
      pmtypeIsupdate: 'Is it modifiable',
      comment: 'remarks',
      pcomment: 'Please enter remarks',
      placeholdername: '',
    },
  },
}
