export default {
  'zh-CN': {
    sihfHfrepay: {
      title: '公积金详细信息',
      title1: '公积金补缴申请',
      title2: '公积金补缴确认',
      title3: '补缴申报结果',
      sihfrpCompany: '公司',
      sihfrpDept: '部门',
      sihfrpEmpworkno: '员工工号',
      sihfrpEmpgid: '唯一标识号',
      sihfrpCname: '中文名',
      sihfrpLastname: 'Last Name',
      sihfrpFirstname: 'First Name',
      sihfrpIdtype: '证件类型',
      sihfrpIdno: '证件号码',
      sihfrpEmptype: '员工类型',
      sihfrpBenefitlocation: '补缴公积金缴纳地',
      sihfrpBenefitpolicy: '补缴公积金政策',
      sihfrpBenefittype: '补缴公积金开户类别',
      sihfrpSmonth: '补缴开始月',
      sihfrpEmonth: '补缴结束月',
      sihfrpPaymonth: '补缴扣费月',
      sihfrpBaseamt: '每月补缴基数',
      sihfrpReason: '补缴原因',
      sihfrpStatus: '状态',
      sihfrpApplicant: '申请人',
      sihfrpApplytime: '申请时间',
      sihfrpIsconfirm: '是否确认',
      sihfrpNocmreason: '未确认原因',
      sihfrpConfirmer: '确认人',
      sihfrpConfirmtime: '确认时间',
      sihfrpConfirmrecord: '确认记录',
      sihfrpSbperson: '申报人',
      sihfrpSbtime: '申报时间',
      sihfrpSberror: '申报失败原因',
      sihfrpComment: '备注',
      sihfrpCompanyPrompt: '请选择公司',
      sihfrpEmpworknoPrompt: '请输入员工工号',
      sihfrpCnamePrompt: '请输入员工中文名',
      sihfrpDeptPrompt: '请选择部门',
      sihfrpBenefitlocationPrompt: '请选择补缴公积金缴纳地',
      sihfrpBenefitpolicyPrompt: '请选择补缴公积金政策',
      sihfrpBenefitlocationWarning: '请选择补缴公积金缴纳地',
      sihfrpBenefittypeWarning: '请选择补缴公积金开户类别',
      sihfrpBaseamtWarning: '请输入正确的补缴基数',
      sihfrpReasonWarning: '请输入补缴原因',
      sihfrpNocmreasonPrompt: '请输入未确认原因',
      sihfrpEmpworknoWarning: '请选择员工信息',
      sihfrpSmonthWarning: '请输入补缴开始月',
      sihfrpEmonthWarning: '请输入补缴结束月',
      sihfrpPaymonthWarning: '请输入补缴扣费月',
      empWarning: '请先选择公司和部门',
    },
    sihfHfrepayInsurance: {
      title: '公积金险种信息',
      sihfrpinsInsurance: '险种',
      sihfrpinsBaseamt: '每月补缴基数',
      sihfrpinsCompratio: '每月公司补缴比例(%)',
      sihfrpinsCompamt: '每月公司补缴金额',
      sihfrpinsCompsum: '公司补缴合计',
      sihfrpinsPersratio: '每月个人补缴比例(%)',
      sihfrpinsPersamt: '每月个人补缴金额',
      sihfrpinsPerssum: '个人补缴合计',
      sihfrpinsComment: '备注',
    },
    base: {
      sihfrpIsconfirmDis: '是否确认',
      che1: '确认当前选中的数据是否全部确认',
      che2: '您有数据未进行确认处理，请进行确认',
      check1: '确认数据',
      isConfirm: '是否确认',
      noreason: '不确认原因',
      pnoreason: '请输入未确认原因',
      yesconfirm: '请选择是否确认',
      reminder: '确认数据成功',
      select: '已确认待申报',
      declare: '申报成功',
      declaref: '申报失败',
      declarefw: '已申报，不能重复申报',
      declarefw2: '请确定提交',
      sihfrpinsComment: '',
      sihfrpinsComment: '',
    },
  },
  'en-US': {
    base: {
      sihfrpIsconfirmDis: '公积金险种信息',
      sihfrpinsComment: '',
      check1: 'Confirm the data',
      isConfirm: 'Whether to confirm',
      noreason: 'Do not confirm the reason',
      pnoreason: 'Please enter the unconfirmed reason',
      yesconfirm: 'Please select whether to confirm',
      reminder: 'Confirm data success',
      select: 'The declaration has been confirmed',
      declare: 'Declare success',
      declaref: 'Declare failure',
      declarefw: 'Declaration has been made and cannot be repeated',
      declarefw2: 'Please make sure to submit',
    },
    sihfHfrepay: {
      title: 'Accumulation fund details',
      title1: 'Application for supplementary payment of public accumulation fund',
      title2: 'Accumulation fund makes up confirm',
      title3: 'The result of the supplementary declaration',
      sihfrpCompany: 'The company',
      sihfrpDept: 'department',
      sihfrpEmpworkno: 'Employees working',
      sihfrpEmpgid: 'Unique identification number',
      sihfrpCname: 'Chinese name',
      sihfrpLastname: 'Last Name',
      sihfrpFirstname: 'First Name',
      sihfrpIdtype: 'Document type',
      sihfrpIdno: 'I.d.',
      sihfrpEmptype: 'Employee type',
      sihfrpBenefitlocation: 'Make up pay accumulation fund pay ground',
      sihfrpBenefitpolicy: 'Make up accumulation fund policy',
      sihfrpBenefittype: 'Make up pay accumulation fund to open an account category',
      sihfrpSmonth: 'Starting month of supplementary payment',
      sihfrpEmonth: 'Month of completion of supplementary payment',
      sihfrpPaymonth: 'Monthly supplementary payment of withholding fee',
      sihfrpBaseamt: 'Monthly supplementary payment base',
      sihfrpReason: 'Payment of reason',
      sihfrpStatus: 'state',
      sihfrpApplicant: 'The applicant',
      sihfrpApplytime: 'To apply for time',
      sihfrpIsconfirm: 'Whether to confirm',
      sihfrpNocmreason: 'Reasons not confirmed',
      sihfrpConfirmer: 'Confirm the people',
      sihfrpConfirmtime: 'Set the time',
      sihfrpConfirmrecord: 'Confirm that the record',
      sihfrpSbperson: 'The notifier',
      sihfrpSbtime: 'The time',
      sihfrpSberror: 'Reasons for failure to declare',
      sihfrpComment: 'note',
      sihfrpCompanyPrompt: 'Please select company',
      sihfrpEmpworknoPrompt: 'Please enter the employee number',
      sihfrpCnamePrompt: 'Please enter your employee\'s Chinese name',
      sihfrpDeptPrompt: 'Please select department',
      sihfrpBenefitlocationPrompt: 'Please select the place to pay the accumulation fund',
      sihfrpBenefitpolicyPrompt: 'Please choose to make up the accumulation fund policy',
      sihfrpBenefitlocationWarning: 'Please select the place to pay the accumulation fund',
      sihfrpBenefittypeWarning: 'Please select the account type of CPF',
      sihfrpBaseamtWarning: 'Please enter the correct payment base',
      sihfrpReasonWarning: 'Please enter the reason for the supplementary payment',
      sihfrpNocmreasonPrompt: 'Please enter the unconfirmed reason',
      sihfrpEmpworknoWarning: 'Please select employee information',
      sihfrpSmonthWarning: 'Please enter the starting month of the supplementary payment',
      sihfrpEmonthWarning: 'Please enter the end month of the supplementary payment',
      sihfrpPaymonthWarning: 'Please enter the month of repayment fee',
      empWarning: 'Please select the company and department first',
    },
    sihfHfrepayInsurance: {
      title: 'Provident fund insurance information',
      sihfrpinsInsurance: 'Danger is planted',
      sihfrpinsBaseamt: 'Monthly supplementary payment base',
      sihfrpinsCompratio: 'Monthly company supplementary payment ratio(%)',
      sihfrpinsCompamt: 'Monthly company supplementary payment',
      sihfrpinsCompsum: 'Total of the company\'s supplementary payment',
      sihfrpinsPersratio: 'Monthly individual contribution proportion(%)',
      sihfrpinsPersamt: 'Monthly individual supplementary payment',
      sihfrpinsPerssum: 'Total individual supplementary payment',
      sihfrpinsComment: 'note',
    },
  },
}
