export default {
  'zh-CN': {
    platCalendar: {
      title: '薪资日历计划',
      title1: '工作日历管理',
      calendartitle: '转换为日历模式',
      clipboardtitle: '转换为表格模式',
      lastM: '上月',
      nextM: '下月',
      sun: '星期日',
      mon: '星期一',
      tues: '星期二',
      wed: '星期三',
      thurs: '星期四',
      fri: '星期五',
      sat: '星期六',
      legHoliday: '法定节假日',
      comHoliday: '公司节假日',
      legRestDay: '法定休息日',
      comRestDay: '公司休息日',
      calendarDate: '日期',
      calendarLegaltypeName: '法定日期类型',
      calendarComptypeName: '公司日期类型',
      calendarDesc: '休假日说明',
      errReminder: '请选择年月！',
      comment: '备注',
      sYear: '起始年份',
      eYear: '结束年份',
      calendarLegaltypeNameDis: '请选择法定日期类型',
      calendarComptypeNameDis: '请选择公司日期类型',
      commentDis: '请输入备注...',
      sYearDis: '请输入起始年份',
      eYearDis: '请输入结束年份',
    },
    platFiscalyear: {
      title: '财年信息管理',
      fyYear: '财年信息',
      fyYearM: '财年信息管理',
      fyMark1: '财年标识1',
      fyMark2: '财年标识2',
      fyMark3: '财年标识3',
      fyAlcalcdate: '年假计算截止日期',
      fyAlclosedate: '年假休假截止日期',
      fySdate: '财年开始日期',
      fyEdate: '财年结束日期',
      comment: '备注',
      fyYearDis: '请输入财年',
      fyMark1Dis: '请输入财年标识1',
      fyMark2Dis: '请输入财年标识2',
      fyMark3Dis: '请输入财年标识3',
      fyAlcalcdateDis: '选择年假计算截止日期',
      fyAlclosedateDis: '选择年假休假截止日期',
      fySdateDis: '选择财年开始日期',
      fyEdateDis: '选择财年结束日期',
      commentDis: '请输入备注...',
    },
    PlatFyperiod: {
      title: '财年期间管理',
      selectTitle: '选择期间',
      fypdYear: '财年',
      fypdPeriod: '期间',
      fypdMark1: '期间标识1',
      fypdMark2: '期间标识2',
      fypdMark3: '期间标识3',
      fypdStartdate: '开始日期',
      fypdEnddate: '结束日期',
      fypdSearch: '财年期间弹出框',
      comment: '备注',
      fypdPeriodDis: '请输入期间',
      fypdMark1Dis: '请输入期间标识1',
      fypdMark2Dis: '请输入期间标识2',
      fypdMark3Dis: '请输入期间标识3',
      fypdStartdateDis: '选择开始日期',
      fypdEnddateDis: '选择结束日期',
      commentDis: '请输入备注...',
    },
    platEmpno: {
      title: '员工工号管理',
      empno: '员工工号',
      companys: '公司范围',
      validName: '是否有效',
      sEmpNo: '起始员工工号',
      eEmpNo: '结束员工工号',
      comment: '备注',
      empnoDis: '请输入员工号',
      companysDis: '请输入公司范围',
      validNameDis: '请选择是否有效',
      sEmpNoDis: '请输入起始员工工号',
      eEmpNoDis: '请输入结束员工工号',
      commentDis: '请输入备注...',
    },
    platPostno: {
      title: '职位编号管理',
      postno: '职位编号',
      companys: '公司范围',
      validName: '是否可用',
      sPostNo: '起始岗位号',
      ePostNo: '结束岗位号',
      comment: '备注',
      postnoDis: '请输入岗位号',
      companysDis: '请输入公司范围',
      validNameDis: '请选择是否有效',
      sPostNoDis: '请填写起始岗位号',
      ePostNoDis: '请填写结束岗位号',
      commentDis: '请输入备注...',
    },
    platBenefitarea: {
      platBenefitarea: '社保区域管理',
      bfareaCode: '区域编码',
      bfareaCodeDis: '请输入区域编码',
      bfareaCname: '区域名称中文',
      bfareaCnameDis: '请输入区域名称中文',
      bfareaEname: '区域名称英文',
      bfareaEnameDis: '请输入区域名称英文',
      bfareaType: '区域划分',
      bfareaTypeDis: '选择区域划分',
      comment: '备注',
      commentDis: '请输入备注',
      distCity: '分配城市',
      distCompany: '分配公司',
      selectCity: '可选择城市',
      selectedCity: '已选择城市',
      cityName: '城市名称',
      companyName: '公司名称',
      selectCompany: '可选择公司',
      selectedCompany: '已选择公司',
      bfareaName: '请输入区域中/英文...',
      dist: '分配',
    },
    autotasklog: {
      autotasklog: '自动任务日志',
      atlogAtskidNameIns: '请选择自动任务...',
      sdateIns: '选择开始日期',
      edateIns: '选择结束日期',
      atlogRuntypeIns: '请输入执行类型...',
      atlogStatusIns: '请选择状态...',
      atskName: '自动任务名称',
      atskTypeName: '自动任务类型',
      atlogRuntime: '执行时间',
      atlogRuntype: '执行类型',
      atlogAtskidName: '自动任务',
      atlogStatusName: '状态',
      atlogError: '错误信息',
      comment: '备注',
    },
    syswx: {
      syswx: '微信模板管理',
      syswxNo: '模板编号',
      syswxTypeDis: '消息类型',
      syswxTitle: '标题',
      syswxContent: '内容',
      syswxTo: '接收人',
      syswxSendcondition: '发送条件',
      syswxLink: '卡片链接',
      syswxIsvalid: '是否有效',
      syswxInvreason: '失效原因',
      syswxComment: '备注',
      syswxNoIns: '请输入模板编号',
      syswxTypeDisIns: '请选择消息类型',
      syswxTitleIns: '请输入标题',
      syswxContentIns: '请输入内容',
      syswxToIns: '请输入接收人',
      syswxSendconditionIns: '请输入发送条件',
      syswxLinkIns: '请输入卡片链接',
      syswxIsvalidIns: '请选择是否有效',
      syswxInvreasonIns: '请输入失效原因',
      syswxCommentIns: '请输入备注',
      syswxInfo: '微信模板信息',
      syswxvarInfo: '微信模板变量',
      syswxNoIns2: '仅支持数字格式模板编号',
      syswxvarMark: '变量标识',
      syswxvarName: '变量名称',
      syswxvarValdesc: '取值说明',
      syswxvarComment: '备注',
      syswxvarMarkIns: '请输入变量标识',
      syswxvarNameIns: '请输入变量名称',
      syswxvarValdescIns: '请输入取值说明',
      syswxvarCommentIns: '请输入备注',
    },
    autoTask: {
      autoTask: '自动任务配置',
      autoTaskInfo: '自动任务配置内容',
      atskNo: '自动任务编号',
      atskName: '自动任务名称',
      atskIsvalid: '是否有效',
      atskJobid: '任务JOBID',
      atskClass: '任务执行类名',
      atskType: '任务类型',
      atskPrommode: '提醒方式',
      atskTemptable: '自动提醒临时表',
      atskAdvancedays: '提前天数',
      atskDurationdays: '持续天数',
      atskFrequency: '执行频率',
      atskTime: '执行时间',
      atskRunmonth: '请选择月...',
      atskRunday: '请选择日...',
      atskRunhour: '请选择时...',
      atskRunminute: '请选择分...',
      atskRunweek: '请选择周...',
      atskIntervalminutes: '间隔分钟',
      atskSendamount: '间隔发送数量',
      atskRunsdate: '执行开始时间',
      atskRunedate: '执行结束时间',
      atskLasttime: '最后执行时间',
      atskMailtempName: '邮件模板',
      atskSurveyName: '调查定义',
      atskSmsName: '短信模板',
      atskWxName: '微信模板',
      atskPromkey: '提醒数据主键标识',
      atskFlowdatakey: '流程数据主键标识',
      atskComment: '备注',
      atskNoIns: '请输入自动任务编号',
      atskNameIns: '请输入自动任务名称',
      atskJobidIns: '请输入任务JOBID',
      atskClassIns: '请输入任务执行类名',
      atskMailtempNameIns: '请选择邮件模板',
      atskSurveyNameIns: '请选择调查定义',
      atskSmsNameIns: '请选择短信模板',
      atskWxNameIns: '请选择微信模板',
      atskPromkeyIns: '请输入提醒数据主键标识',
      atskFlowdatakeyIns: '请输入流程数据主键标识',
      atskCommentIns: '请输入备注',
      atskFrequencyIns: '请设置执行频率',
      atskPrommodeIns: '至少选择一个布局方式',
      plat_atsk_temp01: '自动任务临时表01',
      plat_atsk_temp02: '自动任务临时表02',
      plat_atsk_temp03: '自动任务临时表03',
      plat_atsk_temp04: '自动任务临时表04',
      plat_atsk_temp05: '自动任务临时表05',
      plat_atsk_temp06: '自动任务临时表06',
      plat_atsk_temp07: '自动任务临时表07',
      plat_atsk_temp08: '自动任务临时表08',
      plat_atsk_temp09: '自动任务临时表09',
      plat_atsk_temp10: '自动任务临时表10',
      platSuvCode: '编号',
      platSuvTitle: '标题',
      sysmailName: '模板名称',
      sysmailObject: '主题',
      syssmsNo: '模板编号',
      syssmsTitle: '标题',
      month: ' 月',
      day: ' 日',
      hour: ' 时',
      minut: ' 分',
      atskdfClmmark: '数据项标识',
      atskdfClmcn: '数据项标识中文',
      atskdfClmen: '数据项标识英文',
      atskdfMailvarName: '邮件变量',
      atskdfSurveyvarName: '调查变量',
      atskdfSmsvarName: '短信变量',
      atskdfWxvarName: '微信变量',
      atskdfGetvalbyclmName: '反查定义',
      atskdfComment: '备注',
      platSvaCname: '变量名称',
      platSvaName: '变量标识',
      sysmlvarName: '变量名称',
      sysmlvarMark: '变量标识',
      syssmsvarName: '变量名称',
      syssmsvarMark: '变量标识',
      syswxvarName: '变量名称',
      syswxvarMark: '变量标识',
      sourceName: '服务名称',
      vffPropname: '属性名称',
      vffProperty: '关联属性',
      atskdfClmmarkIns: '请输入数据项标识',
      atskdfClmcnIns: '请输入数据项标识中文',
      atskdfClmenIns: '请输入数据项标识英文',
      atskdfMailvarNameIns: '请输入邮件变量',
      atskdfSurveyvarNameIns: '请输入调查变量',
      atskdfSmsvarNameIns: '请输入短信变量',
      atskdfWxvarNameIns: '请输入微信变量',
      atskdfGetvalbyclmNameIns: '请输入反查定义',
      atskdfCommentIns: '请输入备注',
    },
    platFlowVar: {
      platFlowVar: '业务变量管理',
      flvarMarkIns2: '请输入变量标识或名称',
      flvarFormtype: '表单类型',
      flvarFlow: '表单',
      flvarMark: '变量标识',
      flvarName: '变量名称',
      flvarValresource: '变量取值来源',
      flvarSysval: '系统变量',
      flvarFiled: '流程字段',
      flvarGetvalbyfiled: '反查服务',
      flvarRtndatafmt: '返回数据类型',
      flvarDatefmt: '日期格式',
      flvarIscondition: '是否条件设置',
      comment: '备注',
      flvarFormtypeIns: '请输入表单类型',
      flvarFlowIns: '请输入表单',
      flvarMarkIns: '请输入变量标识',
      flvarNameIns: '请输入变量名称',
      flvarValresourceIns: '请输入变量取值来源',
      flvarSysvalIns: '请输入系统变量',
      flvarFiledIns: '请输入流程字段',
      flvarGetvalbyfiledIns: '请输入反查服务',
      flvarRtndatafmtIns: '请输入返回数据类型',
      flvarDatefmtIns: '请输入日期格式',
      flvarIsconditionIns: '请输入是否条件设置',
      commentIns: '请输入备注',
      sformName: '表单名称',
      sformTbname: '物理表名',
      sffPhyfield: '物理字段名称',
      sffFieldNameCnDis: '字段名称',
      sourceName: '服务名称',
      vffPropname: '属性名称',
      vffProperty: '关联属性',
      flvarField: '变量字段',
    },
    platFlowcontacts: {
      platFlowcontacts: '业务联系人管理',
      flcontFormtype: '表单类型',
      flcontFlowName: '表单',
      flcontMark: '联系人标识',
      flcontName: '联系人名称',
      flcontValueName: '联系人取值变量',
      comment: '备注',
      flcontFormtypeIns: '请选择表单类型',
      flcontFlowNameIns: '请选择表单',
      flcontMarkIns: '请输入联系人标识',
      flcontNameIns: '请输入联系人名称',
      flcontValueNameIns: '请选择联系人取值变量',
      commentIns: '请输入备注',
      sformName: '表单名称',
      sformTbname: '物理表名',
      flvarName: '流程变量名称',
      flvarMark: '流程变量标识',
      flcontMarkIns2: '请输入标识或名称',
    },
  },
  'en-US': {
    platCalendar: {
      title: 'Work calendar management',
      calendartitle: 'Convert to calendar mode',
      clipboardtitle: 'Convert to table mode',
      lastM: 'last month',
      nextM: 'Next month',
      sun: 'Sunday',
      mon: 'Monday',
      tues: 'Tuesday',
      wed: 'Wednesday',
      thurs: 'Thursday',
      fri: 'Friday',
      sat: 'Saturday',
      legHoliday: 'Legalholidays',
      comHoliday: 'CompanyHolidays',
      legRestDay: 'LegalRestDays',
      comRestDay: 'CompanyRestDays',
      calendarDate: 'Date',
      calendarLegaltypeName: 'Legal date type',
      calendarComptypeName: 'Company date type',
      calendarDesc: 'Holiday explanation',
      errReminder: 'Please select year and month！',
      comment: 'Comment',
      sYear: 'Starting Year',
      eYear: 'Ending Year',
      calendarLegaltypeNameDis: 'Please select a legal date type',
      calendarComptypeNameDis: 'Please select company date type',
      commentDis: 'Please enter comment...',
      sYearDis: 'Please enter the starting year',
      eYearDis: 'Please enter the ending year',
    },
    platFiscalyear: {
      title: 'Fiscal Year Information Management',
      fyYearM: 'Fiscal Year Information',
      fyYear: 'Fiscal Year',
      fyMark1: 'Fiscal Year Mark1',
      fyMark2: 'Fiscal Year Mark2',
      fyMark3: 'Fiscal Year Mark3',
      fyAlcalcdate: 'Annual leave calculation deadline',
      fyAlclosedate: 'Vacation leave deadline',
      fySdate: 'Fiscal Year Start Date',
      fyEdate: 'Fiscal Year End Date',
      comment: 'Comment',
      fyYearDis: 'Please enter fiscal year',
      fyMark1Dis: 'Please enter fiscal year mark1',
      fyMark2Dis: 'Please enter fiscal year mark2',
      fyMark3Dis: 'Please enter fiscal year mark3',
      fyAlcalcdateDis: 'Select annual leave calculation deadline',
      fyAlclosedateDis: 'Select leave on leave for annual leave',
      fySdateDis: 'Select Fiscal Year Start Date',
      fyEdateDis: 'Select Fiscal Year End Date',
      commentDis: 'Please enter comment...',
    },
    PlatFyperiod: {
      title: 'Information during the fiscal year',
      selectTitle: 'Select period',
      fypdYear: 'Fiscal Year',
      fypdPeriod: 'Period',
      fypdMark1: 'Period Mark1',
      fypdMark2: 'Period Mark2',
      fypdMark3: 'Period Mark3',
      fypdStartdate: 'Start Date',
      fypdEnddate: 'End Date',
      comment: 'Comment',
      fypdSearch: 'Popup box during the fiscal year',
      fypdPeriodDis: 'Please enter period',
      fypdMark1Dis: 'Please enter period mark1',
      fypdMark2Dis: 'Please enter period mark2',
      fypdMark3Dis: 'Please enter period mark3',
      fypdStartdateDis: 'Select start date',
      fypdEnddateDis: 'Select end date',
      commentDis: 'Please enter comment...',
    },
    platEmpno: {
      title: 'Staff number management',
      empno: 'Employee Number',
      companys: 'Company Scope',
      validName: 'Is valid ?',
      sEmpNo: 'Starting Employee Number',
      eEmpNo: 'Ending Employee Number',
      comment: 'Comment',
      empnoDis: 'Please enter employee number',
      companysDis: 'Please enter company scope',
      validNameDis: 'Please select whether it is valid',
      sEmpNoDis: 'Please enter the starting employee number',
      eEmpNoDis: 'Please enter ending employee number',
      commentDis: 'Please enter comment...',
    },
    platPostno: {
      title: 'Post Number Management',
      postno: 'Post Number',
      companys: 'Company Scope',
      validName: 'Is valid ?',
      sPostNo: 'Starting post number',
      ePostNo: 'End position number',
      comment: 'Comment',
      postnoDis: 'Please enter post number',
      companysDis: 'Please enter company scope',
      validNameDis: 'Please select whether it is valid',
      sPostNoDis: 'Please enter starting post number',
      ePostNoDis: 'Please enter ending post number',
      commentDis: 'Please enter comment...',
    },
    platBenefitarea: {
      platBenefitarea: 'Social security area management',
      bfareaCode: 'area code',
      bfareaCodeDis: 'Please enter the area code',
      bfareaCname: 'area name Chinese',
      bfareaCnameDis: 'Please enter the area name Chinese',
      bfareaEname: 'area name English',
      bfareaEnameDis: 'Please enter the area name in English',
      bfareaType: 'Zone division',
      bfareaTypeDis: 'Select area division',
      comment: 'Comment',
      commentDis: 'Please enter a comment',
      distCity: 'Assign the city',
      distCompany: 'Assign the company',
      selectCity: 'can choose city',
      selectedCity: 'Selected city',
      cityName: 'city name',
      companyName: 'company name',
      selectCompany: 'can choose Company',
      selectedCompany: 'Selected Company',
      bfareaName: 'Please enter the area / English...',
      dist: 'allocation',
    },
    autotasklog: {
      autotasklog: 'automatic task log',
      atlogAtskidNameIns: 'Please select automatic task...',
      sdateIns: 'Select start date',
      edateIns: 'Select end date',
      atlogRuntypeIns: 'Please enter the execution type...',
      atlogStatusIns: 'Please select state...',
      atskName: 'automatic task name',
      atskTypeName: 'automatic task type',
      atlogRuntime: 'execution time',
      atlogRuntype: 'execution type',
      atlogAtskidName: 'automatic task',
      atlogStatusName: 'state',
      atlogError: 'error message',
      comment: 'Comment',
    },
    syswx: {
      syswx: 'WeChat template management',
      syswxNo: 'template number',
      syswxTypeDis: 'message type',
      syswxTitle: 'title',
      syswxContent: 'content',
      syswxTo: 'Recipient',
      syswxSendcondition: 'send condition',
      syswxLink: 'card link',
      syswxIsvalid: 'whether valid',
      syswxInvreason: 'failure reason',
      syswxComment: 'Comment',
      syswxNoIns: 'Please enter the template number',
      syswxTypeDisIns: 'Please select message type',
      syswxTitleIns: 'Please enter a title',
      syswxContentIns: 'Please enter the content',
      syswxToIns: 'Please enter the recipient',
      syswxSendconditionIns: 'Please enter the sending condition',
      syswxLinkIns: 'Please enter a card link',
      syswxIsvalidIns: 'Please select whether it is valid',
      syswxInvreasonIns: 'Please enter the reason for failure',
      syswxCommentIns: 'Please enter a comment',
      syswxInfo: 'WeChat template information',
      syswxvarInfo: 'WeChat template variable',
      syswxNoIns2: 'Only support for number format template number',
      syswxvarMark: 'variable identifier',
      syswxvarName: 'variable name',
      syswxvarValdesc: 'value description',
      syswxvarComment: 'Comment',
      syswxvarMarkIns: 'Please enter the variable identifier',
      syswxvarNameIns: 'Please enter a variable name',
      syswxvarValdescIns: 'Please enter a value description',
      syswxvarCommentIns: 'Please enter a comment',
    },
    autoTask: {
      autoTask: 'Automatic task configuration',
      autoTaskInfo: 'Automatic task configuration content',
      atskNo: 'Automatic task number',
      atskName: 'Automatic task name',
      atskIsvalid: 'Isvalid?',
      atskJobid: 'Task JOBID',
      atskClass: 'Task execution class name',
      atskType: 'task type',
      atskPrommode: 'Reminder mode',
      atskTemptable: 'Automatically remind temporary table',
      atskAdvancedays: 'early days',
      atskDurationdays: 'last days',
      atskFrequency: 'execution frequency',
      atskTime: 'execution time',
      atskRunmonth: 'Please select month...',
      atskRunday: 'Please select day...',
      atskRunhour: 'Please select...',
      atskRunminute: 'Please select points...',
      atskRunweek: 'Please select week...',
      atskIntervalminutes: 'interval minutes',
      atskSendamount: 'interval send quantity',
      atskRunsdate: 'execution start time',
      atskRunedate: 'execution end time',
      atskLasttime: 'last execution time',
      atskMailtempName: 'mail template',
      atskSurveyName: 'Investigation definition',
      atskSmsName: 'SMS template',
      atskWxName: 'WeChat template',
      atskPromkey: 'Remind data primary key identifier',
      atskFlowdatakey: 'process data primary key identifier',
      atskComment: 'Comment',
      atskNoIns: 'Please enter the automatic task number',
      atskNameIns: 'Please enter the automatic task name',
      atskJobidIns: 'Please enter the task JOBID',
      atskClassIns: 'Please enter the task execution class name',
      atskMailtempNameIns: 'Please select mail template',
      atskSurveyNameIns: 'Please select survey definition',
      atskSmsNameIns: 'Please select SMS template',
      atskWxNameIns: 'Please select WeChat template',
      atskPromkeyIns: 'Please enter the reminder data primary key identifier',
      atskFlowdatakeyIns: 'Please enter the process data primary key identifier',
      atskCommentIns: 'Please enter a comment',
      atskFrequencyIns: 'Please set the execution frequency',
      atskPrommodeIns: 'Select at least one layout method',
      plat_atsk_temp01: 'Automatic task temporary table 01',
      plat_atsk_temp02: 'Automatic task temporary table 02',
      plat_atsk_temp03: 'Automatic task temporary table 03',
      plat_atsk_temp04: 'Automatic task temporary table 04',
      plat_atsk_temp05: 'Automatic task temporary table 05',
      plat_atsk_temp06: 'Automatic task temporary table 06',
      plat_atsk_temp07: 'Automatic task temporary table 07',
      plat_atsk_temp08: 'Automatic task temporary table 08',
      plat_atsk_temp09: 'Automatic task temporary table 09',
      plat_atsk_temp10: 'Automatic task temporary table 10',
      platSuvCode: 'number',
      platSuvTitle: 'Title',
      sysmailName: 'template name',
      sysmailObject: 'theme',
      syssmsNo: 'template number',
      syssmsTitle: 'title',
      month: 'month',
      day: 'day',
      hour: 'hour',
      minut: 'minute',
      atskdfClmmark: 'data item identifier',
      atskdfClmcn: 'data item identification Chinese',
      atskdfClmen: 'data item identification English',
      atskdfMailvarName: 'mail variable',
      atskdfSurveyvarName: 'investigation variable',
      atskdfSmsvarName: 'SMS variable',
      atskdfWxvarName: 'WeChat variable',
      atskdfGetvalbyclmName: 'reverse check definition',
      atskdfComment: 'Comment',
      platSvaCname: 'variable name',
      platSvaName: 'variable identifier',
      sysmlvarName: 'variable name',
      sysmlvarMark: 'variable ID',
      syssmsvarName: 'variable name',
      syssmsvarMark: 'variable identifier',
      syswxvarName: 'variable name',
      syswxvarMark: 'variable identifier',
      sourceName: 'service name',
      vffPropname: 'property name',
      vffProperty: 'Associated property',
      atskdfClmmarkIns: 'Please enter the data item ID',
      atskdfClmcnIns: 'Please enter the data item identification Chinese',
      atskdfClmenIns: 'Please enter the data item identification English',
      atskdfMailvarNameIns: 'Please enter the mail variable',
      atskdfSurveyvarNameIns: 'Please enter the survey variable',
      atskdfSmsvarNameIns: 'Please enter SMS variable',
      atskdfWxvarNameIns: 'Please enter WeChat variable',
      atskdfGetvalbyclmNameIns: 'Please enter the reverse check definition',
      atskdfCommentIns: 'Please enter a comment',
    },
    platFlowVar: {
      platFlowVar: 'Business Variable Management',
      flvarMarkIns2: 'Please enter a variable ID or name',
      flvarFormtype: 'form type',
      flvarFlow: 'form',
      flvarMark: 'variable identification',
      flvarName: 'variable name',
      flvarValresource: 'Variable value source',
      flvarSysval: 'system variable',
      flvarFiled: 'process field',
      flvarGetvalbyfiled: 'reverse check service',
      flvarRtndatafmt: 'return data type',
      flvarDatefmt: 'date format',
      flvarIscondition: 'whether conditional setting',
      Comment: 'Comment',
      flvarFormtypeIns: 'Please enter form type',
      flvarFlowIns: 'Please enter the form',
      flvarMarkIns: 'Please enter the variable ID',
      flvarNameIns: 'Please enter a variable name',
      flvarValresourceIns: 'Please enter the source of the variable value',
      flvarSysvalIns: 'Please enter system variable',
      flvarFiledIns: 'Please enter the process field',
      flvarGetvalbyfiledIns: 'Please enter the reverse check service',
      flvarRtndatafmtIns: 'Please enter the return data type',
      flvarDatefmtIns: 'Please enter the date format',
      flvarIsconditionIns: 'Please enter the condition setting',
      commentIns: 'Please enter a comment',
      sformName: 'form name',
      sformTbname: 'physical table name',
      sffPhyfield: 'physical field name',
      sffFieldNameCnDis: 'field name',
      sourceName: 'service name',
      vffPropname: 'property name',
      vffProperty: 'Associated property',
      flvarField: 'Variable field',
    },
    platFlowcontacts: {
      platFlowcontacts: 'Business Contact Management',
      flcontFormtype: 'form type',
      flcontFlowName: 'form',
      flcontMark: 'contact ID',
      flcontName: 'contact name',
      flcontValueName: 'contact value variable',
      comment: 'Comment',
      flcontFormtypeIns: 'Please select form type',
      flcontFlowNameIns: 'Please select form',
      flcontMarkIns: 'Please enter a contact ID',
      flcontNameIns: 'Please enter a contact name',
      flcontValueNameIns: 'Please select a contact value variable',
      commentIns: 'Please enter a comment',
      sformName: 'form name',
      sformTbname: 'physical table name',
      flvarName: 'process variable name',
      flvarMark: 'process variable ID',
      flcontMarkIns2: 'Please enter a logo or name',
    },
  },
}
