export default {
  'zh-CN': {
    fileClass: {
      title: '档案分类管理',
      claNo: '编码',
      claName: '名称',
      claPid: '上级分类名称',
      claYesno: '是否必须',
      yes: '是',
      no: '否',
      claNote: '备注',
      claNoDis: '请输入档案分类编码',
      claNameDis: '请输入档案分类名称',
      claPidDis: '请选择上级分类名称',
      claYesnoDis: '请选择是否必须',
      claNoteDis: '请输入备注',
      // searchTitle
      searchPid: '选择上级',
      searchClaName: '选择档案类别',
    },
    archivesRoom: {
      title: '档案室信息管理',
      cenNo: '档案室编号',
      cenName: '档案室名称',
      cenAddress: '档案室地址',
      cenAdmin: '管理员',
      cenAdminTel: '管理员联系电话',
      cenAdminMail: '管理员邮箱',
      cenNote: '备注',
      cenNoDis: '请输入档案室编号',
      cenNameDis: '请输入档案室名称',
      cenAddressDis: '请输入档案室地址',
      cenAdminDis: '请选择管理员',
      cenAdminTelDis: '请输入管理员联系电话',
      cenAdminMailDis: '请输入管理员邮箱',
      cenNoteDis: '请输入备注',
    },
    fileCabinet: {
      title: '档案位信息管理',
      cabCenid: '档案室',
      cabNo: '档案位编号',
      cabName: '档案位名称',
      cabNote: '备注',
      cabCenidDis: '请选择档案室',
      cabNoDis: '请输入档案位编号',
      cabNameDis: '请输入档案位名称',
      cabNoteDis: '请输入备注',
      // searchTable
      searchTitle: '档案室',
    },
    fileQuery: {
      title: '档案查询管理',
      fileDetail: '档案详情',
      entEmpid: '员工',
      entClaid: '档案分类',
      entNo: '档案编号',
      entName: '档案名称',
      entTime: '归档时间',
      entCenid: '档案室',
      entCabid: '档案位',
      entFile: '附件',
      entNote: '备注',
      entEmpidDis: '请选择员工',
      entClaidDis: '请选择档案分类',
      entNoDis: '请输入档案编号',
      entNameDis: '请输入档案名称',
      entTimeDis: '请选择归档时间',
      entCenidDis: '请选择档案室',
      entCabidDis: '请选择档案位',
      entFileDis: '请上传附件',
      entNoteDis: '请输入备注',
      // searchTable
      searchTitle: '选择上级档案',
      claNameDis: '请输入上级档案名称',
      searchTitle2: '选择员工',
      searchText: '请输入员工名称',
      empkiWorkno: '员工工号',
      empName: '员工姓名',
      empcompPost: '岗位',
      // borrowingInof
      borBorrower: '查阅人',
      borBortime: '查阅时间',
      borList: '查阅档案列表',
      borReason: '查阅原因',
      borBorrowerDis: '请选择查阅人',
      borBortimeDis: '请选择查阅时间',
      borListDis: '请输入查阅档案列表',
      borReasonDis: '请输入查阅原因',
      // borSearchText
      borSearchText: '请输入用户姓名',
      borSearchTitle: '选择用户',
      name: '姓名',
      idNo: '证件号码',
      // remind ,
      startLendtime: '开始时间不能大于结束时间',
    },
  },
  'en-US': {
    fileClass: {
      title: 'File classification management',
      claNo: 'Code',
      claName: 'ClassFileName',
      claPid: 'Superior ClassFile',
      claYesno: 'Is Must?',
      yes: 'Yes',
      no: 'No',
      claNote: 'Comment',
      claNoDis: 'Please enter the file classification code',
      claNameDis: 'Please select the parent category name',
      claPidDis: 'Please select the parent category name',
      claYesnoDis: 'Please choose whether you must',
      claNoteDis: 'Please enter comment',
      // searchTitle
      searchPid: 'Select the superior',
      searchClaName: 'Select File Type',
    },
    archivesRoom: {
      title: 'Archives information management',
      cenNo: 'Registry number',
      cenName: 'Registry name',
      cenAddress: 'Registry address',
      cenAdmin: 'The administrator',
      cenAdminTel: 'Administrator contact number',
      cenAdminMail: 'Administrator mailbox',
      cenNote: 'note',
      cenNoDis: 'Please enter the registry number',
      cenNameDis: 'Please enter the name of the archive room',
      cenAddressDis: 'Please enter the address of the archive room',
      cenAdminDis: 'Please select administrator',
      cenAdminTelDis: 'Please enter administrator contact number',
      cenAdminMailDis: 'Please enter administrator mailbox',
      cenNoteDis: 'Please enter remarks',
    },
    fileCabinet: {
      title: 'File bit information management',
      cabCenid: 'Archives',
      cabNo: 'Filebit number',
      cabName: 'File name',
      cabNote: 'Comment',
      cabCenidDis: 'Please select the archive room',
      cabNoDis: 'Please enter the file number',
      cabNameDis: 'Please enter the file bit name',
      cabNoteDis: 'Please enter comment',
      // searchTable
      searchTitle: 'Archives',
    },
    fileQuery: {
      title: 'File query management',
      fileDetail: 'File for details',
      entEmpid: 'Employee',
      entClaid: 'Classification',
      entNo: 'FileNumber',
      entName: 'FileName',
      entTime: 'ArchiveTime',
      entCenid: 'Archives',
      entCabid: 'FileCabinet',
      entFile: 'Attachment',
      entNote: 'Comment',
      entEmpidDis: 'Please select employees',
      entClaidDis: 'Please select file category',
      entNoDis: 'Please enter the file number',
      entNameDis: 'Please enter the file name',
      entTimeDis: 'Please select the filing time',
      entCenidDis: 'Please select the archive room',
      entCabidDis: 'Please select the file bit',
      entFileDis: 'Please upload the attachment.',
      entNoteDis: 'Please enter remarks',
      // searchTable
      searchTitle: 'Select superior files',
      claNameDis: 'Please enter the name of the superior file',
      searchTitle2: 'Select Employee',
      searchText: 'Please enter emplyee name',
      empkiWorkno: 'Employee Number',
      empName: 'Employee Name',
      empcompPost: 'Post',
      // borwerinfo
      borBorrower: 'Borrower',
      borBortime: 'Bortime',
      borList: 'FileList',
      borReason: 'BorrowReason',
      borBorrowerDis: 'Please select the person to consult',
      borBortimeDis: 'Please select the time to check',
      borListDis: 'Please enter the view file list',
      borReasonDis: 'Please enter the reason',
      // borSearchText
      borSearchText: 'Please enter user name',
      borSearchTitle: 'Select the user',
      name: 'Name',
      idNo: 'Id.No',
      // remind ,
      startLendtime: 'The start time cannot be longer than the end time',
    }
  },
}
