export default {
  'zh-CN': {
    cmutCorpora: {
      corpora: '私有语料库',
      titleIns: '请输入标题...',
      valid: '生效',
      invalid: '失效',
      cmutCorpQtype: '问题类型',
      cmutCorpOrder: '序号',
      cmutCorpTitle: '问题',
      cmutCorpContent: '答案(PC端)',
      cmutCorpWxcontent: '答案(微信端)',
      cmutCorpStateDis: '状态',
      succes: '操作完成',
      cmutCorpOrderIns: '请输入序号',
      cmutCorpStateIns: '请选择状态',
      cmutCorpQtypeIns: '请输入问题类型',
      cmutCorpTitleIns: '请输入问题',
      cmutCorpContentIns: '请输入答案(PC端)...',
      cmutCorpWxcontentIns: '请输入答案(微信端)...',
      comment: '备注',
      commentIns: '请输入备注...',
    },
    cmutTeam: {
      title: '咨询团队管理',
      cmstTeamcode: '团队标识',
      cmstTeamname: '团队名称',
      cmstWddistribute: '工单分配方式',
      cmstComment: '备注',

      p_cmstTeamcode: '请输入团队标识',
      p_cmstTeamname: '请输入团队名称',
      p_cmstComment: '备注',
      p_searchbox: '输入服务标识或服务名称',

      rule_cmstTeamcode: '团队标识不能为空',
      rule_cmstTeamname: '团队名称不能为空',
      rule_cmstWddistribute: '工单方式不能为空',
      title1: '工单团队信息',
      title2: '工单团队成员',
    },
    TeamMem: {
      cmstmStid: '支持团队',
      cmstmCode: '成员编号',
      cmstmUserid: '成员',
      mobileNo: '成员电话',
      loginName: '成员登录名',
      email: '成员邮箱',
      cmstmDistribute: '是否有分配工单权限',
      cmstmIsvalid: '是否有效',
      comment: '备注',

      p_cmstmStid: '请选择支持团队',
      p_cmstmCode: '请输入成员编号',
      p_cmstmUserid: '请选择成员信息',
      p_comment: '请输入备注',

      rule_cmstmCode: '成员编号不能为空',
      rule_cmstmUserid: '成员不能为空',
    },
    searchBusiUser: {
      title: '用户信息',
      searchText: '请输入用户姓名',
      userName: '姓名',
      mobileNo: '手机号',
      email: '邮箱',
      loginName: '登录名',
    },
    teamMapping: {
      title: '工单分配管理',
      cmtmtpWdtype: '工单类型',
      cmtmtpTeam: '分配团队',
      cmtmtpTeammember: '分配成员',
      cmtmtpComment: '备注',


      p_cmtmtpWdtypeName: '请选择工单类型',
      p_cmtmtpTeam: '请选择团队',
      p_cmtmtpTeammember: '请选择成员',
      p_cmtmtpComment: '请输入备注',

      rule_cmtmtpWdtype: '工单类型不能为空',
      rule_cmtmtpTeam: '团队不能为空',
      reminder: '请先选择分配团队!',
    },
    searchKnowType: {
      searchTitle: '选择工单类型',
      cmutKntypeCode: '类型编码',
      cmutKntypeName: '类型名称',
    },
    searchKnowTeam: {
      searchTitle1: '选择团队',
      searchText1: '请输入团队名称',
      cmstTeamcode: '团队标识',
      cmstTeamname: '团队名称',
    },
    searchTeamMember: {
      searchTitle2: '选择团队成员',
      searchText2: '请输入成员编号',
      cmstmCode: '成员编号',
      cmstmUseridDis: '成员名称',
    },
  },
  'en-US': {
    cmutCorpora: {
      corpora: 'Private Corpus',
      titleIns: 'Please enter a title...',
      valid: 'valid',
      invalid: 'invalid',
      cmutCorpQtype: 'Type of problem',
      cmutCorpOrder: 'serial number',
      cmutCorpTitle: 'question',
      cmutCorpContent: 'Answer(PC)',
      cmutCorpWxcontent: 'Answer(WX)',
      cmutCorpStateDis: 'state',
      succes: 'Operation completed',
      cmutCorpOrderIns: 'Please enter the serial number',
      cmutCorpStateIns: 'Please select state',
      cmutCorpTitleIns: 'Please enter a question',
      cmutCorpQtypeIns: 'Please enter the question type',
      cmutCorpContentIns: 'Please enter Answer(PC)...',
      cmutCorpWxcontentIns: 'Please enter Answer(WX)...',
      comment: 'Comment',
      commentIns: 'Please enter a comment...',
    },
    cmutTeam: {
      title: 'Team Management',
      cmstTeamcode: 'Team Mark',
      cmstTeamname: 'Team Name',
      cmstWddistribute: 'Workorder distribution',
      cmstComment: 'Comment',

      p_cmstTeamcode: 'Please input team mark',
      p_cmstTeamname: 'Please input team name',
      p_cmstComment: 'Please input comment',
      p_searchbox: 'Please input mark or name',

      rule_cmstTeamcode: 'Team Mark must be not null',
      rule_cmstTeamname: 'Team Name must be not null',
      rule_cmstWddistribute: 'Workorder distribution must not be null',

      title1: 'Team Info',
      title2: 'Team Mem',

    },
    TeamMem: {
      cmstmStid: 'Team',
      cmstmCode: 'Mem Code',
      cmstmUserid: 'Member',
      mobileNo: 'Telephone',
      loginName: 'Login Name',
      email: 'Email',
      cmstmDistribute: 'Is Distribute',
      cmstmIsvalid: 'Is Valid',
      comment: 'Comment',

      p_cmstmStid: 'Please select team',
      p_cmstmCode: 'Please input code',
      p_cmstmUserid: 'Please select mem',
      p_comment: 'Please input comment',

      rule_cmstmCode: 'Mem Code must  be not null',
      rule_cmstmUserid: 'Members must  be not null',
    },
    searchBusiUser: {
      title: 'User Info',
      searchText: 'Please input user name',
      userName: 'Name',
      mobileNo: 'Mobile No.',
      email: 'Email',
      loginName: 'Login Name',
    },
    teamMapping: {
      title: 'Workorder Distribute',
      cmtmtpWdtype: 'Workorder Type',
      cmtmtpTeam: 'Team',
      cmtmtpTeammember: 'Member',
      cmtmtpComment: 'Comment',


      p_cmtmtpWdtypeName: 'Please select workoder type',
      p_cmtmtpTeam: 'Please select team',
      p_cmtmtpTeammember: 'Please select team mem',
      p_cmtmtpComment: 'Please input comment',

      rule_cmtmtpWdtype: 'workoder type must be not null',
      rule_cmtmtpTeam: 'team must be not null',
      reminder: 'Please enter the WeChat link and select the assigned team first!',
    },
    searchKnowType: {
      searchTitle: 'Workorder Type',
      cmutKntypeCode: 'Code',
      cmutKntypeName: 'Name',
    },
    searchKnowTeam: {
      searchTitle1: 'Team List',
      searchText1: 'Please input team Name',
      cmstTeamcode: 'Code',
      cmstTeamname: 'Name',
    },
    searchTeamMember: {
      searchTitle2: 'Team Mem',
      searchText2: 'Please input mem code',
      cmstmCode: 'Code',
      cmstmUseridDis: 'Name',
    },
  },
}
