export default {
  'zh-CN': {
    ansrptEmpSihf: {
      title: '员工社保信息',
      titleHosf: '员工公积金信息',
      empGid: '唯一标识号',
      empkiWorkno: '员工工号',
      empCname: '员工中文名',
      empbntEmpid: '员工姓名',
      empbntHirecompany: '雇佣公司',
      empbntBenefitlocation: '社保缴纳地',
      empbntBenefitpolicy: '社保政策',
      empbntBenefittype: '社保开户类别',
      empbntSdate: '生效日期',
      empbntEdate: '失效日期',
      empbntComment: '备注',
      basechititle: '员工社保险种',
      basechiHosftitle: '员工公积金险种',
    },
    ansrptSihfInsurance: {
      empinsEmpid: '员工姓名',
      empinsHirecompany: '雇佣公司',
      empinsType: '险种类别',
      empinsInsurance: '险种',
      empinsBaseamt: '基数',
      empinsCompratio: '公司缴纳比例(%)',
      empinsCompamt: '公司缴纳金额',
      empinsPersratio: '个人缴纳比例(%)',
      empinsPersamt: '个人缴纳金额',
      empinsSdate: '生效日期',
      empinsEdate: '失效日期',
      empinsComment: '备注',
    },
    ansrptHosfSihf: {
      empbntBenefitlocation: '公积金缴纳地',
      empbntBenefitlocationDis: '请选择社保缴纳地',
      empbntBenefitlocationCity: '请选择公积金缴纳地',
      empbntBenefitpolicy: '公积金政策',
      empbntBenefittype: '公积金开户类别',
    },
    functionStatistic: {
    	title: '访问功能统计',
    	statusF: '请选择状态',
    	userInfo: '请选择用户',
    	query: '查询',
    	statistics: '前十统计',
    	functionNode: '功能节点',
    	userNode: '用户节点',
    	visits: '访问次数',
    	times: '次',
    },
  },
  'en-US': {
    ansrptEmpSihf: {
      title: 'Staff social security information',
      titleHosf: 'Employee accumulation fund information',
      empGid: 'Unique identification number',
      empkiWorkno: 'Employee number',
      empCname: 'Employee Chinese name',
      empbntEmpid: 'Employee name',
      empbntHirecompany: 'Employment Company',
      empbntBenefitlocation: 'Social security payment',
      empbntBenefitpolicy: 'Social security policy',
      empbntBenefittype: 'Social security opening category',
      empbntSdate: 'effective date',
      empbntEdate: 'Expiration date',
      empbntComment: 'comments',
      basechititle: 'Insurance for social security of employees',
      basechiHosftitle: 'Insurance of employee accumulation fund',
    },
    ansrptSihfInsurance: {
      empinsEmpid: 'Employee name',
      empinsHirecompany: 'Employment Company',
      empinsType: 'Category of dangerous species',
      empinsInsurance: 'Type of insurance',
      empinsBaseamt: 'base',
      empinsCompratio: 'Proportion (%) of the company',
      empinsCompamt: 'Amount of payment by the company',
      empinsPersratio: 'Personal payment ratio (%)',
      empinsPersamt: 'Individual payment',
      empinsSdate: 'effective date',
      empinsEdate: 'Expiration date',
      empinsComment: 'comments',
    },
    ansrptHosfSihf: {
      empbntBenefitlocation: 'Provident fund',
      empbntBenefitpolicy: 'Provident fund policy',
      empbntBenefittype: 'Fund opening category',
    },
    functionStatistic: {
    	title: 'user access function statistics',
    	statusF: 'please select a status',
    	userInfo: 'please select a user',
    	query: 'query',
    	statistics: 'top ten statistics',
    	functionNode: 'function node',
    	userNode: 'user node',
    	visits: 'visits',
    	times: 'times'
    },
  },
}
