export default {
  'zh-CN': {
    baseCountry: {
      title: '国家信息管理',
      countryCnameDis: '请输入国家中文',
      countryEnameDis: '请输入国家英文',
      countryCode1Dis: '请输入编码1',
      countryCode2Dis: '请输入编码2',
      countryCode3Dis: '请输入编码3',
      commentDis: '请输入备注',
      countryCname: '国家中文',
      countryEname: '国家英文',
      countryCode1: '编码1',
      countryCode2: '编码2',
      countryCode3: '编码3',
      comment: '备注',
    },
    baseCity: {
      title: '省份城市管理',
      cityNameDis: '请输入城市名称',
      cityCode1Dis: '请输入编码1',
      cityCode2Dis: '请输入编码2',
      cityCode3Dis: '请输入编码3',
      cityTypeNameDis: '请选择城市类型',
      cityPnameDis: '请选择所属上级',
      cityIsvalidNameDis: '若不选择,则默认为启用',
      cityIssbNameDis: '若不选择,则默认为开通',
      cityIshfNameDis: '若不选择,则默认为开通',
      cityIstaxNameDis: '若不选择,则默认为开通',
      commentDis: '请输入备注',
      cityName: '城市名称 ',
      cityCode1: '编码1',
      cityCode2: '编码2',
      cityCode3: '编码3',
      cityTypeName: '城市类型',
      cityPname: '所属上级',
      cityIsvalidName: '是否启用',
      cityIssbName: '是否社保缴纳',
      cityIshfName: '是否公积金缴纳',
      cityIstaxName: '是否个税申报',
      comment: '备注',
      allCountry: '全国省市',
      areaLists: '选择城市',
    },
    baseTaxrate: {
      title: '税率信息管理',
      taxCodeDis: '请输入税率编码',
      taxYearDis: '请输入税率年份',
      taxYear: '税率年份',
      taxSdateDis: '选择生效日期',
      taxEdateDis: '选择失效日期',
      taxMinDis: '请输入下限',
      taxMaxDis: '请输入上限',
      taxTaxrateDis: '请输入税率',
      taxQkdeuctionDis: '请输入速算扣除数',
      taxAmountminDis: '请输入缴税金额下限',
      taxAmountmaxDis: '请输入缴税金额上限',
      taxPosttaxminDis: '请输入税后金额下限',
      taxPosttaxmaxDis: '请输入税后金额上限',
      commentDis: '请输入备注',
      taxCode: '税率编码',
      taxMin: '下限',
      taxMax: '上限',
      taxTaxrate: '税率',
      taxQkdeuction: '速算扣除数',
      taxAmountmin: '缴税金额下限',
      taxAmountmax: '缴税金额上限',
      taxPosttaxmin: '税后金额下限',
      taxPosttaxmax: '税后金额上限',
      taxSdate: '生效日期',
      taxEdate: '失效日期',
      comment: '备注',
    },
    baseCurrency: {
      title: '币种信息管理',
      currCurrencyDis: '请输入币种',
      currCode1Dis: '请输入编码1',
      currCode2Dis: '请输入编码2',
      currCode3Dis: '请输入编码3',
      commentDis: '请输入备注',
      currCurrency: '币种',
      currCode1: '编码1',
      currCode2: '编码2',
      currCode3: '编码3',
      comment: '备注',
    },
    baseExrate: {
      title: '汇率信息管理',
      exrLocalcurrencyNameDis: '选择本位币',
      exrCurrencyNameDis: '选择外币',
      exrDateDis: '选择日期',
      exrExrateDis: '请输入汇率',
      commentDis: '请输入备注...',
      exrCurrencyName: '外币',
      exrLocalcurrencyName: '本位币',
      exrDate: '日期',
      exrExrate: '汇率',
      comment: '备注',
    },
    baseTaxexemption: {
      title: '个税免征额管理 ',
      taxexeEmptypeNameDis: '选择员工类型',
      taxexeThresholdDis: '请输入起征点',
      taxexeSdateDis: '选择生效日期',
      taxexeEdateDis: '选择失效日期',
      commentDis: '请输入备注',
      taxexeEmptypeName: '员工类型',
      taxexeThreshold: '起征点',
      taxexeSdate: '生效日期',
      taxexeEdate: '失效日期',
      comment: '备注',
    },
    baseBankinfo: {
      title: '银行信息管理 ',
      bankCodeDis: '请输入银行代码',
      banknameDis: '请输入银行中文/英文名称',
      bankSwiftcodeDis: '请输入swiftcode/银行国际代码',
      bankCityNameDis: '请选择所属城市',
      bankCnameDis: '请输入银行名称',
      bankEnameDis: '请输入英文名称',
      bankCaddDis: '请输入银行地址',
      bankEaddDis: '请输入英文地址',
      commentDis: '请输入备注',
      bankCode: '银行代码',
      bankCityName: '所属城市',
      bankCname: '银行名称',
      bankEname: '英文名称',
      bankCadd: '银行地址',
      bankEadd: '英文地址',
      bankSwiftcode: '银行国际代码',
      comment: '备注',
    },
    baseLevareason: {
      title: '离职原因管理',
      levaCodeDis: '请输入编码',
      levaReatypeNameDis: '选择分类',
      levaCnameDis: '请输入离职原因',
      levaEnameDis: '请输入离职原因英文',
      commentDis: '请输入备注',
      levaCode: '编码',
      levaReatypeName: '离职分类',
      levaCname: '离职原因',
      levaEname: '离职原因英文',
      levaname: '请输入离职原因中文/英文',
      comment: '备注',
    },
    baseLevadfamount: {
      title: '离职补偿金管理',
      selCity: '请选择所属城市',
      levdfDfamountDis: '请输入免税金额',
      levdfSdateDis: '选择生效日期',
      levdfEdateDis: '选择失效日期',
      commentDis: '请输入备注',
      levdfCityName: '所属城市',
      levdfDfamount: '免税金额',
      levdfSdate: '生效日期',
      levdfEdate: '失效日期',
      comment: '备注',
    },
    baseNereason: {
      title: '未入职原因管理',
      nerCodeDis: '请输入编码',
      sscTypeNameDis: '请选择险种类别',
      nerEnameDis: '请输入原因英文',
      nerCnameDis: '请输入原因',
      commentDis: '请输入备注',
      nerCode: '编码',
      sscTypeName: '险种类别',
      nerEname: '原因英文',
      nerCname: '原因',
      comment: '备注',
    },
    baseSscoverage: {
      title: '社保险种管理',
      sscCodeDis: '请输入编码',
      sscTypeNameDis: '请输入险种类型',
      sscCnameDis: '请输入名称',
      sscEnameDis: '请输入英文',
      commentDis: '请输入备注',
      sscCode: '编码',
      sscTypeName: '险种类型',
      sscCname: '险种名称',
      sscEname: '险种英文名称',
      comment: '备注',
    },
    baseMapping: {
      baseMapping: 'Mapping关系维护',
      mapTypeIns: '请选择mapping类型',
      mapTypeDis: 'Mapping类型',
      mapCode1Ins: '请输入Mapping Code1',
      mapCodedesc1Ins: '请输入desc1...',
      mapCode2Ins: '请输入Mapping Code2',
      mapCodedesc2Ins: '请输入desc2...',
      comment: '备注',
      commentIns: '请输入备注',
    },
    autocode: {
      autocodeManage: '自动编码配置',
      autoFlagIns: '请输入自动编码标识...',
      autoNameIns: '请输入自动编码名称...',
      autoFlag: '自动编码标识',
      autoName: '自动编码名称',
      autoPrefix: '前缀',
      autoTimeformatName: '时间格式',
      autoWater: '流水位数',
      autoValidityName: '是否有效',
      autoCode: '当前编码',
      autoPrefixIns: '请输入前缀...',
      autoTimeformatNameIns: '选择时间格式...',
      autoWaterIns: '请输入流水位数...',
      autoValidityNameIns: '选择是否有效...',
      autoCodeIns: '请输入当前编码...',
      comment: '备注',
      commentIns: '请输入备注...',
    },
    wxMsgRecord: {
      wxMsgRecord: '微信消息日志',
      sdateIns: '请选择开始时间...',
      edateIns: '请选择结束时间...',
      wxmsgSendeeIns: '请输入接收人...',
      wxmsgTime: '发送时间',
      wxmsgBustype: '业务类型',
      wxmsgMsgtypeDis: '消息类型',
      wxmsgDataid: '数据ID',
      wxmsgSendee: '接收人',
      wxmsgContent: '消息内容',
      comment: '备注',
      wxmsgDatasource: '数据来源',
      wxmsgTitle: '消息标题',
      wxmsgUrl: '消息链接',
    },
    smsrecord: {
      smsrecord: '短信发送日志',
      smsPhonesIns: '请输入手机号...',
      sdateIns: '选择开始日期',
      edateIns: '选择结束日期',
      smsContentIns: '请输入短信内容...',
      smsStatusIns: '请输入状态...',
      smsPhones: '手机号码',
      smsTime: '发送时间',
      smsContent: '短信内容',
      smsError: '错误信息',
      smsDatasource: '数据来源',
      smsStatus: '状态',
      atlogError: '错误信息',
      comment: '备注',
      smsEtime: '结束时间',
    },
    emaillog: {
      emaillog: '邮件发送日志',
      mailObjectIns: '请输入主题...',
      sdateIns: '选择开始日期',
      edateIns: '选择结束日期',
      mailToIns: '请输入接收人...',
      mailCcIns: '请输入抄送人...',
      mailContentIns: '请输入邮件内容...',
      mailStatusIns: '请输入状态...',
      mailTime: '发送时间',
      mailObject: '主题',
      mailTo: '接收人',
      mailCc: '抄送人',
      mailStatus: '状态',
      comment: '备注',
      mailError: '错误信息',
    },
    baseHousinglease: {
      title: '租房专项扣除',
      leaseYear: '扣除年度',
      leaseAmout: '扣除金额',
      leaseCitysDis: '城市范围',
      leaseSdate: '生效日期',
      leaseEdate: '失效日期',
      comment: '备注',

      p_leaseYear: '请选择扣除年度',
      p_leaseAmout: '请选择扣除金额',
      p_leaseCitysDis: '请选择城市',
      p_leaseSdate: '请选择生效时间',
      p_leaseEdate: '请选择失效时间',
      p_comment: '请填写备注',

      r_leaseYear: '扣除年度不能为空',
      r_leaseAmout: '扣除金额不能为空',
      r_leaseCitysDis: '城市不能为空',
      r_leaseSdate: '生效时间不能为空',
    },
  },
  'en-US': {
    baseCountry: {
      title: 'Conntry Information Maintenance',
      countryCnameDis: 'Please enter country\'s chinese name',
      countryEnameDis: 'Please enter country\'s english name',
      countryCode1Dis: 'Please enter Code1',
      countryCode2Dis: 'Please enter Code2',
      countryCode3Dis: 'Please enter Code3',
      commentDis: 'Please enter Comment',
      countryCname: 'Country Chinese',
      countryEname: 'Country English',
      countryCode1: 'CountryCode1',
      countryCode2: 'CountryCode2',
      countryCode3: 'CountryCode3',
      comment: 'Comment',
    },
    baseCity: {
      title: 'Provincial City Management',
      cityNameDis: 'Please enter city name',
      cityCode1Dis: 'Please enter code1',
      cityCode2Dis: 'Please enter code2',
      cityCode3Dis: 'Please enter code3',
      cityTypeNameDis: 'Please select city type',
      cityPnameDis: 'Please select the parent',
      cityIsvalidNameDis: 'If not selected, it is enabled by default',
      cityIssbNameDis: 'If not selected, it is enabled by default',
      cityIshfNameDis: 'If not selected, it is enabled by default',
      cityIstaxNameDis: 'If not selected, it is enabled by default',
      commentDis: 'Please enter a note',
      cityName: 'City Name ',
      cityCode1: 'Code1',
      cityCode2: 'Code2',
      cityCode3: 'Code3',
      cityTypeName: 'City Type',
      cityPname: 'Affiliated superior',
      cityIsvalidName: 'Enable IS?',
      cityIssbName: 'Social IS?',
      cityIshfName: 'Provident IS?',
      cityIstaxName: 'Tax IS?',
      comment: 'Comment',
      allCountry: 'All provinces and cities',
      areaLists: 'Select city',
    },
    baseTaxrate: {
      title: 'Tax Rate Maintenance',
      taxCodeDis: 'Please enter tax rate code',
      taxYearDis: 'Please enter tax rate year',
      taxYear: 'tax rate year',
      taxSdateDis: 'Select starting date',
      taxEdateDis: 'Select ending date',
      taxMinDis: 'Please enter the lower limit ',
      taxMaxDis: 'Please enter the upper limit',
      taxTaxrateDis: 'please enter tax rate',
      taxQkdeuctionDis: 'Please enter a quick deduction',
      taxAmountminDis: 'Please enter the lower limit of tax payment',
      taxAmountmaxDis: 'Please enter the maximum amount of tax',
      taxPosttaxminDis: 'Please enter the minimum amount after tax',
      taxPosttaxmaxDis: 'Please enter the maximum amount after tax',
      commentDis: 'Please enter comment',
      taxCode: 'Tax Code',
      taxMin: 'Lower limit',
      taxMax: 'Upper limit',
      taxTaxrate: 'Tax Rate',
      taxQkdeuction: 'Quick Deduction',
      taxAmountmin: 'Tax Payment Last',
      taxAmountmax: 'Tax Payment Upper',
      taxPosttaxmin: 'Min Tax',
      taxPosttaxmax: 'Max Tax',
      taxSdate: 'Start Date',
      taxEdate: 'End Date',
      comment: 'Comment',
    },
    baseCurrency: {
      title: 'Currency Information Maintenance',
      currCurrencyDis: 'Please enter the currency',
      currCode1Dis: 'Please currency code1',
      currCode2Dis: 'Please currency code2',
      currCode3Dis: 'Please currency code3',
      commentDis: 'Please enter comment',
      currCurrency: 'Currency',
      currCode1: 'Code1',
      currCode2: 'Code2',
      currCode3: 'Code3',
      comment: 'Comment',
    },
    baseExrate: {
      title: 'Exchange Rate Information Maintenance',
      exrCurrencyNameDis: 'Select currency',
      exrLocalcurrencyNameDis: 'Select local Currency',
      exrDateDis: 'Select date',
      exrExrateDis: 'Please enter the exchange rate',
      commentDis: 'Please enter Comment...',
      exrCurrencyName: 'Currency',
      exrLocalcurrencyName: 'local Currency',
      exrDate: 'Date',
      exrExrate: 'Exchange Rate',
      comment: 'Comment',
    },
    baseTaxexemption: {
      title: 'Tax Exemption ',
      taxexeEmptypeNameDis: 'Select employee type',
      taxexeThresholdDis: 'Please enter the threshold',
      taxexeSdateDis: 'Select start date',
      taxexeEdateDis: 'Select end date',
      commentDis: 'Please enter Comment',
      taxexeEmptypeName: 'Employee Type',
      taxexeThreshold: 'Threshold',
      taxexeSdate: 'Start Date',
      taxexeEdate: 'End Date',
      comment: 'Comment',
    },
    baseBankinfo: {
      title: 'Bank Information Maintenance ',
      bankCodeDis: 'Please enter bank code/line number',
      banknameDis: 'Please enter bank Chinese/English name',
      bankSwiftcodeDis: 'Please enter swiftcode or international code',
      bankCityNameDis: 'Please select your city',
      bankCnameDis: 'Please enter Chinese name',
      bankEnameDis: 'Please input English name',
      bankCaddDis: 'Please enter Chinese address',
      bankEaddDis: 'Please enter the English address',
      commentDis: 'Please enter Comment',
      bankCode: 'Bank code/line number',
      bankCityName: 'Suborinate City',
      bankCname: 'Chinese Name',
      bankEname: 'English Name',
      bankCadd: 'Chinese Address',
      bankEadd: 'English Address',
      bankSwiftcode: 'Swift Code',
      comment: 'Comment',
    },
    baseLevareason: {
      title: 'Leave Reson Maintenance',
      levaCodeDis: 'Please Enter Code',
      levaReatypeNameDis: 'Select reasons for leaving',
      levaCnameDis: 'Please enter Chinese',
      levaEnameDis: 'Please enter English',
      commentDis: 'Please enter comment',
      levaCode: 'Code',
      levaReatypeName: 'Reason Type',
      levaCname: 'Chinese',
      levaEname: 'English',
      comment: 'Comment',
      levaname: 'Please enter Chinese or English',
    },
    baseLevadfamount: {
      title: 'Retirement Compensation Allowance',
      selCity: 'Please select City',
      levdfDfamountDis: 'Please enter the amount of tax exemption',
      levdfSdateDis: 'Select Start date',
      levdfEdateDis: 'Select end date',
      commentDis: 'Please enter comment',
      levdfCityName: 'Suborinate City',
      levdfDfamount: 'Tax Allowance',
      levdfSdate: 'Start Date',
      levdfEdate: 'End Date',
      comment: 'Comment',
    },
    baseNereason: {
      title: 'Unemployed Reason',
      nerCodeDis: 'Please enter code',
      sscTypeNameDis: 'Please select insurance category',
      nerEnameDis: 'Please enter English',
      nerCnameDis: 'Please enter chinese',
      commentDis: 'Please enter comment',
      nerCode: 'code',
      nerCname: 'Chinese',
      nerEname: 'English',
      comment: 'Comment',
    },
    baseSscoverage: {
      title: 'Social Insurance Information',
      sscCodeDis: 'Please enter Code',
      sscCnameDis: 'Please enter chinese',
      sscEnameDis: 'Please enter english',
      sscTypeNameDis: 'Please enter insurance information',
      commentDis: 'Please enter comment',
      sscCode: 'code',
      sscTypeName: 'Insurance Information',
      sscCname: 'Chinese',
      sscEname: 'English',
      comment: 'Comment',
    },
    baseMapping: {
      baseMapping: 'Mapping relation maintenance',
      mapTypeIns: 'Please select the mapping type',
      mapTypeDis: 'Mapping type',
      mapCode1Ins: 'Please enter Mapping Code1',
      mapCodedesc1Ins: 'Please enter desc1...',
      mapCode2Ins: 'Please enter Mapping Code2',
      mapCodedesc2Ins: 'Please enter desc2...',
      comment: 'Comment',
      commentIns: 'Please enter a comment',
    },
    autocode: {
      autocodeManage: 'Automatic encoding configuration',
      autoFlagIns: 'Please enter the automatic encoding ID...',
      autoNameIns: 'Please enter the auto-encoded name...',
      autoFlag: 'automatic encoding identifier',
      autoName: 'autocode name',
      autoPrefix: 'prefix',
      autoTimeformatName: 'time format',
      autoWater: 'flow number',
      autoValidityName: 'whether valid',
      autoCode: 'current encoding',
      autoPrefixIns: 'Please enter a prefix...',
      autoTimeformatNameIns: 'Select time format...',
      autoWaterIns: 'Please enter the number of streams...',
      autoValidityNameIns: 'Select whether it is valid...',
      autoCodeIns: 'Please enter the current encoding...',
      comment: 'Comment',
      commentIns: 'Please enter a comment...',
    },
    wxMsgRecord: {
      wxMsgRecord: 'WeChat message log',
      sdateIns: 'Please select the start time...',
      edateIns: 'Please select the end time...',
      wxmsgSendeeIns: 'Please enter the recipient...',
      wxmsgTime: 'send time',
      wxmsgBustype: 'business type',
      wxmsgMsgtypeDis: 'message type',
      wxmsgDataid: 'data ID',
      wxmsgSendee: 'Recipient',
      wxmsgContent: 'message content',
      comment: 'Comment',
      wxmsgDatasource: 'data source',
      wxmsgTitle: 'message title',
      wxmsgUrl: 'message link',
    },
    smsrecord: {
      smsrecord: 'SMS send log',
      smsPhonesIns: 'Please enter the phone number...',
      sdateIns: 'Select start date',
      edateIns: 'Select end date',
      smsContentIns: 'Please enter SMS content...',
      smsStatusIns: 'Please enter the status...',
      smsPhones: 'Mobile number',
      smsTime: 'send time',
      smsContent: 'SMS content',
      smsError: 'error message',
      smsDatasource: 'data source',
      smsStatus: 'status',
      atlogError: 'error message',
      comment: 'Comment',
      smsEtime: 'end time',
    },
    emaillog: {
      emaillog: 'mail send log',
      mailObjectIns: 'Please enter the subject...',
      sdateIns: 'Select start date',
      edateIns: 'Select end date',
      mailToIns: 'Please enter the recipient...',
      mailCcIns: 'Please enter the CC person...',
      mailContentIns: 'Please enter the message content...',
      mailStatusIns: 'Please enter the status...',
      mailTime: 'send time',
      mailObject: 'theme',
      mailTo: 'Recipient',
      mailCc: 'CC person',
      mailStatus: 'status',
      comment: 'Comment',
      mailError: 'error message',
    },
    baseHousinglease: {
      title: 'Housing lease',
      leaseYear: 'Years',
      leaseAmout: 'Amount',
      leaseCitysDis: 'Citys',
      leaseSdate: 'Valid date',
      leaseEdate: 'Invalid date',
      comment: 'Comment',

      p_leaseYear: 'Please select year',
      p_leaseAmout: 'please select amount',
      p_leaseCitysDis: 'please select citys',
      p_leaseSdate: 'please select date',
      p_leaseEdate: 'please select date',
      p_comment: 'please input comment',

      r_leaseYear: 'Year must be not null',
      r_leaseAmout: 'Amount must be not null',
      r_leaseCitysDis: 'Citys must be not null',
      r_leaseSdate: 'Date must be not null',
    },
  },
}
