export default {
  'zh-CN': {
    sihfRepay: {
      title: '社保详细信息',
      title1: '社保补缴申请',
      title2: '社保补缴确认',
      title3: '补缴申报结果',
      sirpCompany: '公司',
      sirpDept: '部门',
      sirpEmpworkno: '员工工号',
      sirpEmpgid: '唯一标识号',
      sirpCname: '中文名',
      sirpLastname: 'Last Name',
      sirpFirstname: 'First Name',
      sirpIdtype: '证件类型',
      sirpIdno: '证件号码',
      sirpEmptype: '员工类型',
      sirpBenefitlocation: '补缴社保缴纳地',
      sirpBenefitpolicy: '补缴社保政策',
      sirpBenefittype: '补缴社保开户类别',
      sirpSmonth: '补缴开始月',
      sirpEmonth: '补缴结束月',
      sirpPaymonth: '补缴扣费月',
      sirpBaseamt: '每月补缴基数',
      sirpReason: '补缴原因',
      sirpStatus: '状态',
      sirpApplicant: '申请人',
      sirpApplytime: '申请时间',
      sirpIsconfirm: '是否确认',
      sirpNocmreason: '未确认原因',
      sirpConfirmer: '确认人',
      sirpConfirmtime: '确认时间',
      sirpConfirmrecord: '确认记录',
      sirpSbperson: '申报人',
      sirpSbtime: '申报时间',
      sirpSberror: '申报失败原因',
      sirpComment: '备注',
      sirpCompanyPrompt: '请选择公司',
      sirpNocmreasonPrompt: '请输入未确认原因',
      sirpEmpworknoPrompt: '请输入员工工号',
      sirpCnamePrompt: '请输入员工中文名',
      sirpBenefitlocationWarning: '请选择补缴社保缴纳地',
      sirpDeptPrompt: '请选择部门',
      sirpBaseamtWarning: '请输入正确的补缴基数',
      sirpSmonthWarning: '请输入补缴开始月',
      sirpEmonthWarning: '请输入补缴结束月',
      sirpPaymonthWarning: '请输入补缴扣费月',
      sirpEmpWarning: '请先选择公司和部门',
      sirpEmpworknoWarning: '请选择员工信息',
      sirpIsconfirmDis: '是否确认',
      psirpNocmreason: '请输入未确认原因',
      sirpStatusDis: '待确认',
    },
    sihfRepayInsurance: {
      title: '社保险种信息',
      sirpinsInsurance: '险种',
      sirpinsBaseamt: '每月补缴基数',
      sirpinsCompratio: '每月公司补缴比例(%)',
      sirpinsCompamt: '每月公司补缴金额',
      sirpinsCompsum: '公司补缴合计',
      sirpinsPersratio: '每月个人补缴比例(%)',
      sirpinsPersamt: '每月个人补缴金额',
      sirpinsPerssum: '个人补缴合计',
      sirpinsComment: '备注',
      sihfrpinsBaseamtChe: '请参照对应政策险种基数区间，输入正确基数',
      sirpinsInsuranceWarning: '请参照对应政策险种比例区间，输入正确比例',
      sirpinsInsuranceCp: '请输入公司补缴比例',
      sirpinsInsurancePp: '请输入个人补缴比例',
      checkIsConfirm: '您有数据未进行确认处理，请进行确认',
    },
    base: {
      check1: '确认数据',
      isConfirm: '是否确认',
      noreason: '不确认原因',
      pnoreason: '请输入未确认原因',
      yesconfirm: '请选择是否确认',
      reminder: '确认数据成功',
      select: '已确认待申报',
      declare: '申报成功',
      declaref: '申报失败',
      declarefw: '已申报，不能重复申报',
      declarefw2: '请确定提交',
      checkIsConfirm: '',
      deaf: '申报失败原因',
      sirpSberror: '失败原因',
      psirpSberror: '请输入申报失败原因',
      psirpSberrorq: '请确定申报失败？',
      psirpSq: '系统正在进行公积金核算，请稍后。。。？',
      psirpSwwq: '您有数据未进行确认处理，请进行确认!',

    },
  },
  'en-US': {
    base: {
      psirpSwwq: 'You have data not confirmed processing, please confirm!',
      check1: 'Confirm the data',
      isConfirm: 'Whether to confirm',
      noreason: 'Do not confirm the reason',
      pnoreason: 'Please enter the unconfirmed reason',
      yesconfirm: 'Please select whether to confirm',
      reminder: 'Confirm data success',
      select: 'The declaration has been confirmed',
      declare: 'Declare success',
      declaref: 'Declare failure',
      declarefw: 'Declaration has been made and cannot be repeated',
      declarefw2: 'Please make sure to submit',
      checkIsConfirm: '',
      deaf: 'Reasons for failure to declare',
      sirpSberror: 'The reason for failure',
      psirpSberror: 'Please enter the reason of failure',
      psirpSberrorq: 'Please make sure the declaration fails',
      psirpSq: 'The system is carrying out CPF accounting, please wait...?',
    },
    sihfRepayInsurance: {
      sirpNocmreason: 'Reasons not confirmed',
      checkIsConfirm: 'You have data not confirmed processing, please confirm',
      title: 'Social security insurance information',
      sirpinsInsurance: 'Danger is planted',
      sirpinsBaseamt: 'Monthly supplementary payment base',
      sirpinsCompratio: 'Monthly company supplementary payment ratio(%)',
      sirpinsCompamt: 'Monthly company supplementary payment',
      sirpinsCompsum: 'Total of the company\'s supplementary payment',
      sirpinsPersratio: 'Monthly individual contribution proportion(%)',
      sirpinsPersamt: 'Monthly individual supplementary payment',
      sirpinsPerssum: 'Total individual supplementary payment',
      sirpinsComment: 'note',
      sihfrpinsBaseamtChe: 'Please refer to the corresponding policy coverage base interval, enter the correct base',
      sirpinsInsuranceWarning: 'Please refer to the corresponding policy coverage proportion interval, input the correct proportion',
      sirpinsInsuranceCp: 'Please input the company\'s contribution proportion',
      sirpinsInsurancePp: 'Please enter your personal contribution proportion',
    },
    sihfRepay: {
      sirpStatusDis: 'To be confirmed',
      psirpNocmreason: 'Please enter the unconfirmed reason',
      title: 'Social security details',
      title1: 'Social security compensation application',
      title2: 'Confirm the social security payment',
      title3: 'The result of the supplementary declaration',
      sirpCompany: 'The company',
      sirpDept: 'department',
      sirpEmpworkno: 'Employees working',
      sirpEmpgid: 'Unique identification number',
      sirpCname: 'Chinese name',
      sirpLastname: 'Last Name',
      sirpFirstname: 'First Name',
      sirpIdtype: 'Document type',
      sirpIdno: 'I.d.',
      sirpEmptype: 'Employee type',
      sirpBenefitlocation: 'Make up pay social security to pay ground',
      sirpBenefitpolicy: 'Make up social security policy',
      sirpBenefittype: 'Make up pay social security to open an account category',
      sirpSmonth: 'Starting month of supplementary payment',
      sirpEmonth: 'Month of completion of supplementary payment',
      sirpPaymonth: 'Monthly supplementary payment of withholding fee',
      sirpBaseamt: 'Monthly supplementary payment base',
      sirpReason: 'Payment of reason',
      sirpStatus: 'state',
      sirpApplicant: 'The applicant',
      sirpApplytime: 'To apply for time',
      sirpIsconfirm: 'Whether to confirm',
      sirpNocmreason: 'Reasons not confirmed',
      sirpConfirmer: 'Confirm the people',
      sirpConfirmtime: 'Set the time',
      sirpConfirmrecord: 'Confirm that the record',
      sirpSbperson: 'The notifier',
      sirpSbtime: 'The time',
      sirpSberror: 'Reasons for failure to declare',
      sirpComment: 'note',
      sirpCompanyPrompt: 'Please select company',
      sirpNocmreasonPrompt: 'Please enter the unconfirmed reason',
      sirpEmpworknoPrompt: 'Please enter the employee number',
      sirpCnamePrompt: 'Please enter your employee\'s Chinese name',
      sirpBenefitlocationWarning: 'Please choose the place of social security payment',
      sirpDeptPrompt: 'Please select department',
      sirpBaseamtWarning: 'Please enter the correct payment base',
      sirpSmonthWarning: 'Please enter the starting month of the supplementary payment',
      sirpEmonthWarning: 'Please enter the end month of the supplementary payment',
      sirpPaymonthWarning: 'Please enter the month of repayment fee',
      sirpEmpWarning: 'Please select the company and department first',
      sirpEmpworknoWarning: 'Please select employee information',
      sirpIsconfirmDis: 'Whether to confirm',
    },

  },
}
