export default {
  'zh-CN': {
    Mulg: {
      title: '多语言信息管理',
      lanType: '所属分类',
      lanCode: '编码',
      lanCn: '中文',
      lanEn: '英文',
      lanTw: '繁体',
      lanOth1: '其他语言1',
      lanOth2: '其他语言2',
      lanOth3: '其他语言3',
      lanOth4: '其他语言4',
      lanOth5: '其他语言5',
      comment: '备注',
      lanTypeDis: '所属分类',
      p_lanTypeDis: '请选择多语言类型',
      p_lanCode: '请输入编码',
      p_lanCn: '请输入中文',
      p_lanEn: '请输入英文',
      p_lanTw: '请输入繁体',
      p_comment: '请输入备注...',
      p_encn: '请输入中/英文',
      rule_lanType: '请填写分类',
      rule_lanCode: '请填写编码',
      rule_lanCn: '请填写中文',
    },
    searchType: {
      title: '多语言类型',
      searchText1: '请输入类型名称',
      searchText2: '请输入类型编码',
      lanTypeName: '分类名称',
      lanTypeCode: '分类编码',
    },

  },
  'en-US': {
    Mulg: {
      title: 'Multilingual Management',
      lanType: 'Lan Type',
      lanCode: 'Lan Code',
      lanCn: 'Chinese simplified ',
      lanEn: 'English',
      lanTw: 'Chinese traditional ',
      lanOth1: 'Other1',
      lanOth2: 'Other2',
      lanOth3: 'Other3',
      lanOth4: 'Other4',
      lanOth5: 'Other5',
      comment: 'comment',
      lanTypeDis: 'category',
      p_lanTypeDis: 'Please chioce one type',
      p_lanCode: 'please input lan code',
      p_lanCn: 'please input Chinese simplified',
      p_lanEn: 'please input English',
      p_lanTw: 'please input Chinese traditional',
      p_comment: 'please input comment...',
      p_encn: 'please input Chinese simplified or English',
      rule_lanType: 'Please input lan type',
      rule_lanCode: 'Please input lan code',
      rule_lanCn: 'Please input lan cn',
    },
    searchType: {
      title: 'lan type',
      searchText1: 'Please input lanTypeName',
      searchText2: 'Please input lanTypeCode',
      lanTypeName: 'LanType Name',
      lanTypeCode: 'LanType Code',
    },
  },
}
