export default {
  'zh-CN': {
    export: {
      selectAll: '全选',
    },
    import: {
      importTemplate: '导入模板',
      downTemplate: '下载模板',
      selectImpType: '选择导入模板方式',
      upd: '更新',
      addReminder: '导入文件中的记录，如不在系统中，则新增至系统；如已在系统中，则不被导入，同时系统会生成未导入原因的说明文件。',
      updReminder: '导入文件中的记录，如已在系统中，则以导入文件中的记录更新系统中对应的记录。如不在系统中，则不被导入，同时系统会生成未导入原因的说明文件。',
      selectFile: '选择要上传的文件 ：',
      browsing: '浏览',
      importing: '正在导入',
      confirmImp: '确认导入',
      importReminder: '导入的文件必须是xls，xlsx格式。',
      importErr: '文件格式错误！',
      uploadSuc: '上传成功',
      exportTemplate: '导出模板',
      impResult: '导入结果',
      downloadFail: '导入文件失败',
      fieldsNoImport: '字段未导入',
    },
  },
  'en-US': {
    export: {
      selectAll: 'All',
    },
    import: {
      importTemplate: 'import template',
      downTemplate: 'download template',
      selectImpType: 'select the way of import',
      upd: 'update',
      addReminder: 'The records in the import file are added to the system if they are not in the system; if they are already in the system, they are not imported, and the system generates a description file that does not import the reason.',
      updReminder: 'The records in the import file, if already in the system, update the corresponding records in the system with the records in the import file. If it is not in the system, it will not be imported. At the same time, the system will generate a description file for the reasons that have not been imported.',
      selectFile: 'Select the file to upload ：',
      browsing: 'Browsing',
      importing: 'Importing',
      confirmImp: 'Confirm import',
      importReminder: 'The imported file must be in xls, xlsx format.',
      importErr: 'File format error！',
      uploadSuc: 'Uploaded successfully',
      exportTemplate: 'export template',
      impResult: 'import results',
      downloadFail: 'Import file fail!',
      fieldsNoImport: 'Filed is not imported!',
    },
  },
}
