export default {
  'zh-CN': {
    platCustoption: {
      title: '自定义选项管理',
      cptTablename: '自定义选项表',
      cptFiele: '自定义选项字段',
      comment: '备注',
      p_cptcOrder: '请输入序号',
      p_cptcCname: '请输入选项内容中文',
      p_cptcEname: '请输入选项内容英文',
      p_comment: '请输入备注...',
      p_cptTablename: '请输入自定义选项表',
      p_cptFiele: '请输入自定义选项字段',
      rule_cptTablename: '请输入自定义选项表',
      rule_cptFiele: '请输入自定义选项字段',
      title1: '自定义选项',
      title2: '自定义选项内容',
    },
    platCopcontent: {
      title: '自定义选项内容',
      cptcOrder: '序号',
      cptcOptionDis: '自定义选项',
      cptcCname: '选项内容中文',
      cptcEname: '选项内容英文',
      comment: '备注',
      p_cptcOrder: '请输入序号',
      p_cptcCname: '请输入选项内容中文',
      p_cptcEname: '请输入选项内容英文',
      p_comment: '请输入备注...',
      rule_cptcOrder: '请输入序号',
      rule_cptcCname: '请输入选项内容中文',
      rule_cptcEname: '请输入选项内容英文',
    },
  },
  'en-US': {
    platCustoption: {
      title: 'Custom option management',
      cptTablename: 'Custom options table',
      cptFiele: 'Custom options ',
      comment: 'comment',
      p_cptTablename: 'Please input table name',
      p_cptFiele: 'Please input table field',
      p_comment: 'Please input commnet...',
      rule_cptTablename: 'Please input table name',
      rule_cptFiele: 'Please input table field',
      title1: 'Custom options',
      title2: 'Custom options content',
    },
    platCopcontent: {
      title: 'Custom option content',
      cptcOrder: 'order',
      cptcOptionDis: 'Custom options',
      cptcCname: 'Content Chinese',
      cptcEname: 'Content English',
      comment: 'comment',
      p_cptcOrder: 'Please input order',
      p_cptcCname: 'please input content cn',
      p_cptcEname: 'please input content en',
      p_comment: 'Please input comment',
      rule_cptcOrder: 'Please input order',
      rule_cptcCname: 'please input content cn',
      rule_cptcEname: 'please input content en',
    },
  },
}
