export default {
  'zh-CN': {
    paySalItem: {
      title: '薪资项目管理',
      paysiOrderDis: '请输入项目序号',
      paysiCodeDis: '请输入项目编码',
      paysiSearchDis: '请输入项目中文名/英文名',
      paysiCNDis: '请输入项目中文名称',
      paysiENDis: '请输入项目英文名称',
      paysiIsdefaultssiNameDis: '请选择是否薪资套账缺省项目',
      paysiDefaulttypeNameDis: '请选择缺省项目类别',
      paysiDefaultdtsourceNameDis: '请输入缺省数据来源',
      paysiCommentDis: '请输入备注',
      paysiOrder: '项目序号',
      paysiCode: '项目编码',
      paysiCN: '项目中文名称',
      paysiEN: '项目英文名称',
      paysiIsdefaultssiName: '是否新账套缺省项目',
      paysiDefaulttypeName: '缺省项目类别',
      paysiDefaultdtsourceName: '缺省数据来源',
      paysiComment: '备注',
    },
    paySalSet: {
      title: '薪资账套管理',
      payssCodeDis: '请输入项目编码',
      payssCNDis: '请输入项目中文名称',
      payssENDis: '请输入项目名称英文',
      payssLocalcurrencyDis: '请输入本位币',
      payssContactDis: '请输入联系人',
      payssEmailDis: '请输入联系人邮箱',
      payssPhoneDis: '请输入联系人电话',
      payssCommentDis: '请输入备注',
      payssCode: '账套编码',
      payssCN: '账套名称中文',
      payssEN: '账套名称英文',
      payssLocalcurrency: '本位币',
      payssContact: '联系人',
      payssEmail: '联系人邮箱',
      payssPhone: '联系人电话',
      payssComment: '备注',
    },
    paySalSetItem: {
      title: '薪资账套项目',
      payssiItemCode: '项目编码',
      payssiItemName: '薪资项目',
      payssiItemtypeName: '项目类别',
      payssiCurrencyName: '项目币种',
      payssiDatasource: '数据来源',
      payssiFormula: '薪资公式',
      payssiFormulacomment: '公式备注',
      payssiCarrymode: '进位方式',
      payssiPaylistdis: '工资单是否显示',
      payssiObversion: '是否依据入职离职日期折算显示',
      isValid: '是否启用',
      payssiComment: '备注',
      payssiOrderDis: '请输入序号',
      payssiOrder: '序号',
      payssiItemNameDis: '请选择薪资项目',
      payssiItemtypeNameDis: '请选择项目类别',
      payssiCurrencyNameDis: '请选择项目币种',
      payssiDatasourceDis: '请选择数据来源',
      payssiFormulaDis: '请配置薪资公式',
      payssiFormulacommentDis: '请输入公式备注',
      payssiCarrymodeDis: '请选择进位方式',
      payssiSelectDis: '请选择',
      payssiCommentDis: '请输入备注',
      currencyColumn: '选择币种',
      salItemColumn: '选择项目',
    },
    payFormula: {
      title: '薪资公式设置',
      itemHead: '运算项目',
      contentHead: '公式内容',
      calHead: '基本计算',
      comment: '备注',
    },
    payCompConfig: {
      title: '公司薪资配置',
      pcgCompany: '服务公司',
      pcgEmptype: '员工类型',
      pcgSalset: '薪资账套',
      pcgSdate: '生效日期',
      pcgEdate: '失效日期',
      pcgComment: '备注',
      pcgCompanyDis: '请选择公司',
      pcgEmptypeDis: '请选择员工类型',
      pcgSalsetDis: '请选择薪资账套',
      pcgSdateDis: '选择生效日期',
      pcgEdateDis: '选择失效日期',
      pcgCommentDis: '请输入备注...',
    },
    payProcessconfig: {
      title: '薪资流程配置',
      ppcSalset: '薪资账套',
      ppcScopecode: '范围代码',
      ppcScopename: '范围名称',
      ppcCompanyscope: '公司范围',
      ppcRole: '角色',
      ppcContact: '联系人',
      ppcEmail: '联系人邮箱',
      ppcPhone: '联系人电话',
      ppcSdate: '生效日期',
      ppcEdate: '失效日期',
      ppcComment: '备注',
      ppcSalsetDis: '请选择薪资账套',
      ppcScopecodeDis: '请输入范围代码...',
      ppcScopenameDis: '请输入范围名称...',
      ppcCompanyscopeDis: '请输入公司范围...',
      ppcRoleDis: '请选择角色',
      ppcSdateDis: '选择生效日期',
      ppcEdateDis: '选择失效日期',
      ppcCommentDis: '请输入备注...',
      ppcContactDis: '请输入联系人...',
      ppcEmailDis: '请输入联系人邮箱...',
      ppcPhoneDis: '请输入联系人电话...',
    },
    payPlantemplate: {
      title: '薪资计划模板',
      pltpYear: '财年',
      pltpSalset: '薪资账套',
      pltpTaskshort: '任务简称',
      pltpTaskname: '任务名称',
      pltpTaskdesc: '任务描述',
      pltpIskey: '是否关键任务',
      pltpTasktype: '任务类型',
      pltpTaskday: '任务日期',
      pltperson: '任务负责人',
      pltpSpecdate: '年度特殊日',
      pltpNonworkrule: '非工作日规则',
      pltpTime: '执行时间',
      pltpComment: '备注',
      pltpYearDis: '请选择财年',
      pltpSalsetDis: '请选择薪资账套',
      pltpTaskshortDis: '请输入任务简称',
      pltpTasknameDis: '请输入任务名称',
      pltpIskeyDis: '请选择是否关键任务',
      pltpTasktypeDis: '请选择任务类型',
      pltpTaskdayDis: '请选择任务日期',
      pltpersonDis: '请选择任务负责人',
      pltpSpecdateDis: '请选择年度特殊日',
      pltpNonworkruleDis: '请选择非工作日规则',
      pltpTimeDis: '请选择执行时间',
      pltpCommentDis: '请输入备注',
      pltpReminder01: '请选择财年和薪资账套',
    },
    payPlantemperson: {
      title: '任务负责人',
      pltpsEmployee: '员工',
      pltpsEmpNo: '员工工号',
      pltpsEmpName: '员工姓名',
      pltpsEmpCmp: '公司',
      pltpsEmpDept: '部门',
      pltpsEmpstatus: '员工状态',
      pltpsEmpstatusInit: '在职',
      pltpsIsmain: '主负责人',
      pltpsResdesc: '负责简述',
      pltpsComment: '备注',
      pltpsEmployeeDis: '请选择员工',
      pltpsEmpstatusDis: '员工状态',
      pltpsIsmainDis: '请选择是否主负责人',
      pltpsResdescDis: '请输入负责简述',
      pltpsCommentDis: '请输入备注',
    },
    payAdd: {
      baseTitle: '入职薪资账套',
      baseSubTitle: '入职薪资明细',
      title1: '入职薪资核定',
      title2: '入职薪资确认',
      title3: 'HR系统更新',
      pladBussource: '业务来源',
      pladEmpworkno: '员工工号',
      pladCname: '中文名',
      pladBusdesc: '业务简述',
      pladEmpgid: '唯一标识号',
      pladEmptype: '员工类型',
      pladLastname: 'Last Name',
      pladFirstname: 'First Name',
      pladIdtype: '证件类型',
      pladIdno: '证件号码',
      pladCompany: '公司',
      pladDept: '部门',
      pladPost: '岗位',
      pladCostcenter: '成本中心',
      pladPostlevel: '职位级别',
      pladSalarylevel: '薪资级别',
      pladTravellevel: '差旅级别',
      pladAdminlevel: '行政级别',
      pladTaxlocation: '个税缴纳地',
      pladSalarycurrency: '薪资币种',
      pladEntrydate: '入职日期',
      pladSalaryset: '薪资账套',
      pladStatus: '状态',
      pladConfirmrecord: '确认记录',
      pladApplicant: '核定人',
      pladApplytime: '核定时间',
      pladConfirmer: '确认人',
      pladConfirmtime: '确认时间',
      pladUpdperson: '更新人',
      pladUpdtime: '更新时间',
      pladIsconfirm: '是否确认',
      pladNocmreason: '未确认原因',
      pladComment: '备注',
      //-----
      pladBussourceDis: '请选择业务来源',
      pladEmpworknoDis: '请输入员工工号',
      pladCnameDis: '请输入员工中文名',
      pladBusdescDis: '请输入业务简述',
      pladEmpgidDis: '请输入唯一标识号',
      pladEmptypeDis: '请选择员工类型',
      pladLastnameDis: '请输入Last Name',
      pladFirstnameDis: '请输入First Name',
      pladIdtypeDis: '请选择证件类型',
      pladIdnoDis: '请输入证件号码',
      pladCompanyDis: '请选择公司',
      pladDeptDis: '请选择部门',
      pladPostDis: '请选择岗位',
      pladCostcenterDis: '请选择成本中心',
      pladPostlevelDis: '请选择职位级别',
      pladSalarylevelDis: '请选择薪资级别',
      pladTravellevelDis: '请选择差旅级别',
      pladAdminlevelDis: '请选择行政级别',
      pladTaxlocationDis: '请选择个税缴纳地',
      pladSalarycurrencyDis: '请选择薪资币种',
      pladEntrydateDis: '请选择入职日期',
      pladSalarysetDis: '请选择薪资账套',
      pladStatusDis: '请选择状态',
      pladConfirmrecordDis: '暂未提交,没有确认记录!',
      pladCommentDis: '请输入备注',
      pladApplicantDis: '申请人',
      pladApplytimeDis: '申请时间',
      pladIsconfirmDis: '是否确认',
      pladNocmreasonDis: '请输入未确认原因',
      // ----
      handRemind: '您有数据未初始化，请先初始化!',
      noconfirmRemind: '您有数据未进行确认处理，请进行确认!',
      // isOrNotConfirm
      confirmTitle: '确认数据',
      yes: '是',
      no: '否',
    },
    payAddSalItem: {
      pladitmType: '项目类别',
      pladitmItem: '薪资项目',
      pladitmCurrency: '项目币种',
      pladitmAmount: '薪资金额',
      pladitmSdate: '生效日期',
      pladitmEdate: '失效日期',
      pladitmComment: '备注',
      // --
      pladitmTypeDis: '请选择项目类别',
      pladitmItemDis: '请选择薪资项目',
      pladitmCurrencyDis: '请选择项目项目币种',
      pladitmAmountDis: '请输入金额',
      pladitmSdateDis: 'pladitmSdate',
      pladitmEdateDis: '选择失效日期',
      pladitmCommentDis: '请输入备注',
    },
    payEnd: {
      baseTitle: '离职薪资账套',
      baseSubTitle: '离职薪资明细',
      title1: '离职薪资核定',
      title2: '离职薪资确认',
      title3: 'HR系统更新',
      pledBussource: '业务来源',
      pledEmpworkno: '员工工号',
      pledCname: '中文名',
      pledBusdesc: '业务简述',
      pledEmpgid: '唯一标识号',
      pledEmptype: '员工类型',
      pledLastname: 'Last Name',
      pledFirstname: 'First Name',
      pledIdtype: '证件类型',
      pledIdno: '证件号码',
      pledCompany: '公司',
      pledDept: '部门',
      pledPost: '岗位',
      pledCostcenter: '成本中心',
      pledPostlevel: '职位级别',
      pledSalarylevel: '薪资级别',
      pledTravellevel: '差旅级别',
      pledAdminlevel: '行政级别',
      pledTaxlocation: '个税缴纳地',
      pledSalarycurrency: '薪资币种',
      pledDimdate: '离职日期',
      pledDimtype: '离职类型',
      pledSalaryset: '薪资账套',
      pledStatus: '状态',
      pledConfirmrecord: '确认记录',
      pledApplicant: '核定人',
      pledApplytime: '核定时间',
      pledConfirmer: '确认人',
      pledConfirmtime: '确认时间',
      pledUpdperson: '更新人',
      pledUpdtime: '更新时间',
      pledIsconfirm: '是否确认',
      pledNocmreason: '未确认原因',
      pledComment: '备注',
      //-----
      pledBussourceDis: '请选择业务来源',
      pledEmpworknoDis: '请输入员工工号',
      pledCnameDis: '请输入中文名',
      pledBusdescDis: '请输入业务简述',
      pledEmpgidDis: '请输入唯一标识号',
      pledEmptypeDis: '请选择员工类型',
      pledLastnameDis: '请输入Last Name',
      pledFirstnameDis: '请输入First Name',
      pledIdtypeDis: '请选择证件类型',
      pledIdnoDis: '请输入证件号码',
      pledCompanyDis: '请选择公司',
      pledDeptDis: '请选择部门',
      pledPostDis: '请选择岗位',
      pledCostcenterDis: '请选择成本中心',
      pledPostlevelDis: '请选择职位级别',
      pledSalarylevelDis: '请选择薪资级别',
      pledTravellevelDis: '请选择差旅级别',
      pledAdminlevelDis: '请选择行政级别',
      pledTaxlocationDis: '请选择个税缴纳地',
      pledSalarycurrencyDis: '请选择薪资币种',
      pledDimdateDis: '请选择离职日期',
      pledDimtypeDis: '请选择离职类型',
      pledSalaryseDisDis: '请选择薪资账套',
      pledStatusDis: '请选择状态',
      pledConfirmrecordDis: '暂未提交,没有确认记录!',
      pledCommentDis: '请输入备注',
      pledApplicantDis: '申请人',
      pledApplytimeDis: '申请时间',
      pledIsconfirmDis: '是否确认',
      pledNocmreasonDis: '请输入未确认原因',
      // ----
      handRemind: '您有数据未初始化，请先初始化!',
      noconfirmRemind: '您有数据未进行确认处理，请进行确认!',
      // isOrNotConfirm
      confirmTitle: '确认数据',
      yes: '是',
      no: '否',
    },
    payEndSalItem: {
      pleditmType: '项目类别',
      pleditmItem: '薪资项目',
      pleditmCurrency: '项目币种',
      pleditmAmount: '薪资金额',
      pleditmSdate: '生效日期',
      pleditmEdate: '失效日期',
      pleditmComment: '备注',
      // --
      pleditmTypeDis: '请选择项目类别',
      pleditmItemDis: '请选择薪资项目',
      pleditmCurrencyDis: '请选择项目项目币种',
      pleditmAmountDis: '请输入金额',
      pleditmSdateDis: '请输入生效日期',
      pleditmEdateDis: '选择失效日期',
      pleditmCommentDis: '请输入备注',
    },
    payAdjust: {
      baseTitle: ' 薪资调整信息',
      baseSubTitle: '薪资调整项目',
      title1: '薪资调整申请',
      title2: '薪资调整确认',
      title3: 'HR系统更新',
      plajCompany: '公司',
      plajDept: '部门',
      plajEmpworkno: '员工工号',
      plajEmpgid: '唯一标识号',
      plajCname: '中文名',
      plajPost: '岗位',
      plajEmptype: '员工类型',
      plajCostcenter: '成本中心',
      plajTaxlocation: '个税缴纳地',
      plajPostlevelOld: '职位级别(原)',
      plajPostlevelNew: '职位级别(新)',
      plajSalarylevelOld: '薪资级别(原)',
      plajSalarylevelNew: '薪资级别(新)',
      plajTravellevelOld: '差旅级别(原)',
      plajTravellevelNew: '差旅级别(新)',
      plajAdminlevelOld: '行政级别(原)',
      plajAdminlevelNew: '行政级别(新)',
      plajSalarycurrency: '薪资币种',
      plajSalaryset: '薪资账套',
      plajReadon: '调整原因',
      plajAdjustdate: '调整生效日期',
      plajConfirmrecord: '确认记录',
      plajStatus: '状态',
      plajApplicant: '申请人',
      plajApplytime: '申请时间',
      plajConfirmer: '确认人',
      plajConfirmtime: '确认时间',
      plajUpdperson: '更新人',
      plajUpdtime: '更新时间',
      plajIsconfirm: '是否确认',
      plajNocmreason: '未确认原因',
      plajComment: '备注',
      // --
      plajCompanyDis: '请选择公司',
      plajDeptDis: '请选择部门',
      plajEmpworknoDis: '请输入员工工号',
      plajEmpgidDis: '请输入唯一标识号',
      plajCnameDis: '请输入中文名',
      plajPostDis: '岗位',
      plajEmptypeDis: '员工类型',
      plajCostcenterDis: '成本中心',
      plajTaxlocationDis: '个税缴纳地',
      plajPostlevelOldDis: '职位级别(原)',
      plajPostlevelNewDis: '请选择职位级别',
      plajSalarylevelOldDis: '薪资级别(原)',
      plajSalarylevelNewDis: '请选择薪资级别',
      plajTravellevelOldDis: '差旅级别(原)',
      plajTravellevelNewDis: '请选择差旅级别(新)',
      plajAdminlevelOldDis: '行政级别(原)',
      plajAdminlevelNewDis: '请选择行政级别',
      plajSalarycurrencyDis: '请选择薪资币种',
      plajSalarysetDis: '请选择薪资账套',
      plajReadonDis: '请选择调整原因',
      plajAdjustdateDis: '请选择调整生效日期',
      plajConfirmrecordDis: '暂未提交,没有确认记录!',
      plajStatusDis: '请选择状态',
      plajApplicantDis: '申请人',
      plajApplytimeDis: '申请时间',
      plajConfirmerDis: '请输入确认人',
      plajConfirmtimeDis: '请输入确认时间',
      plajUpdpersonDis: '请输入更新人',
      plajUpdtimeDis: '请输入更新时间',
      plajIsconfirmDis: '请选择是否确认',
      plajNocmreasonDis: '请输入未确认原因',
      plajCommentDis: '请输入备注',
      // remind
      noconfirmRemind: '您有数据未进行确认处理，请进行确认!',
      // isOrNotConfirm
      confirmTitle: '确认数据',
      yes: '是',
      no: '否',
    },
    payAdjustItem: {
      plajitmType: '项目类别',
      plajitmItem: '薪资项目',
      plajitmCurrency: '项目币种',
      plajitmAmount: '薪资金额',
      plajitmAdjust: '是否调整',
      plajitmSdate: '生效日期',
      plajitmSpecsdate: '指定生效日期',
      plajitmAdjamt: '调整后金额',
      plajitmComment: '备注',
      // ---
      plajitmTypeDis: '请选择项目类别',
      plajitmItemDis: '请选择薪资项目',
      plajitmCurrencyDis: '请选择项目币种',
      plajitmAmountDis: '请输入薪资金额',
      plajitmAdjustDis: '请输入是否调整',
      plajitmSdateDis: '请选择生效日期',
      plajitmSpecsdateDis: '请指定生效日期',
      plajitmAdjamtDis: '请输入调整后金额',
      plajitmCommentDis: '请输入备注',
    },
    payMonPeriod: {
      title1: '数据收集提交',
      title2: '数据收集确认',
      title3: '数据收集更新',
      plsimnpCompany: '公司',
      plsimnpmnpDept: '部门',
      plsimnpEmpgid: '唯一标识号',
      plsimnpEmpworkno: '员工工号',
      plsimnpCname: '员工姓名',
      plsimnpPeriod: '财年期间',
      plsimnpSalaryset: '薪资账套',
      plsimnpSalaryItem: '薪资项目...',
      plsimnpSalarycurrency: '薪资币种',
      plsimnpStatus: '状态',
      plsimnpIsconfirm: '是否确认',
      plsimnpNocmreason: '未确认原因',
      plsimnpConfirmrecord: '确认记录',
      plsimnpApplicant: '核定人',
      plsimnpApplytime: '核定时间',
      plsimnpConfirmer: '确认人',
      plsimnpConfirmtime: '确认时间',
      plsimnpUpdperson: '更新人',
      plsimnpUpdtime: '更新时间',
      plsimnpComment: '备注',
      plsimndownTemplate: '下载导入模板',
      plsimnuploadData: '导入数据',
      // --
      plsimnpCompanyDis: '请选择公司',
      plsimnpmnpDeptDis: '请选择部门',
      plsimnpEmpgidDis: '请输入唯一标识号',
      plsimnpEmpworknoDis: '请输入员工工号',
      plsimnpCnameDis: '请输入员工姓名',
      plsimnpPeriodDis: '请选择财年期间',
      plsimnpSalarysetDis: '请选择薪资账套',
      plsimnpSalaryItemDis: '请选择薪资项目',
      plsimnpSalarycurrencyDis: '请选择薪资币种',
      plsimnpStatusDis: '请选择状态',
      plsimnpIsconfirmDis: '请选择是否确认',
      plsimnpNocmreasonDis: '请输入未确认原因',
      plsimnpConfirmrecordDis: '暂未提交,没有确认记录!',
      plsimnpApplicantDis: '核定人',
      plsimnpApplytimeDis: '核定时间',
      plsimnpConfirmerDis: '确认人',
      plsimnpConfirmtimeDis: '确认时间',
      plsimnpUpdpersonDis: '更新人',
      plsimnpUpdtimeDis: '更新时间',
      plsimnpCommentDis: '请输入备注',
      // ---
      plsimnpReminder: '请先选择薪资账套!',
      plsimnpReminder2: '请先选择公司、期间和薪资账套!',
      plsimnpReminder3: '请选择期间和薪资账套',
      // ----
      handRemind: '您有数据未初始化，请先初始化!',
      noconfirmRemind: '您有数据未进行确认处理，请进行确认!',
      // isOrNotConfirm
      confirmTitle: '确认数据',
      yes: '是',
      no: '否',
    },
    paySalplan: {
      paysalplan: '拟定月度计划',
      paySalplanConfirm: '确认月度计划',
      paySalplanCheck: '薪资计划查看',
      paySalplanPost: '发布月度计划',
      pltpYearCheck: '请选择财年',
      salplPeriodCheck: '请选择期间',
      salplSalsetCheck: '请选择薪资帐套',
      salplYear: '财年',
      salplPeriod: '期间',
      salplSalsetDis: '薪资帐套',
      salplStatusDis: '状态',
      periodplan: '日历计划',
      error: '请选择财年、期间、薪资帐套!',
      confirm: '请确定提交该条数据?',
      copy: '复制',
      iskey: '关键任务',
      today: '当前日期',
      restday: '节假日/休息日',
      salpltkDate: '任务日期',
      salpltkTaskshort: '任务简称',
      salpltkTaskname: '任务名称',
      salpltkIskeyDis: '是否关键任务',
      salpltkTime: '执行时间',
      person: '负责人',
      iscopay: '确定复制当前选中数据吗?',
      paysalplantask: '月度任务计划',
      salpltkStringCheck: '请输入任务日期',
      salpltkTaskshortCheck: '请输入任务简称',
      salpltkTasknameCheck: '请输入任务名称',
      salpltkTaskdesc: '任务描述',
      salpltkTaskdescCheck: '请输入任务描述',
      salpltkIskeyDisCheck: '请选择是否关键任务',
      salpltkTimeCheck: '请选择执行时间',
      salpltkComment: '备注',
      salpltkCommentCheck: '请输入备注...',
      salpltkpEmployeeNoDis: '员工工号',
      salpltkpEmployeeDis: '员工姓名',
      salpltkpEmployeeCompanyDis: '公司',
      salpltkpEmployeeDeptDis: '部门',
      salpltkpIsmainDis: '主负责人',
      salpltkpResdesc: '负责简述',
      salpltkpEmpstatusDis: '状态',
      salpltkpIsmain: '是否主要负责人',
      salpltkpComment: '备注',
      salpltkpEmployeeDisCheck: '请选择员工',
      salpltkpIsmainCheck: '请选择是否主要负责人',
      salpltkpResdescCheck: '请输入任务简称',
      salpltkpCommentCheck: '请输入备注...',
      empstatus: '在职',
      confirmCheck: '提交确认',
      confirmInfo: '确认信息',
      salplcfConfirmtime: '确认时间',
      salplcfConfirmerDis: '确认人',
      salplcfConfirmedDis: '是否确认',
      salplcfReason: '未确认原因',
      post: '发布',
      yes: '是',
      no: '否',
      unconfirmed: '请输入未确认原因',
      confirmNull: '请选择确认状态',
      confirmRes: '请确定提交确认结果？',
    },
    payAccount: {
      title: '薪资核算处理',
      paccPeriod: '期间',
      paccRound: '轮次',
      paccSalaryset: '薪资账套',
      paccLocalcurrency: '本位币',
      totalAmount: '总额',
      updateBy: '更新人',
      updateTime: '更新时间',
      paccStatus: '状态',
      payAccount: '核算',
      paccOptrecord: '操作记录',
      paccComment: '备注',
      // --
      paccPeriodDis: '请选择期间',
      paccRoundDis: '请选择轮次',
      paccSalarysetDis: '请选择薪资账套',
      paccLocalcurrencyDis: '请选择本位币',
      paccStatusDis: '请选择状态',
      paccOptrecordDis: '请输入操作记录',
      paccCommentDis: '请输入备注',
      // --
      accountRemind: '系统正在进行薪资核算，请稍后。。。',
      accountSuc: '核算成功',
    },
    payAccEmp: {
      title: '薪资明细',
      pacemCompany: '公司',
      pacemDept: '部门',
      pacemEmpworkno: '员工工号',
      pacemEmpgid: '唯一标识号',
      pacemCname: '员工姓名',
      pacemIdtype: '证件类型',
      pacemIdno: '证件号码',
      pacemBank: '开户银行',
      pacemAccount: '银行账号',
      pacemMse: '免税额',
      pacemJsgz: '计税工资/税前工资',
      pacemYfgz: '应发工资',
      pacemSfgz: '实发工资',
      pacemComment: '备注',
      // ----
      pacemCompanyDis: '请选择公司',
      pacemDeptDis: '请选择部门',
      pacemEmpworknoDis: '请输入员工工号',
      pacemEmpgidDis: '请输入唯一标识号',
      pacemCnameDis: '请输入员工姓名',
      pacemIdtypeDis: '请选择证件类型',
      pacemIdnoDis: '请输入证件号码',
      pacemBankDis: '请选择开户银行',
      pacemAccountDis: '请输入银行账号',
      pacemMseDis: '请输入免税额',
      pacemJsgzDis: '计税工资/税前工资',
      pacemYfgzDis: '请输入应发工资',
      pacemSfgzDis: '请输入实发工资',
      pacemCommentDis: '请输入备注',
      pacemCnameOrNum: '请输入员工工号/姓名',
      // reminder
      reminder1: '请选择期间和公司或账套!',
    },
    payAccItem: {
      title: '薪资项目明细',
      pacemEmpworkno: '员工工号',
      pacemCname: '中文名',
      pacemimItem: '薪资项目',
      pacemimCurrency: '项目币种',
      pacemimValue: '项目值',
      pacemimAmount: '金额',
      pacemimLcamount: '本位币金额',
      pacemimComment: '备注',
      pacemEmpworknoDis: '请输入员工工号',
      pacemCnameDis: '请输入中文名',
      pacemimItemDis: '请选择薪资项目',
      pacemimCurrencyDis: '请选择项目币种',
      pacemimValueDis: '请输入项目值',
      pacemimAmountDis: '请输入金额',
      pacemimLcamountDis: '请输入本位币金额',
      pacemimCommentDis: '请输入备注',
    },
    empPayroll: {
        title: '员工薪资查询',
    },
    salaryBase: {
      salaryBase: '月度固定薪资',
      deptDisNameIns: '请选择部门',
      worknoDisIns: '请输入员工工号',
      cnameDisIns: '请输入员工中文名',
      companyDis: '公司',
      deptDis: '部门',
      gidDis: '唯一标识号',
      postDis: '职位',
      empTypeDis: '员工类型',
      costCenterDis: '成本中心',
      empsalbsTaxlocationDis: '个税缴纳地',
      empsalbsSalarycurrencyDis: '薪资币种',
      empsalbsSdate: '生效日期',
      empsalbsEdate: '失效日期',
      empsalbsComment: '备注',
      worknoDis: '员工工号',
      cnameDis: '员工中文名',
      empsalbsSalarysetDis: '薪资帐套',
      empsalbsPostlevelDis: '职位级别',
      empsalbsSalarylevelDis: '薪资级别',
      empsalbsTravellevelDis: '差旅级别',
      empsalbsAdminlevelDis: '行政级别',
      searchCmp: '选择公司',
      searchDept: '选择部门',
      unitsNameIns: '请输入公司名称',
      unitsNameIns2: '请输入部门名称',
      unitCode: '公司编码',
      compFnameCnDis: '公司全称',
      compFnameEnDis: '公司全称',
      unitCode2: '部门编码',
      compFnameCnDis2: '部门全称',
      compFnameEnDis2: '部门全称',
      payrollBase: '薪资基本信息',
      payrollItem: '薪资项目信息',
      empsaltmTypeDis: '项目类别',
      empsaltmItemDis: '薪资项目',
      empsaltmCurrencyDis: '项目币种',
      empsaltmAmount: '金额',
      empsaltmSdate: '生效日期',
      empsaltmEdate: '失效日期',
      empsaltmComment: '备注',
    },
    payrollReport: {
      payrollReport: '薪资报税信息',
      reporttypeIns: '请选择报税类型',
      bussourceIns: '请选择员工数据类型',
      payrlogSalsetDis: '薪资帐套',
      payrlogPeriod: '期间',
      payrlogTypeDis: '报税类型',
      payrlogFilename: '下载文件',
      payrlogEmptype: '薪资数据类型',
      createByDis: '操作人',
      createTime: '操作时间',
      paramInfoName1: '全部',
      paramCode1: '',
      paramInfoName2: '当月入职员工',
      paramCode2: '当月入职员工',
      paramInfoName3: '当月离职员工',
      paramCode3: '当月离职员工',
      paramInfoName4: '正常员工',
      paramCode4: '正常员工',
      initErr: '请先选择生成条件!',
    },
    platAplInfo: {
      platAplInfo: '编辑流程图',
      table: '表格',
      editText: '编辑节点的文本',
      editNode: '编辑连接的文本',
      newAplic: '新建连接',
      flsRelation: '步骤关系设置',
      apstrelConditiontitle: '条件标题',
      apstrelConditiondis: '条件',
      apstrelCommment: '备注',
      apstrelConditiontitleIns: '请输入条件标题',
      apstrelConditiondisIns: '请设置生成条件',
      apstrelCommmentIns: '请输入备注',
      condion: '条件设置',
      seachFlowcontacts: '业务联系人',
      flcontNameIns: '请输入联系人名称',
      flowstepInfo: '流程步骤定义',
      apstCode: '步骤编码',
      apstName: '步骤名称',
      apstApprovetype: '审批类型',
      apstApprovelevel: '审批层级',
      apstApprovepost: '审批岗位',
      apstDesapprover: '指定审批人',
      apstApprovemode: '同级多人时审批方式',
      apstComment: '备注',
      apstCodeIns: '请输入步骤编码',
      apstNameIns: '请输入步骤名称',
      apstApprovetypeIns: '请输入审批类型',
      apstApprovelevelIns: '请输入审批层级',
      apstApprovepostIns: '请选择审批岗位',
      apstDesapproverIns: '请选择指定审批人',
      apstApprovemodeIns: '请选择同级多人时审批方式',
      apstCommentIns: '请输入备注',
      flcontMark: '联系人标识',
      flcontName: '联系人名称',
      flcontValueName: '联系人取值变量',
    },
  },
  'en-US': {
    paySalItem: {
      title: 'Payroll Project Management',
      paysiOrderDis: 'Please enter item number',
      paysiSearchDis: 'Please enter the Chinese name/English name of the Item?',
      paysiCodeDis: 'Please enter code',
      paysiCNDis: 'Please enter chinese name',
      paysiENDis: 'Please enter english name',
      paysiIsdefaultssiNameDis: 'Please select is Default Item?',
      paysiDefaulttypeNameDis: 'Please select item type',
      paysiDefaultdtsourceNameDis: 'Please enter the default data source',
      paysiCommentDis: 'Please enter comment',
      paysiOrder: 'Item Order',
      paysiCode: 'Project Code',
      paysiCN: 'Project CN',
      paysiEN: 'Project EN',
      paysiIsdefaultssiName: 'Is Default Item?',
      paysiDefaulttypeName: 'Item Type',
      paysiDefaultdtsourceName: 'Default data source',
      paysiComment: 'Comment',
    },
    paySalSet: {
      title: 'Payroll Set Management',
      payssCodeDis: 'Please enter code',
      payssCNDis: 'Please enter chinese name',
      payssENDis: 'Please enter english name',
      payssLocalcurrencyDis: 'Please enter standard currency',
      payssContactDis: 'Please enter contact',
      payssEmailDis: 'Please enter contact email',
      payssPhoneDis: 'Please enter contact number',
      payssCommentDis: 'Please enter comment',
      payssCode: 'Code',
      payssCN: 'Chinese Name',
      payssEN: 'English Name',
      payssLocalcurrency: 'Standard Currency',
      payssContact: 'Contact',
      payssEmail: 'Contact email',
      payssPhone: 'Contact Phone',
      payssComment: 'Comment',
    },
    paySalSetItem: {
      title: 'Payroll Set items',
      payssiItemCode: 'Items code',
      payssiItemName: 'Payroll Items',
      payssiItemtypeName: 'Project Type',
      payssiCurrencyName: 'Project Currency',
      payssiDatasource: 'Data sources',
      payssiFormula: 'Salary formula',
      payssiFormulacomment: 'Formula Note',
      payssiCarrymode: 'Carry Way',
      payssiPaylistdis: 'Whether the payroll is displayed',
      payssiObversion: 'Whether to convert according to the date of entry',
      isValid: 'Whether to enable',
      payssiComment: 'Comment',
      payssiOrderDis: 'Please enter No.',
      payssiOrder: 'No.',
      payssiItemNameDis: 'Please select payroll items',
      payssiItemtypeNameDis: 'Please select payroll type',
      payssiCurrencyNameDis: 'Please select the item currency',
      payssiDatasourceDis: 'Please select data sources',
      payssiFormulaDis: 'Please allocate the salary formula',
      payssiFormulacommentDis: 'Please enter the formula notes',
      payssiCarrymodeDis: 'Please select carry mode',
      payssiSelectDis: 'Please select',
      payssiCommentDis: 'Please enter comment',
      currencyColumn: 'Select currency',
      salItemColumn: 'Select Item',
    },
    payCompConfig: {
      title: 'Company salary allocation',
      pcgCompany: 'Service company',
      pcgEmptype: 'Employee type',
      pcgSalset: 'Payroll set',
      pcgSdate: 'Effective date',
      pcgEdate: 'Expiration date',
      pcgComment: 'Comment',
      pcgCompanyDis: 'Please select a company',
      pcgEmptypeDis: 'Please select employee type',
      pcgSalsetDis: 'Please select a salary set',
      pcgSdateDis: 'Select effective date',
      pcgEdateDis: 'Select expiration date',
      pcgCommentDis: 'Please enter a comment...',
    },
    payProcessconfig: {
      title: 'Payroll Flow Config',
      ppcSalset: 'Payroll set',
      ppcScopecode: 'Scope code',
      ppcScopename: 'Scope name',
      ppcCompanyscope: 'Company scope',
      ppcRole: 'Role',
      ppcContact: 'Contact person',
      ppcEmail: 'Contact person email',
      ppcPhone: 'Contact person phone',
      ppcSdate: 'Effective date',
      ppcEdate: 'Expiration date',
      ppcComment: 'Comment',
      ppcSalsetDis: 'Please select a salary set',
      ppcScopecodeDis: 'Please input scope code...',
      ppcScopenameDis: 'Please input scope name...',
      ppcCompanyscopeDis: 'Please input company scope...',
      ppcRoleDis: 'Please select a role',
      ppcSdateDis: 'Please select effective date',
      ppcEdateDis: 'Please select expiration date',
      ppcCommentDis: 'Please enter a comment...',
      ppcContactDis: 'Please input person name..',
      ppcEmailDis: 'Please input person email...',
      ppcPhoneDis: 'Please input person phone...',
    },
    payFormula: {
      title: 'Salary formula setting',
      itemHead: 'Operation project',
      contentHead: 'Formula content',
      calHead: 'The basic calculation',
      comment: 'Comment',
    },
    payPlantemplate: {
      title: 'Salary planning template',
      pltpYear: 'Fiscal Year',
      pltpSalset: 'Salary account set',
      pltpTaskshort: 'Task short name',
      pltpTaskname: 'Task name',
      pltpTaskdesc: 'Task Description',
      pltpIskey: 'Is key task ?',
      pltpTasktype: 'Task Type',
      pltpTaskday: 'Task Date',
      pltperson: 'Task ower',
      pltpSpecdate: 'Special day of the year',
      pltpNonworkrule: 'Non-working day rule',
      pltpTime: 'Execution Time',
      pltpComment: 'comment',
      pltpYearDis: 'Please choose the fiscal year',
      pltpSalsetDis: 'Please select a salary set',
      pltpTaskshortDis: 'Please enter the task short name',
      pltpTasknameDis: 'Please enter the task name',
      pltpIskeyDis: 'Please choose whether it is key task!',
      pltpTasktypeDis: 'Please select a task type',
      pltpTaskdayDis: 'Please select a task date',
      pltpersonDis: 'Please select the task owner',
      pltpSpecdateDis: 'Please select the special day of the year',
      pltpNonworkruleDis: 'Please select a non-working day rule',
      pltpTimeDis: 'Please select the execution time',
      pltpCommentDis: 'Please enter comment',
      pltpReminder01: 'Please select the fiscal year and salary set',
    },
    payPlantemperson: {
      title: 'Task manager',
      pltpsEmployee: 'Employee',
      pltpsEmpNo: 'Workno',
      pltpsEmpName: 'Name',
      pltpsEmpCmp: 'Company',
      pltpsEmpDept: 'Depart',
      pltpsEmpstatus: 'Status',
      pltpsEmpstatusInit: 'Active',
      pltpsIsmain: 'Master Manager',
      pltpsResdesc: 'Manager Sketch',
      pltpsComment: 'Comment',
      pltpsEmployeeDis: 'Please select employee',
      pltpsEmpstatusDis: 'Employee status',
      pltpsIsmainDis: 'Please select is or not',
      pltpsResdescDis: 'Please enter manager sketch',
      pltpsCommentDis: 'Please enter comment',
    },
    payAdd: {
      baseTitle: 'Entry salary set',
      baseSubTitle: 'Entry salary details',
      title1: 'Entry salary approval',
      title2: 'Entry salary confirm',
      title3: 'HR System update',
      pladBussource: 'Business source',
      pladEmpworkno: 'Work Num',
      pladCname: 'Chinese Name',
      pladBusdesc: 'Business Brief',
      pladEmpgid: 'Unique Number',
      pladEmptype: 'Employee Type',
      pladLastname: 'Last Name',
      pladFirstname: 'First Name',
      pladIdtype: 'ID Type',
      pladIdno: 'ID Nmber',
      pladCompany: 'Company',
      pladDept: 'Depart',
      pladPost: 'Post',
      pladCostcenter: 'Costcenter',
      pladPostlevel: 'Postlevel',
      pladSalarylevel: 'Salarylevel',
      pladTravellevel: 'Travellevel',
      pladAdminlevel: 'Adminlevel',
      pladTaxlocation: 'Taxlocation',
      pladSalarycurrency: 'Salarycurrency',
      pladEntrydate: 'Entrydate',
      pladSalaryset: 'Salaryset',
      pladStatus: 'Status',
      pladConfirmrecord: 'Confirmrecord',
      pladApplicant: 'Applicant',
      pladApplytime: 'Apply Time',
      pladConfirmer: 'Confirmer',
      pladConfirmtime: 'Confirmer Time',
      pladUpdperson: 'Updater',
      pladUpdtime: 'Update Time',
      pladIsconfirm: 'Is Confirm?',
      pladNocmreason: 'No Confirm reason',
      pladComment: 'Comment',
      //-----
      pladBussourceDis: 'Please select Business source',
      pladEmpworknoDis: 'Please enter the employee number',
      pladCnameDis: 'Please enter employee chinese name',
      pladBusdescDis: 'Please enter a business brief',
      pladEmpgidDis: 'Please enter a unique identification number',
      pladEmptypeDis: 'Please select employee type',
      pladLastnameDis: 'Please enter Last Name',
      pladFirstnameDis: 'Please enter First Name',
      pladIdtypeDis: 'Please select the ID type',
      pladIdnoDis: 'Please enter the ID number',
      pladCompanyDis: 'Please select a company',
      pladDeptDis: 'Please select a department',
      pladPostDis: 'Please select a position',
      pladCostcenterDis: 'Please select a cost center',
      pladPostlevelDis: 'Please select a position level',
      pladSalarylevelDis: 'Please select a salary level',
      pladTravellevelDis: 'Please select a travel level',
      pladAdminlevelDis: 'Please select an administrative level',
      pladTaxlocationDis: 'Please choose a tax payment place',
      pladSalarycurrencyDis: 'Please select a salary currency',
      pladEntrydateDis: 'Please select the entry date',
      pladSalarysetDis: 'Please select a salary set',
      pladStatusDis: 'Please select a status',
      pladConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      pladApplicantDisDis: 'Applicant',
      pladApplytimeDis: 'Apply Time',
      pladIsconfirmDis: 'Is Confirm?',
      pladCommentDis: 'Please enter comment',
      pladNocmreasonDis: 'Please enter no confirm reason',
      // ----
      handRemind: 'You have data not initialized, please initialize first!',
      noconfirmRemind: 'You have data not confirmed processing, please confirm!',
      // isOrNotConfirm
      confirmTitle: 'Confirm Data',
      yes: 'Yes',
      no: 'No',
    },
    payAddSalItem: {
      pladitmType: 'Item Type',
      pladitmItem: 'Salary Item',
      pladitmCurrency: 'Project currency',
      pladitmAmount: 'Salary amount',
      pladitmSdate: 'Effective Date',
      pladitmEdate: 'Expiration Date',
      pladitmComment: 'Comment',
      // --
      pladitmTypeDis: 'Please select item type',
      pladitmItemDis: 'Please select a salary item',
      pladitmCurrencyDis: 'Please select item currency',
      pladitmAmountDis: 'Please enter the amount',
      pladitmSdateDis: 'Please select the effective date',
      pladitmEdateDis: 'Please select an expiration date',
      pladitmCommentDis: 'Please enter comment',
    },
    payEnd: {
      baseTitle: 'Resignation salary set',
      baseSubTitle: 'Resignation salary details',
      title1: 'Resignation salary approval',
      title2: 'Resignation salary confirm',
      title3: 'HR System update',
      pledBussource: 'Business source',
      pledEmpworkno: 'Work Num',
      pledCname: 'Chinese Name',
      pledBusdesc: 'Business Brief',
      pledEmpgid: 'Unique Number',
      pledEmptype: 'Employee Type',
      pledLastname: 'Last Name',
      pledFirstname: 'First Name',
      pledIdtype: 'ID Type',
      pledIdno: 'ID Nmber',
      pledCompany: 'Company',
      pledDept: 'Depart',
      pledPost: 'Post',
      pledCostcenter: 'Costcenter',
      pledPostlevel: 'Postlevel',
      pledSalarylevel: 'Salarylevel',
      pledTravellevel: 'Travellevel',
      pledAdminlevel: 'Adminlevel',
      pledTaxlocation: 'Taxlocation',
      pledSalarycurrency: 'Salarycurrency',
      pledDimdate: 'Resignation date',
      pledDimtype: 'Resignation Type',
      pledSalaryset: 'Salaryset',
      pledStatus: 'Status',
      pledConfirmrecord: 'Confirmrecord',
      pledApplicant: 'Applicant',
      pledApplytime: 'Apply Time',
      pledConfirmer: 'Confirmer',
      pledConfirmtime: 'Confirmer Time',
      pledUpdperson: 'Updater',
      pledUpdtime: 'Update Time',
      pledIsconfirm: 'Is Confirm?',
      pledNocmreason: 'No Confirm reason',
      pledComment: 'Comment',
      //-----
      pledBussourceDis: 'Please select Business source',
      pledEmpworknoDis: 'Please enter the employee number',
      pledCnameDis: 'Please enter a Chinese name',
      pledBusdescDis: 'Please enter a business brief',
      pledEmpgidDis: 'Please enter a unique identification number',
      pledEmptypeDis: 'Please select employee type',
      pledLastnameDis: 'Please enter Last Name',
      pledFirstnameDis: 'Please enter First Name',
      pledIdtypeDis: 'Please select the ID type',
      pledIdnoDis: 'Please enter the ID number',
      pledCompanyDis: 'Please select a company',
      pledDeptDis: 'Please select a department',
      pledPostDis: 'Please select a position',
      pledCostcenterDis: 'Please select a cost center',
      pledPostlevelDis: 'Please select a position level',
      pledSalarylevelDis: 'Please select a salary level',
      pledTravellevelDis: 'Please select a travel level',
      pledAdminlevelDis: 'Please select an administrative level',
      pledTaxlocationDis: 'Please choose a tax payment place',
      pledSalarycurrencyDis: 'Please select a salary currency',
      pledDimdateDis: 'Please select the date of resignation',
      pledDimtypeDis: 'Please select the type of resignation',
      pledSalaryseDisDis: 'Please select a salary set',
      pledStatusDis: 'Please select a status',
      pledConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      pledApplicantDisDis: 'Applicant',
      pledApplytimeDis: 'Apply Time',
      pledIsconfirmDis: 'Is Confirm?',
      pledCommentDis: 'Please enter comment',
      pledNocmreasonDis: 'Please enter no confirm reason',
      // ----
      handRemind: 'You have data not initialized, please initialize first!',
      noconfirmRemind: 'You have data not confirmed processing, please confirm!',
      // isOrNotConfirm
      confirmTitle: 'Confirm Data',
      yes: 'Yes',
      no: 'No',
    },
    payEndSalItem: {
      pleditmType: 'Item Type',
      pleditmItem: 'Salary Item',
      pleditmCurrency: 'Project currency',
      pleditmAmount: 'Salary amount',
      pleditmSdate: 'Effective Date',
      pleditmEdate: 'Expiration Date',
      pleditmComment: 'Comment',
      // --
      pleditmTypeDis: 'Please select item type',
      pleditmItemDis: 'Please select a salary item',
      pleditmCurrencyDis: 'Please select item currency',
      pleditmAmountDis: 'Please enter the amount',
      pleditmSdateDis: 'Please select the effective date',
      pleditmEdateDis: 'Please select an expiration date',
      pleditmCommentDis: 'Please enter comment',
    },
    payAdjust: {
      baseTitle: 'Salary details',
      baseSubTitle: 'Salary Item',
      title1: 'Salary adjustment application',
      title2: 'Salary adjustment confirmation',
      title3: 'HR system update',
      plajCompany: 'Company',
      plajDept: 'Depart',
      plajEmpworkno: 'Work Number',
      plajEmpgid: 'Unique Code',
      plajCname: 'Chinese Name',
      plajPost: 'Post',
      plajEmptype: 'Employee Type',
      plajCostcenter: 'Cost Center',
      plajTaxlocation: 'Tax payment place',
      plajPostlevelOld: 'Position level (original)',
      plajPostlevelNew: 'Position level (new)',
      plajSalarylevelOld: 'Salary level (original)',
      plajSalarylevelNew: 'Salary level (new)',
      plajTravellevelOld: 'Travel level (original)',
      plajTravellevelNew: 'Travel level (new)',
      plajAdminlevelOld: 'Administrative level (original)',
      plajAdminlevelNew: 'Administrative level (new)',
      plajSalarycurrency: 'Salary currency',
      plajSalaryset: 'Salary set',
      plajReadon: 'Adjust Reason',
      plajAdjustdate: 'Effective date',
      plajConfirmrecord: 'Confirmation record',
      plajStatus: 'Status',
      plajApplicant: 'Applicant',
      plajApplytime: 'Applytime',
      plajConfirmer: 'Confirmer',
      plajConfirmtime: 'Confirm time',
      plajUpdperson: 'Update person',
      plajUpdtime: 'Update time',
      plajIsconfirm: 'Is Confirm?',
      plajNocmreason: 'No confirm reason',
      plajComment: 'Comment',
      // --
      plajCompanyDis: 'Please select a company',
      plajDeptDis: 'Please select a department',
      plajEmpworknoDis: 'Please enter employee number',
      plajEmpgidDis: 'Pleas enter unique Code',
      plajCnameDis: 'Please enter Chinese Name',
      plajPostDis: 'Post',
      plajEmptypeDis: 'Employee Type',
      plajCostcenterDis: 'Cost Center',
      plajTaxlocationDis: 'Tax payment place',
      plajPostlevelOldDis: 'Position level (original)',
      plajPostlevelNewDis: 'Please select a position level',
      plajSalarylevelOldDis: 'Salary level (original)',
      plajSalarylevelNewDis: 'Please select a salary level',
      plajTravellevelOldDis: 'Travel level (original)',
      plajTravellevelNewDis: 'Please select a travel level',
      plajAdminlevelOldDis: 'Administrative level (original)',
      plajAdminlevelNewDis: 'Please select an administrative level',
      plajSalarycurrencyDis: 'Please select a salary currency',
      plajSalarysetDis: 'Please select a salary set',
      plajReadonDis: 'Please select the reason for adjustment',
      plajAdjustdateDis: 'Please select the adjustment effective date',
      plajConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      plajStatusDis: 'Please select status',
      plajApplicantDis: 'Applicant',
      plajApplytimeDis: 'Applytime',
      plajConfirmerDis: 'Please enter the confirmer',
      plajConfirmtimeDis: 'Please enter the confirmation time',
      plajUpdpersonDis: 'Please enter the updater',
      plajUpdtimeDis: 'Please enter the update time',
      plajIsconfirmDis: 'Please select whether to confirm',
      plajNocmreasonDis: 'Please enter the reason for unconfirmed',
      plajCommentDis: 'Please enter comment',
      // remind
      noconfirmRemind: 'You have data not confirmed processing, please confirm!',
      // isOrNotConfirm
      confirmTitle: 'Confirm Data',
      yes: 'Yes',
      no: 'No',
    },
    payAdjustItem: {
      plajitmType: 'Item Type',
      plajitmItem: 'Salary Item',
      plajitmCurrency: 'Item currency',
      plajitmAmount: 'Salary amount',
      plajitmAdjust: 'IS adjust?',
      plajitmSdate: 'Effective Date',
      plajitmSpecsdate: 'Specify effective date',
      plajitmAdjamt: 'Adjusted amount',
      plajitmComment: 'Comment',
      // ---
      plajitmTypeDis: 'Please select a item type',
      plajitmItemDis: 'Please select a salary item',
      plajitmCurrencyDis: 'Please select the item currency',
      plajitmAmountDis: 'Please enter the salary amount',
      plajitmAdjustDis: 'Please enter whether to adjust',
      plajitmSdateDis: 'Please select the effective date',
      plajitmSpecsdateDis: 'Please specify the effective date',
      plajitmAdjamtDis: 'Please enter the adjusted amount',
      plajitmCommentDis: 'Please enter a comment',
    },
    payMonPeriod: {
      title1: 'Data collection submit',
      title2: 'Data collection confirm',
      title3: 'Data collection update',
      plsimnpCompany: 'Company',
      plsimnpmnpDept: 'Depaart',
      plsimnpEmpgid: 'Uniqe code',
      plsimnpEmpworkno: 'Employee Number',
      plsimnpCname: 'Employee Name',
      plsimnpPeriod: 'Fiscal Year',
      plsimnpSalaryset: 'Payroll set',
      plsimnpSalaryItem: 'Salary Item...',
      plsimnpSalarycurrency: 'Salary Currency',
      plsimnpStatus: 'Status',
      plsimnpIsconfirm: 'Is Confirm?',
      plsimnpNocmreason: 'Unconfirmed reason',
      plsimnpConfirmrecord: 'Confirm record',
      plsimnpApplicant: 'Approved person',
      plsimnpApplytime: 'Approved time',
      plsimnpConfirmer: 'Confirmor',
      plsimnpConfirmtime: 'Confirm Time',
      plsimnpUpdperson: 'Updater',
      plsimnpUpdtime: 'Update time',
      plsimnpComment: 'Comment',
      plsimndownTemplate: 'Download import template',
      plsimnuploadData: 'Import Data',
      // --
      plsimnpCompanyDis: 'Please select company',
      plsimnpmnpDeptDis: 'Please select department',
      plsimnpEmpgidDis: 'Please enter unique code',
      plsimnpEmpworknoDis: 'Please enter the employee number',
      plsimnpCnameDis: 'Please enter the employee name',
      plsimnpPeriodDis: 'Please select fiscal year',
      plsimnpSalarysetDis: 'Please select a salary set',
      plsimnpSalaryItemDis: 'Please select a salary item',
      plsimnpSalarycurrencyDis: 'Please select a salary currency',
      plsimnpStatusDis: 'Please select status',
      plsimnpIsconfirmDis: 'Please select whether to confirm',
      plsimnpNocmreasonDis: 'Please enter unconfirm reason',
      plsimnpConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      plsimnpApplicantDis: 'Approved Person',
      plsimnpApplytimeDis: 'Approved Time',
      plsimnpConfirmerDis: 'Confirmor',
      plsimnpConfirmtimeDis: 'Confirm time',
      plsimnpUpdpersonDis: 'Updater',
      plsimnpUpdtimeDis: 'Update time',
      plsimnpCommentDis: 'Please enter comment',
      // --
      plsimnpReminder: 'Please select the salary set first!',
      plsimnpReminder2: 'Please select the company, period and salary set first!',
      plsimnpReminder3: 'Please select period and payroll account set',
      // ----
      handRemind: 'You have data not initialized, please initialize first!',
      noconfirmRemind: 'You have data not confirmed processing, please confirm!',
      // isOrNotConfirm
      confirmTitle: 'Confirm Data',
      yes: 'Yes',
      no: 'No',
    },
    paySalplan: {
      paysalplan: 'Draft monthly plan',
      paySalplanConfirm: 'Confirm monthly plan',
      paySalplanCheck: 'Pay plan view',
      paySalplanPost: 'Publish monthly plan',
      pltpYearCheck: 'Please select the fiscal year',
      salplPeriodCheck: 'Please select period',
      salplSalsetCheck: 'Please select a salary set',
      salplYear: 'Fiscal Year',
      salplPeriod: 'Period',
      salplSalsetDis: 'salary set',
      salplStatusDis: 'status',
      periodplan: 'calendar plan',
      error: 'Please select the fiscal year, period, salary set!',
      confirm: 'Please be sure to submit this data?',
      copy: 'copy',
      iskey: 'critical task',
      today: 'current date',
      restday: 'holiday/rest day',
      salpltkDate: 'task date',
      salpltkTaskshort: 'Task short name',
      salpltkTaskname: 'task name',
      salpltkIskeyDis: 'Is it mission critical',
      salpltkTime: 'execution time',
      person: 'person in charge',
      iscopay: 'Are you sure to copy the currently selected data?',
      paysalplantask: 'Monthly mission plan',
      salpltkStringCheck: 'Please enter the task date',
      salpltkTaskshortCheck: 'Please enter the task short name',
      salpltkTasknameCheck: 'Please enter the task name',
      salpltkTaskdesc: 'Task description',
      salpltkTaskdescCheck: 'Please enter the task description',
      salpltkIskeyDisCheck: 'Please choose whether it is a mission critical task',
      salpltkTimeCheck: 'Please select execution time',
      salpltkComment: 'Remarks',
      salpltkCommentCheck: 'Please enter a comment...',
      salpltkpEmployeeNoDis: 'employee number',
      salpltkpEmployeeDis: 'employee name',
      salpltkpEmployeeCompanyDis: 'company',
      salpltkpEmployeeDeptDis: 'department',
      salpltkpIsmainDis: 'main person in charge',
      salpltkpResdesc: 'Responsible for briefing',
      salpltkpEmpstatusDis: 'status',
      salpltkpIsmain: 'Is the main person in charge',
      salpltkpComment: 'Remarks',
      salpltkpEmployeeDisCheck: 'Please select an employee',
      salpltkpIsmainCheck: 'Please choose the main person in charge',
      salpltkpResdescCheck: 'Please enter the task short name',
      salpltkpCommentCheck: 'Please enter a comment...',
      empstatus: 'in-service',
      confirmCheck: 'Confirm Check',
      confirmInfo: 'Confirm Info',
      salplcfConfirmtime: 'confirm time',
      salplcfConfirmerDis: 'confirmer',
      salplcfConfirmedDis: 'whether confirmed',
      salplcfReason: 'Unconfirmed reason',
      post: 'post',
      yes: 'yes',
      no: 'No',
      unconfirmed: 'Please enter the reason for unconfirmed',
      confirmNull: 'Please select confirmation status',
      confirmRes: 'Please confirm the submission of the confirmation result? ',
    },
    payAccount: {
      title: 'Payroll Accounting handle',
      paccPeriod: 'Period',
      paccRound: 'Rounds',
      paccSalaryset: 'Payroll Set',
      paccLocalcurrency: 'Local currency',
      totalAmount: 'Total Amount',
      updateBy: 'Update Person',
      updateTime: 'Update time',
      paccStatus: 'Status',
      payAccount: 'Account',
      paccOptrecord: 'Operation Record',
      paccComment: 'Comment',
      // --
      paccPeriodDis: 'Please select period',
      paccRoundDis: 'Please select the round',
      paccSalarysetDis: 'Please select a salary set',
      paccLocalcurrencyDis: 'Please select the local currency',
      paccStatusDis: 'Please select a status',
      paccOptrecordDis: 'Please enter an operation record',
      paccCommentDis: 'Please enter comment',
      // --
      accountRemind: 'The system is undergoing payroll accounting, please wait a moment. . .',
      accountSuc: 'Account Successfully',
    },
    payAccEmp: {
      title: 'Salary details',
      pacemCompany: 'Company',
      pacemDept: 'Depart',
      pacemEmpworkno: 'Employee number',
      pacemEmpgid: 'Unique Code',
      pacemCname: 'Chinese Name',
      pacemIdtype: 'ID Type',
      pacemIdno: 'ID Number',
      pacemBank: 'Bank Account',
      pacemAccount: 'Bank Account',
      pacemMse: 'Allowance',
      pacemJsgz: 'Axable/pre-tax Salary',
      pacemYfgz: 'Payable',
      pacemSfgz: 'Real wage',
      pacemComment: 'Comment',
      pacemCompanyDis: 'Please select company',
      pacemDeptDis: 'Please select a department',
      pacemEmpworknoDis: 'Please enter the employee number',
      pacemEmpgidDis: 'Please enter unique code',
      pacemCnameDis: 'Please enter chinese name',
      pacemIdtypeDis: 'Please select ID Type',
      pacemIdnoDis: 'Please enter the ID number',
      pacemBankDis: 'Please select open account bank',
      pacemAccountDis: 'Please enter a bank account number',
      pacemMseDis: 'Please enter a tax allowance',
      pacemJsgzDis: 'Please enter the taxable salary / pre-tax salary',
      pacemYfgzDis: 'Please enter the payable salary',
      pacemSfgzDis: 'Please enter the actual wage',
      pacemCommentDis: 'Please enter comment',
      pacemCnameOrNum: 'Please enter employee ID/name',
      // reminder
      reminder1: 'Please select period and company or account set!',
    },
    payAccItem: {
      title: 'Payroll item details',
      pacemEmpworkno: 'Employee Number',
      pacemCname: 'Chinese name',
      pacemimItem: 'Salary Item',
      pacemimCurrency: 'Item Currency',
      pacemimValue: 'Item value',
      pacemimAmount: 'Amount',
      pacemimLcamount: 'Local currency amount',
      pacemimComment: 'Comment',
      pacemEmpworknoDis: 'Please enter the employee number',
      pacemCnameDis: 'Please enter a Chinese name',
      pacemimItemDis: 'Please select a salary item',
      pacemimCurrencyDis: 'Please select the project currency',
      pacemimValueDis: 'Please enter the item value',
      pacemimAmountDis: 'Please enter the amount',
      pacemimLcamountDis: 'Please enter the amount of the local currency',
      pacemimCommentDis: 'Please enter comment',
    },
    empPayroll: {
      title: 'Employee salary query',
    },
    salaryBase: {
      salaryBase: 'Monthly fixed salary',
      deptDisNameIns: 'Please select department',
      worknoDisIns: 'Please enter employee ID number',
      cnameDisIns: 'Please enter the employee Chinese name',
      companyDis: 'company',
      deptDis: 'department',
      gidDis: 'Unique identification number',
      postDis: 'position',
      empTypeDis: 'employee type',
      costCenterDis: 'cost center',
      empsalbsTaxlocationDis: 'A tax payment place',
      empsalbsSalarycurrencyDis: 'salary currency',
      empsalbsSdate: 'effective date',
      empsalbsEdate: 'expiration date',
      empsalbsComment: 'Remarks',
      worknoDis: 'employee number',
      cnameDis: 'employee Chinese name',
      empsalbsSalarysetDis: 'payroll set',
      empsalbsPostlevelDis: 'post level',
      empsalbsSalarylevelDis: 'salary level',
      empsalbsTravellevelDis: 'Travel level',
      empsalbsAdminlevelDis: 'admin level',
      searchCmp: 'Select company',
      searchDept: 'Select department',
      unitsNameIns: 'Please enter the company name',
      unitsNameIns2: 'Please enter the department name',
      unitCode: 'company code',
      compFnameCnDis: 'Company Chinese full name',
      compFnameEnDis: 'Company English full name',
      unitCode2: 'Department code',
      compFnameCnDis2: 'Department Chinese full name',
      compFnameEnDis2: 'The full name of the department',
      payrollBase: 'Basic salary information',
      payrollItem: 'salary project information',
      empsaltmTypeDis: 'project category',
      empsaltmItemDis: 'salary item',
      empsaltmCurrencyDis: 'project currency',
      empsaltmAmount: 'Amount',
      empsaltmSdate: 'effective date',
      empsaltmEdate: 'expiration date',
      empsaltmComment: 'Remarks',
    },
    payrollReport: {
      payrollReport: 'payroll tax information',
      reporttypeIns: 'Please select the tax type',
      bussourceIns: 'Please select employee data type',
      payrlogSalsetDis: 'payroll set',
      payrlogPeriod: 'period',
      payrlogTypeDis: 'report type',
      payrlogFilename: 'download file',
      payrlogEmptype: 'salary data type',
      createByDis: 'operator',
      createTime: 'operation time',
      paramInfoName1: 'all',
      paramCode1: 'all',
      paramInfoName2: 'The employee of the month',
      paramCode2: 'The employee of the month',
      paramInfoName3: 'The employee who left the month',
      paramCode3: 'The employee who left the month',
      paramInfoName4: 'normal employee',
      paramCode4: 'normal employee',
      initErr: 'Please select the generation condition first!',
    },
    platAplInfo: {
      platAplInfo: 'Edit flowchart',
      table: 'table',
      editText: 'Edit the text of the node',
      editNode: 'Edit the text of the connection',
      newAplic: 'New connection',
      flsRelation: 'step relationship setting',
      apstrelConditiontitle: 'condition header',
      apstrelConditiondis: 'condition',
      apstrelCommment: 'Remarks',
      apstrelConditiontitleIns: 'Please enter a condition title',
      apstrelConditiondisIns: 'Please set the generation condition',
      apstrelCommmentIns: 'Please enter a comment',
      condion: 'condition setting',
      seachFlowcontacts: 'Business Contact',
      flcontNameIns: 'Please enter a contact name',
      flowstepInfo: 'Process step definition',
      apstCode: 'step encoding',
      apstName: 'step name',
      apstApprovetype: 'Approval Type',
      apstApprovelevel: 'Approval level',
      apstApprovepost: 'Approval post',
      apstDesapprover: 'designate approver',
      apstApprovemode: 'Approval method for multi-person peers',
      apstComment: 'Remarks',
      apstCodeIns: 'Please enter step code',
      apstNameIns: 'Please enter the step name',
      apstApprovetypeIns: 'Please enter the approval type',
      apstApprovelevelIns: 'Please enter the approval level',
      apstApprovepostIns: 'Please select an approval position',
      apstDesapproverIns: 'Please select the specified approver',
      apstApprovemodeIns: 'Please select the approval method for multiple people at the same level',
      apstCommentIns: 'Please enter a comment',
      flcontMark: 'contact ID',
      flcontName: 'contact name',
      flcontValueName: 'contact value variable',
    },
  },
}
