export default {
  'zh-CN': {
    finServiceboard: {
      title: '财务服务看板',
      subTitle1: '按照公司统计工单数量',
      subTitle2: '按照工单大类统计工单数量',
      subTitle3: '按照月份统计各公司工单数量',
      subTitle4: '按照公司统计工单费用',
      subTitle5: '按照工单大类统计工单费用',
      subTitle6: '按照月份统计各公司工单费用',
      histogram: '柱状图',
      piechart: '饼状图',
      histGroservies1: '公司工单数量统计',
      piechartservies1: '按照公司统计工单数量',
      histGroservies2: '工单大类工单数量统计',
      piechartservies2: '工单大类工单数量统计',
      histGroservies4: '公司工单数量统计',
      piechartservies4: '按照公司统计工单费用',
      histGroservies5: '工单大类工单数量统计',
      piechartservies5: '工单大类工单数量统计',
    },
    orderPriceSetting: {
      tilte: '工单价格管理',
      searhText: '请输入工单类型名称或者编码',
      cmutKntypeCode: '工单类型编码',
      cmutKntypeName: '工单类型名称',
      cmutKntypePid: '所属工单类型',
      cmutKntypeStdprice: '工单服务标准价格',
      cmutKntypeDesc: '简要说明',
      comment: '备注',
      cmutKntypeCodeDis: '请输入工单类型编码',
      cmutKntypeNameDis: '请输入工单类型名称',
      cmutKntypePidDis: '请输入所属工单类型',
      cmutKntypeStdpriceDis: '请输入工单服务标准价格',
      cmutKntypeDescDis: '请输入简要说明',
      commentDis: '请输入备注',
      // --
      allType: '全部工单类型',
      // searchColumns
      flowName: '流程名称',
    },
    servicePriceCount: {
      title: '服务费用统计',
      title2: '服务费用分析',
      authorComp: '提交公司',
      orderType: '工单类型',
      KntypeBusprop: '工单属性',
      kntypeStdprice: '标准服务价格',
      dealingNum: '处理数量',
      allCost: '服务费用',
      authorCompDis: '请选择提交者公司',
      orderTypeDis: '请输入工单类型',
    },
  },
  'en-US': {
    finServiceboard: {
      title: 'Financial services board',
      subTitle1: 'Count the quantity of work order according to the company',
      subTitle2: 'Count the quantity of work order according to the work order category',
      subTitle3: 'Count the number of work orders by month',
      subTitle4: 'Calculate work order cost according to the company',
      subTitle5: 'According to the work sheet category statistics work sheet cost',
      subTitle6: 'According to the monthly statistics of the cost of each company\'s work order',
      histogram: 'A histogram',
      piechart: 'The pie chart',
      histGroservies1: 'Order statistics',
      piechartservies1: 'Orders of company',
      histGroservies2: 'Work order statistics',
      piechartservies2: 'Work order statistics',
      histGroservies4: 'Order statistics',
      piechartservies4: 'Order cost of company',
      histGroservies5: 'order statistics',
      piechartservies5: 'order statistics',
    },
    orderPriceSetting: {
      tilte: 'Work order price management',
      searhText: 'Please enter work order type name or code',
      cmutKntypeName: 'Type Name',
      cmutKntypeCode: 'Type Code',
      cmutKntypePid: 'Type\'s Pid',
      cmutKntypeStdprice: 'Standard price',
      cmutKntypeDesc: 'Brief Description',
      comment: 'Comment',
      cmutKntypeCodeDis: 'Please enter the work order type code',
      cmutKntypeNameDis: 'Please enter the name of the worksheet type',
      cmutKntypePidDis: 'Please enter the type of work order',
      cmutKntypeStdpriceDis: 'Please enter service standard price for work order',
      cmutKntypeDescDis: 'Please enter a brief description',
      commentDis: 'Please enter comment',
      // --
      allType: 'All Types',
      // searchColumns
      flowName: 'Flow Name',
    },
    servicePriceCount: {
      title: 'Service cost statistics',
      title2: 'Service cost analysis',
      authorComp: 'Company',
      orderType: 'Order Yype',
      KntypeBusprop: 'Order Properties',
      kntypeStdprice: 'Standard Price',
      dealingNum: 'Number of processing',
      allCost: 'Service cost',
      authorCompDis: 'Please select submitter company',
      orderTypeDis: 'Please enter work order type',
    },
  },
}
