export default {
  'zh-CN': {
    sihtPolicy: {
      title: '社保政策管理',
      sihfpcyNo: '政策编号',
      sihfpcyCn: '政策名称中文',
      sihfpcyEn: '政策名称英文',
      sihfpcyAreaName: '所属地区',
      sihfpcyRegisterpropertyName: '户口性质',
      sihfpcyScopedesc: '政策适用说明',
      sihfpcyNewdate: '报增日期',
      sihfpcyCutdate: '报减日期',
      sihfpcySamebaseName: '基数是否相同',
      sihfpcySdate: '生效日期',
      sihfpcyEdate: '失效日期',
      sihfpcyComment: '备注',
      sihfpcyNoDis: '请输入政策编号',
      sihfpcyCnDis: '请输入政策名称中文',
      sihfpcyEnDis: '请输入政策名称英文',
      sihfpcyAreaNameDis: '请选择所属地区',
      sihfpcyScopedescDis: '请输入政策适用说明...',
      sihfpcyNewdateDis: '报增日期',
      sihfpcyCutdateDis: '报减日期',
      sihfpcySamebaseNameDis: '选择基数是否相同',
      sihfpcySdateDis: '选择生效日期',
      sihfpcyEdateDis: '选择失效日期',
      sihfpcyCommentDis: '请输入备注...',
    },
    sihtPlcyinsurance: {
      title: '社保政策险种',
      sihfpcyinsPolicyName: '社保政策',

      sihfpcyinsHfPolicyName: '公积金政策',
      sihfpcyinsOrder: '序号',
      sihfpcyinsInsName: '险种',
      sihfpcyinsCbll: '公司缴费基数下限',
      sihfpcyinsCbul: '公司缴费基数上限',
      sihfpcyinsPbll: '个人缴费基数下限',
      sihfpcyinsPbul: '个人缴费基数上限',
      sihfpcyinsCrtypeName: '公司比例类别',
      sihfpcyinsCr: '公司比例(%)',
      sihfpcyinsCrll: '公司比例下限(%)',
      sihfpcyinsCrul: '公司比例上限(%)',
      sihfpcyinsPrtypeName: '个人比例类别',
      sihfpcyinsPr: '个人比例(%)',
      sihfpcyinsPrll: '个人比例下限(%)',
      sihfpcyinsPrul: '个人比例上限(%)',
      sihfpcyinsCall: '月公司缴纳额下限',
      sihfpcyinsCaul: '月公司缴纳额上限',
      sihfpcyinsPall: '月个人缴纳额下限',
      sihfpcyinsPaul: '月个人缴纳额上限',
      sihfpcyinsCarullName: '企业缴费计算规则',
      sihfpcyinsParullName: '个人缴费计算规则',
      sihfpcyinsCaa: '企业附加金额',
      sihfpcyinsPaa: '个人附加金额',
      sihfpcyinsFrequency: '支付频率',
      sihfpcyinsComment: '备注',
      sihfpcyinsOrderDis: '请输入序号',
      sihfpcyinsInsNameDis: '请选择险种',
      sihfpcyinsCbllDis: '请输入公司缴费基数下限',
      sihfpcyinsCbulDis: '请输入公司缴费基数上限',
      sihfpcyinsPbllDis: '请输入个人缴费基数下限',
      sihfpcyinsPbulDis: '请输入个人缴费基数上限',
      sihfpcyinsCrtypeNameDis: '选择公司比例类别',
      sihfpcyinsCrDis: '请输入公司比例',
      sihfpcyinsCrllDis: '请输入公司比例下限',
      sihfpcyinsCrulDis: '请输入公司比例上限',
      sihfpcyinsPrtypeNameDis: '选择个人比例类别',
      sihfpcyinsPrDis: '请输入个人比例',
      sihfpcyinsPrllDis: '请输入个人比例下限',
      sihfpcyinsPrulDis: '请输入个人比例上限',
      sihfpcyinsCallDis: '请输入月公司缴纳额下限',
      sihfpcyinsCaulDis: '请输入月公司缴纳额上限',
      sihfpcyinsPallDis: '请输入月个人缴纳额下限',
      sihfpcyinsPaulDis: '请输入月个人缴纳额上限',
      sihfpcyinsCarullNameDis: '选择企业缴费计算规则',
      sihfpcyinsParullNameDis: '选择个人缴费计算规则',
      sihfpcyinsCaaDis: '请输入企业附加金额',
      sihfpcyinsPaaDis: '请输入个人附加金额',
      sihfpcyinsFrequencyDis: '请输入支付频率',
      sihfpcyinsCommentDis: '请输入备注...',
    },
    sihfBenefitadd: {
      baseTitle: '社保详细信息',
      subTitle: '社保险种明细',
      title1: '报增申报申请',
      title2: '报增申报确认',
      title3: '报增申报结果',
      sibaBussource: '业务来源',
      sibaBusdesc: '业务简述',
      sibaEmpgid: '唯一标识号',
      sibaEmpworkno: '员工工号',
      sibaCname: '中文名',
      sibaEmptype: '员工类型',
      sibaLastname: 'Last Name',
      sibaFirstname: 'First Name',
      sibaIdtype: '证件类型',
      sibaIdno: '证件号码',
      sibaCompany: '公司',
      sibaDept: '部门',
      sibaBenefitlocation: '社保缴纳地',
      sibaEntrydate: '入职日期',
      sibaBenefitpolicy: '社保政策',
      sibaBenefittype: '社保开户类别',
      sibaApplicant: '申请人',
      sibaApplytime: '申请时间',
      sibaIsconfirm: '是否确认',
      sibaNocmreason: '未确认原因',
      sibaConfirmer: '确认人',
      sibaConfirmtime: '确认时间',
      sibaConfirmrecord: '确认记录',
      sibaSbperson: '申报人',
      sibaSbtime: '申报时间',
      sibaStatus: '状态',
      sibaSberror: '申报失败原因',
      sibaSbrecord: '申报记录',
      sibaComment: '备注',
      isOrnot: '确认数据',
      notInit: '您有数据未进行确认处理，请进行确认!',
      isTrue: '确认当前选中的数据是否全部确认',
      isDeclare: '请确定申报？',
      isDeclareSuccess: '请确定申报成功？',
      declareErr: '已申报，不能重复申报!',
      sibaNocmreasonIns: '请输入未确认原因',
      sibaIsconfirmIns: '请选择是否确认',
      yes: '是',
      no: '否',
      // --
      sibaBussourceDis: '请选择业务来源',
      sibaBusdescDis: '请输入业务简述',
      sibaEmpgidDis: '请输入唯一标识号',
      sibaEmpworknoDis: '请输入员工工号',
      sibaCnameDis: '请输入中文名',
      sibaEmptypeDis: '请选择员工类型',
      sibaLastnameDis: '请输入Last Name',
      sibaFirstnameDis: '请输入First Name',
      sibaIdtypeDis: '请选择证件类型',
      sibaIdnoDis: '请输入证件号码',
      sibaCompanyDis: '请选择公司',
      sibaDeptDis: '请选择部门',
      sibaBenefitlocationDis: '请选择社保缴纳地',
      sibaEntrydateDis: '请选择入职日期',
      sibaBenefitpolicyDis: '请选择社保政策',
      sibaBenefittypeDis: '请选择社保开户类别',
      sibaApplicantDis: '请选择申请人',
      sibaApplytimeDis: '请选择申请时间',
      sibaIsconfirmDis: '请选择是否确认',
      sibaNocmreasonDis: '请输入未确认原因',
      sibaConfirmerDis: '请选择确认人',
      sibaConfirmtimeDis: '请选择确认时间',
      sibaConfirmrecordDis: '暂未提交,没有确认记录!',
      sibaSbpersonDis: '请选择申报人',
      sibaSbtimeDis: '请选择申报时间',
      sibaStatusDis: '请选择状态',
      sibaSberrorDis: '请输入申报失败原因',
      sibaSbrecordDis: '请输入申报记录',
      sibaCommentDis: '请输入备注',
      // --
      sibaReminder1: '您有数据未初始化，请先初始化!',
      sibaReminder2: '已申报，不能重复申报!',
      // button
      declareSucc: '申报成功',
      declareFair: '申报失败',
    },
    benefitaddInsurance: {
      sibainsInsurance: '险种',
      sibainsBaseamt: '基数',
      sibainsCompratio: '公司缴纳比例(%)',
      sibainsCompamt: '公司缴纳金额',
      sibainsPersratio: '个人缴纳比例(%)',
      sibainsPersamt: '个人缴纳金额',
      sibaEntrydate: '入职日期',
      sibainsApplymonth: '申请报增月份',
      sibainsSuccmonth: '申报成功月份',
      sibainsComment: '备注',
      // --
      sibainsInsuranceDis: '请选择险种',
      sibainsBaseamtDis: '请输入缴纳基数',
      sibainsCompratioDis: '请输入公司缴纳比例',
      sibainsCompamtDis: '请输入公司缴纳金额',
      sibainsPersratioDis: '请输入个人缴纳比例',
      sibainsPersamtDis: '请输入个人缴纳金额',
      sibaEntrydateDis: '请选择入职日期',
      sibainsApplymonthDis: '请输入申请报增月份',
      sibainsCommentDis: '请输入备注',
    },
    sihfBenefitend: {
      baseTitle: '社保详细信息',
      subTitle: '社保险种明细',
      title1: '报减申报申请',
      title2: '报减申报确认',
      title3: '报减申报结果',
      sibeBussource: '业务来源',
      sibeBusdesc: '业务简述',
      sibeEmpgid: '唯一标识号',
      sibeEmpworkno: '员工工号',
      sibeCname: '中文名',
      sibeEmptype: '员工类型',
      sibeLastname: 'Last Name',
      sibeFirstname: 'First Name',
      sibeIdtype: '证件类型',
      sibeIdno: '证件号码',
      sibeCompany: '公司',
      sibeDept: '部门',
      sibeBenefitlocation: '社保缴纳地',
      sibeEntrydate: '入职日期',
      sibeLastemployday: '最后雇佣日期',
      sibeBenefitpolicy: '社保政策',
      sibeBenefittype: '社保开户类别',
      sibeApplicant: '申请人',
      sibeApplytime: '申请时间',
      sibeIsconfirm: '是否确认',
      sibeNocmreason: '未确认原因',
      sibeConfirmer: '确认人',
      sibeConfirmtime: '确认时间',
      sibeConfirmrecord: '确认记录',
      sibeSbperson: '申报人',
      sibeSbtime: '申报时间',
      sibeStatus: '状态',
      sibeSberror: '申报失败原因',
      sibeSbrecord: '申报记录',
      sibeComment: '备注',
      // --
      sibeBussourceDis: '请选择业务来源',
      sibeBusdescDis: '请输入业务简述',
      sibeEmpgidDis: '请输入唯一标识号',
      sibeEmpworknoDis: '请输入员工工号',
      sibeCnameDis: '请输入中文名',
      sibeEmptypeDis: '请选择员工类型',
      sibeLastnameDis: '请输入Last Name',
      sibeFirstnameDis: '请输入First Name',
      sibeIdtypeDis: '请选择证件类型',
      sibeIdnoDis: '请输入证件号码',
      sibeCompanyDis: '请选择公司',
      sibeDeptDis: '请选择部门',
      sibeBenefitlocationDis: '请选择社保缴纳地',
      sibeEntrydateDis: '请选择入职日期',
      sibeLastemploydayDis: '请选择最后雇佣日期',
      sibeBenefitpolicyDis: '请选择社保政策',
      sibeBenefittypeDis: '请选择社保开户类别',
      sibeApplicantDis: '请选择申请人',
      sibeApplytimeDis: '请选择申请时间',
      sibeIsconfirmDis: '请选择是否确认',
      sibeNocmreasonDis: '请输入未确认原因',
      sibeConfirmerDis: '请选择确认人',
      sibeConfirmtimeDis: '请选择确认时间',
      sibeConfirmrecordDis: '暂未提交,没有确认记录!',
      sibeSbpersonDis: '请选择申报人',
      sibeSbtimeDis: '请选择申报时间',
      sibeStatusDis: '请选择状态',
      sibeSberrorDis: '请输入申报失败原因',
      sibeSbrecordDis: '请输入申报记录',
      sibeCommentDis: '请输入备注',
      // --
      sibeReminder1: '您有数据未初始化，请先初始化!',
      sibeReminder2: '已申报，不能重复申报!',
      // button
      declareSucc: '申报成功',
      declareFair: '申报失败',
      sibeload: '已确认待申报',
    },
    benefitendInsurance: {
      sibeinsInsurance: '险种',
      sibeinsBaseamt: '基数',
      sibeinsCompratio: '公司缴纳比例(%)',
      sibeinsCompamt: '公司缴纳金额',
      sibeinsPersratio: '个人缴纳比例(%)',
      sibeinsPersamt: '个人缴纳金额',
      sibeEntrydate: '入职日期',
      sibeinsApplymonth: '申请报减月份',
      sibeinsSuccmonth: '申报成功月份',
      sibeinsComment: '备注',
      // --
      sibeinsInsuranceDis: '请选择险种',
      sibeinsBaseamtDis: '请输入缴纳基数',
      sibeinsCompratioDis: '请输入公司缴纳比例',
      sibeinsCompamtDis: '请输入公司缴纳金额',
      sibeinsPersratioDis: '请输入个人缴纳比例',
      sibeinsPersamtDis: '请输入个人缴纳金额',
      sibeEntrydateDis: '请选择入职日期',
      sibeinsApplymonthDis: '请输入申请报减月份',
      sibeinsSuccmonthDis: '请输入申报成功月份',
      sibeinsCommentDis: '请输入备注',
    },
    hfundadd: {
      baseTitle: '公积金详细信息',
      subTitle: '公积金险种明细',
      title1: '报增申报申请',
      title2: '报增申报确认',
      title3: '报增申报结果',
      sihfaBussource: '业务来源',
      sihfaBusdesc: '业务简述',
      sihfaEmpgid: '唯一标识号',
      sihfaEmpworkno: '员工工号',
      sihfaCname: '中文名',
      sihfaEmptype: '员工类型',
      sihfaLastname: 'Last Name',
      sihfaFirstname: 'First Name',
      sihfaIdtype: '证件类型',
      sihfaIdno: '证件号码',
      sihfaCompany: '公司',
      sihfaDept: '部门',
      sihfaHfundlocation: '公积金缴纳地',
      sihfaEntrydate: '入职日期',
      sihfaHfundpolicy: '公积金政策',
      sihfaHfundttype: '公积金开户类别',
      sihfaStatus: '状态',
      sihfaApplicant: '申请人',
      sihfaApplytime: '申请时间',
      sihfaConfirmer: '确认人',
      sihfaConfirmtime: '确认时间',
      sihfaConfirmrecord: '确认记录',
      sihfaIsconfirm: '是否确认',
      sihfaNocmreason: '未确认原因',
      sihfaSbperson: '申报人',
      sihfaSbtime: '申报时间',
      sihfaSberror: '申报失败原因',
      sihfaSbrecord: '申报记录',
      sihfaComment: '备注',
      // --
      sihfaBussourceDis: '请选择业务来源',
      sihfaBusdescDis: '请输入业务简述',
      sihfaEmpgidDis: '请输入唯一标识号',
      sihfaEmpworknoDis: '请输入员工工号',
      sihfaCnameDis: '请输入中文名',
      sihfaEmptypeDis: '请选择员工类型',
      sihfaLastnameDis: '请输入Last Name',
      sihfaFirstnameDis: '请输入First Name',
      sihfaIdtypeDis: '请选择证件类型',
      sihfaIdnoDis: '请输入证件号码',
      sihfaCompanyDis: '请选择公司',
      sihfaDeptDis: '请选择部门',
      sihfaHfundlocationDis: '请选择公积金缴纳地',
      sihfaEntrydateDis: '请选择入职日期',
      sihfaHfundpolicyDis: '请选择公积金政策',
      sihfaHfundttypeDis: '请选择公积金开户类别',
      sihfaStatusDis: '请选择状态',
      sihfaApplicantDis: '请选择申请人',
      sihfaApplytimeDis: '请选择申请时间',
      sihfaConfirmerDis: '请选择确认人',
      sihfaConfirmtimeDis: '请选择确认时间',
      sihfaConfirmrecordDis: '暂未提交,没有确认记录!',
      sihfaIsconfirmDis: '请选择是否确认',
      sihfaNocmreasonDis: '请输入未确认原因',
      sihfaSbpersonDis: '请选择申报人',
      sihfaSbtimeDis: '请选择申报时间',
      sihfaSberrorDis: '请输入申报失败原因',
      sihfaSbrecordDis: '请输入申报记录',
      sihfaCommentDis: '请输入备注',
      // --
      sihfaReminder1: '您有数据未初始化，请先初始化!',
      sihfaReminder2: '已申报，不能重复申报!',
      // button
      declareSucc: '申报成功',
      declareFair: '申报失败',
    },
    hfundaddInsurance: {
      sihfainsInsurance: '险种',
      sihfainsBaseamt: '基数',
      sihfainsCompratio: '公司缴纳比例(%)',
      sihfainsCompamt: '公司缴纳金额',
      sihfainsPersratio: '个人缴纳比例(%)',
      sihfainsPersamt: '个人缴纳金额',
      sihfaEntrydate: '入职日期',
      sihfainsApplymonth: '申请报增月份',
      sihfainsSuccmonth: '报增成功月份',
      sihfainsComment: '备注',
      // --
      sihfainsInsuranceDis: '请选择险种',
      sihfainsBaseamtDis: '请输入基数',
      sihfainsCompratioDis: '请输入公司缴纳比例(%)',
      sihfainsCompamtDis: '请输入公司缴纳金额',
      sihfainsPersratioDis: '请输入个人缴纳比例(%)',
      sihfainsPersamtDis: '请输入个人缴纳金额',
      sihfaEntrydateDis: '请选择入职日期',
      sihfainsApplymonthDis: '请选择申请报增月份',
      sihfainsSuccmonthDis: '请选择报增成功月份',
      sihfainsCommentDis: '请输入备注',
    },
    hfundend: {
      baseTitle: '公积金详细信息',
      subTitle: '公积金险种明细',
      title1: '报减申报申请',
      title2: '报减申报确认',
      title3: '报减申报结果',
      sihfeBussource: '业务来源',
      sihfeBusdesc: '业务简述',
      sihfeEmpgid: '唯一标识号',
      sihfeEmpworkno: '员工工号',
      sihfeCname: '中文名',
      sihfeEmptype: '员工类型',
      sihfeLastname: 'Last Name',
      sihfeFirstname: 'First Name',
      sihfeIdtype: '证件类型',
      sihfeIdno: '证件号码',
      sihfeCompany: '公司',
      sihfeDept: '部门',
      sihfeHfundlocation: '公积金缴纳地',
      sihfeLastemployday: '最后雇佣日期',
      sihfeHfundpolicy: '公积金政策',
      sihfeHfundtype: '公积金开户类别',
      sihfeApplicant: '申请人',
      sihfeApplytime: '申请时间',
      sihfeIsconfirm: '是否确认',
      sihfeNocmreason: '未确认原因',
      sihfeConfirmer: '确认人',
      sihfeConfirmtime: '确认时间',
      sihfeConfirmrecord: '确认记录',
      sihfeSbperson: '申报人',
      sihfeSbtime: '申报时间	',
      sihfeStatus: '状态',
      sihfeSberror: '申报失败原因',
      sihfeSbrecord: '申报记录',
      sihfeComment: '备注',
      // --
      sihfeBussourceDis: '请选择业务来源',
      sihfeBusdescDis: '请输入业务简述',
      sihfeEmpgidDis: '请输入唯一标识号',
      sihfeEmpworknoDis: '请输入员工工号',
      sihfeCnameDis: '请输入中文名',
      sihfeEmptypeDis: '请选择员工类型',
      sihfeLastnameDis: '请输入Last Name',
      sihfeFirstnameDis: '请输入First Name',
      sihfeIdtypeDis: '请选择证件类型',
      sihfeIdnoDis: '请输入证件号码',
      sihfeCompanyDis: '请选择公司',
      sihfeDeptDis: '请选择部门',
      sihfeHfundlocationDis: '请选择公积金缴纳地',
      sihfeLastemploydayDis: '请选择最后雇佣日期',
      sihfeHfundpolicyDis: '请选择公积金政策',
      sihfeHfundtypeDis: '请选择公积金开户类别',
      sihfeApplicantDis: '请选择申请人',
      sihfeApplytimeDis: '请选择申请时间',
      sihfeIsconfirmDis: '请选择是否确认',
      sihfeNocmreasonDis: '请输入未确认原因',
      sihfeConfirmerDis: '请选择确认人',
      sihfeConfirmtimeDis: '请选择确认时间',
      sihfeConfirmrecordDis: '暂未提交,没有确认记录!',
      sihfeSbpersonDis: '请选择申报人',
      sihfeSbtimeDis: '请选择申报时间	',
      sihfeStatusDis: '请选择状态',
      sihfeSberrorDis: '请输入申报失败原因',
      sihfeSbrecordDis: '请输入申报记录',
      sihfeCommentDis: '请输入备注',
      // --
      sihfeReminder1: '您有数据未初始化，请先初始化!',
      sihfeReminder2: '已申报，不能重复申报!',
      // button
      declareSucc: '申报成功',
      declareFair: '申报失败',
    },
    hfundendInsurance: {
      sihfeinsInsurance: '险种',
      sihfeinsBaseamt: '基数',
      sihfeinsCompratio: '公司缴纳比例(%)',
      sihfeinsCompamt: '公司缴纳金额',
      sihfeinsPersratio: '个人缴纳比例(%)',
      sihfeinsPersamt: '个人缴纳金额',
      sihfeLastemployday: '最后雇佣日期',
      sihfeinsApplymonth: '申请报减月份',
      sihfeinsSuccmonth: '报减成功月份',
      sihfeinsComment: '备注',
      // --
      sihfeinsInsuranceDis: '请选择险种',
      sihfeinsBaseamtDis: '请输入基数',
      sihfeinsCompratioDis: '请输入公司缴纳比例(%)',
      sihfeinsCompamtDis: '请输入公司缴纳金额',
      sihfeinsPersratioDis: '请输入个人缴纳比例(%)',
      sihfeinsPersamtDis: '请输入个人缴纳金额',
      sihfeLastemploydayDis: '请选择最后雇佣日期',
      sihfeinsApplymonthDis: '请选择申请报减月份',
      sihfeinsSuccmonthDis: '请选择报减成功月份',
      sihfeinsCommentDis: '请输入备注',
    },
  },
  'en-US': {
    sihtPolicy: {
      title: 'Social Security Policy Management',
      sihfpcyNo: 'Policy Number',
      sihfpcyCn: 'Policy Chinese Name',
      sihfpcyEn: 'Policy English Name',
      sihfpcyAreaName: 'Distract',
      sihfpcyRegisterpropertyName: 'Nature Of Residence',
      sihfpcyScopedesc: 'Policy Trial Instructions',
      sihfpcyNewdate: 'Date Added',
      sihfpcyCutdate: 'Date Of Deduction',
      sihfpcySamebaseName: 'Is Cardinality Same?',
      sihfpcySdate: 'Start Date',
      sihfpcyEdate: 'End Date',
      sihfpcyComment: 'Comment',
      sihfpcyNoDis: 'Please enter the policy number',
      sihfpcyCnDis: 'Please enter the policy name Chinese',
      sihfpcyEnDis: 'Please enter the English name of the policy',
      sihfpcyAreaNameDis: 'Please select your region',
      sihfpcyScopedescDis: 'Please enter policy instructions...',
      sihfpcyNewdateDis: 'Date added',
      sihfpcyCutdateDis: 'Date of deduction',
      sihfpcySamebaseNameDis: 'Choose whether the base is the same',
      sihfpcySdateDis: 'Select start date',
      sihfpcyEdateDis: 'Select end date',
      sihfpcyCommentDis: 'Please enter comment...',
    },
    sihtPlcyinsurance: {
      title: 'Social Security Policy',
      sihfpcyinsPolicyName: 'Social security policy',
      sihfpcyinsOrder: 'No.',
      sihfpcyinsInsName: 'Insurance',
      sihfpcyinsHfPolicyName: 'Provident fund policy',
      sihfpcyinsCbll: 'Company minimum base payment',
      sihfpcyinsCbul: 'Company payment base limit',
      sihfpcyinsPbll: 'Personal payment base minimum',
      sihfpcyinsPbul: 'Personal payment base cap',
      sihfpcyinsCrtypeName: 'Company proportion category',
      sihfpcyinsCr: 'Company proportion',
      sihfpcyinsCrll: 'Company Lower Limit',
      sihfpcyinsCrul: 'Company Upper Limit',
      sihfpcyinsPrtypeName: 'Personal proportion category',
      sihfpcyinsPr: 'Personal proportion',
      sihfpcyinsPrll: 'Personal proportion',
      sihfpcyinsPrul: 'Personal proportion cap',
      sihfpcyinsCall: 'Monthly limit of company monthly payment',
      sihfpcyinsCaul: 'Monthly limit of company payment',
      sihfpcyinsPall: 'Monthly personal payment limit',
      sihfpcyinsPaul: 'Monthly personal payment limit',
      sihfpcyinsCarullName: 'Corporate payment calculation rules',
      sihfpcyinsParullName: 'Personal payment calculation rules',
      sihfpcyinsCaa: 'Corporate additional amount',
      sihfpcyinsPaa: 'Personal additional amount',
      sihfpcyinsFrequency: 'Payment frequency',
      sihfpcyinsComment: 'Comment',
      sihfpcyinsOrderDis: 'Please enter NO.',
      sihfpcyinsInsNameDis: 'Please choose insurance',
      sihfpcyinsCbllDis: 'Please enter the lower limit of company payment base',
      sihfpcyinsCbulDis: 'Please enter the company payment base limit',
      sihfpcyinsPbllDis: 'Please enter the personal payment base minimum',
      sihfpcyinsPbulDis: 'Please enter the personal payment base limit',
      sihfpcyinsCrtypeNameDis: 'Select company ratio category',
      sihfpcyinsCrDis: 'Please enter company proportion',
      sihfpcyinsCrllDis: 'Please enter the company lower limit of 111',
      sihfpcyinsCrulDis: 'Please enter the company percentage limit 111',
      sihfpcyinsPrtypeNameDis: 'Select personal proportion category',
      sihfpcyinsPrDis: 'Please enter personal proportion',
      sihfpcyinsPrllDis: 'Please enter the minimum personal proportion',
      sihfpcyinsPrulDis: 'Please enter the maximum personal proportion',
      sihfpcyinsCallDis: 'Please enter the monthly limit of company payment',
      sihfpcyinsCaulDis: 'Please enter the monthly company payment limit',
      sihfpcyinsPallDis: 'Please enter the monthly personal payment limit',
      sihfpcyinsPaulDis: 'Please enter the monthly personal payment limit',
      sihfpcyinsCarullNameDis: 'Select enterprise payment calculation rules',
      sihfpcyinsParullNameDis: 'Select personal payment calculation rules',
      sihfpcyinsCaaDis: 'Please enter company additional amount',
      sihfpcyinsPaaDis: 'Please enter personal additional amount',
      sihfpcyinsFrequencyDis: 'Please enter payment frequency',
      sihfpcyinsCommentDis: 'Please enter comment...',
    },
    sihfBenefitadd: {
      baseTitle: 'The main table of benefitAdd',
      subTitle: 'The insurance details of benefitAdd',
      title1: 'The benefitAdd application',
      title2: 'The benefitAdd confirm',
      title3: 'The benefitAdd result',
      sibaBussource: 'Source of business',
      sibaBusdesc: 'Business is briefly',
      sibaEmpgid: 'Unique code',
      sibaEmpworkno: 'Employee number',
      sibaCname: 'Chinese name',
      sibaEmptype: 'Employee type',
      sibaLastname: 'The Last Name',
      sibaFirstname: 'First Name',
      sibaIdtype: 'ID type',
      sibaIdno: 'I.d.',
      sibaCompany: 'Company',
      sibaDept: 'Department',
      sibaBenefitlocation: 'Social payment',
      sibaEntrydate: 'Date of entry',
      sibaBenefitpolicy: 'Social policy',
      sibaBenefittype: 'Benefit Type',
      sibaApplicant: 'Applicant',
      sibaApplytime: 'Application time',
      sibaIsconfirm: 'Is Confirm?',
      sibaNocmreason: 'No Confirm Reason',
      sibaConfirmer: 'Confirmor',
      sibaConfirmtime: 'Confirm time',
      sibaConfirmrecord: 'Confirm record',
      sibaSbperson: 'Reporter',
      sibaSbtime: 'Report time',
      sibaStatus: 'Status',
      sibaSberror: 'Cause of failure',
      sibaSbrecord: 'Declaration record',
      sibaComment: 'Comment',
      isOrnot: 'confirm data',
      notInit: 'You have not confirmed the data, please confirm!',
      isTrue: 'Confirm whether the currently selected data is all confirmed',
      isDeclare: 'Please confirm the declaration? ',
      isDeclareSuccess: 'Please confirm the successful application？',
      declareErr: 'Declared, can\'t repeat declaration!',
      sibaNocmreasonIns: 'Please enter the reason for unconfirmed',
      sibaIsconfirmIns: 'Please choose whether to confirm',
      yes: 'yes',
      no: 'No',
      // --
      sibaBussourceDis: 'Please select a business source',
      sibaBusdescDis: 'Please enter a business brief',
      sibaEmpgidDis: 'Please enter a unique identification number',
      sibaEmpworknoDis: 'Please enter the employee number',
      sibaCnameDis: 'Please enter a Chinese name',
      sibaEmptypeDis: 'Please select employee type',
      sibaLastnameDis: 'Please enter Last Name',
      sibaFirstnameDis: 'Please enter First Name',
      sibaIdtypeDis: 'Please select the ID type',
      sibaIdnoDis: 'Please enter the ID number',
      sibaCompanyDis: 'Please select a company',
      sibaDeptDis: 'Please select a department',
      sibaBenefitlocationDis: 'Please choose social security payment place',
      sibaEntrydateDis: 'Please select the entry date',
      sibaBenefitpolicyDis: 'Please choose social security policy',
      sibaBenefittypeDis: 'Please select the social security account opening category',
      sibaApplicantDis: 'Please select an applicant',
      sibaApplytimeDis: 'Please select the application time',
      sibaIsconfirmDis: 'Please choose whether to confirm',
      sibaNocmreasonDis: 'Please enter the reason for unconfirmed',
      sibaConfirmerDis: 'Please select a confirmer',
      sibaConfirmtimeDis: 'Please select confirmation time',
      sibaConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      sibaSbpersonDis: 'Please select the applicant',
      sibaSbtimeDis: 'Please select the declaration time',
      sibaStatusDis: 'Please select a status',
      sibaSberrorDis: 'Please enter the reason for the failure of the declaration',
      sibaSbrecordDis: 'Please enter the declaration record',
      sibaCommentDis: 'Please enter comment',
      // --
      sibaReminder1: 'You have data not initialized, please initialize first!',
      // button
      declareSucc: 'Declaration Successful',
      declareFair: 'Declaration failure',
    },
    benefitaddInsurance: {
      sibainsInsurance: 'Insurance',
      sibainsBaseamt: 'Cardinal number',
      sibainsCompratio: 'Company payment ratio (%)',
      sibainsCompamt: 'Company payment amount',
      sibainsPersratio: 'Individual contribution ratio (%)',
      sibainsPersamt: 'Individual contribution amount',
      sibaEntrydate: 'Date of entry',
      sibainsApplymonth: 'Application for increase in month',
      sibainsSuccmonth: 'Successful declaration month',
      sibainsComment: 'Remarks',
      sibainsInsuranceDis: 'Please choose insurance',
      sibainsBaseamtDis: 'Please enter the payment base',
      sibainsCompratioDis: 'Please enter the company\'s payment ratio',
      sibainsCompamtDis: 'Please enter the company\'s payment amount',
      sibainsPersratioDis: 'Please enter the personal contribution ratio',
      sibainsPersamtDis: 'Please enter the amount of personal payment',
      sibaEntrydateDis: 'Please select the entry date',
      sibainsApplymonthDis: 'Please enter the application registration month',
      sibainsCommentDis: 'Please enter a note',
    },
    sihfBenefitend: {
      baseTitle: 'The main table of benefitEnd',
      subTitle: 'The insurance details of benefitEnd',
      title1: 'The benefitEnd application',
      title2: 'The benefitEnd confirm',
      title3: 'The benefitEnd result',
      sibeBussource: 'Source of business',
      sibeBusdesc: 'Business is briefly',
      sibeEmpgid: 'Unique code',
      sibeEmpworkno: 'Employee number',
      sibeCname: 'Chinese name',
      sibeEmptype: 'Employee type',
      sibeLastname: 'The Last Name',
      sibeFirstname: 'First Name',
      sibeIdtype: 'ID type',
      sibeIdno: 'I.d.',
      sibeCompany: 'Company',
      sibeDept: 'Department',
      sibeBenefitlocation: 'Social payment',
      sibeEntrydate: 'Date of entry',
      sibeLastemployday: 'Last hire date',
      sibeBenefitpolicy: 'Social policy',
      sibeBenefittype: 'Benefit Type',
      sibeApplicant: 'Applicant',
      sibeApplytime: 'Application time',
      sibeIsconfirm: 'Is Confirm?',
      sibeNocmreason: 'No Confirm Reason',
      sibeConfirmer: 'Confirmor',
      sibeConfirmtime: 'Confirm time',
      sibeConfirmrecord: 'Confirm record',
      sibeSbperson: 'Reporter',
      sibeSbtime: 'Report time',
      sibeStatus: 'Status',
      sibeSberror: 'Cause of failure',
      sibeSbrecord: 'Declaration record',
      sibeComment: 'Comment',
      // --
      sibeBussourceDis: 'Please select a business source',
      sibeBusdescDis: 'Please enter a business brief',
      sibeEmpgidDis: 'Please enter a unique identification number',
      sibeEmpworknoDis: 'Please enter the employee number',
      sibeCnameDis: 'Please enter a Chinese name',
      sibeEmptypeDis: 'Please select employee type',
      sibeLastnameDis: 'Please enter Last Name',
      sibeFirstnameDis: 'Please enter First Name',
      sibeIdtypeDis: 'Please select the ID type',
      sibeIdnoDis: 'Please enter the ID number',
      sibeCompanyDis: 'Please select a company',
      sibeDeptDis: 'Please select a department',
      sibeBenefitlocationDis: 'Please choose social security payment place',
      sibeEntrydateDis: 'Please select the entry date',
      sibeLastemploydayDis: 'Please select the last hire date',
      sibeBenefitpolicyDis: 'Please choose social security policy',
      sibeBenefittypeDis: 'Please select the social security account opening category',
      sibeApplicantDis: 'Please select an applicant',
      sibeApplytimeDis: 'Please select the application time',
      sibeIsconfirmDis: 'Please choose whether to confirm',
      sibeNocmreasonDis: 'Please enter the reason for unconfirmed',
      sibeConfirmerDis: 'Please select a confirmer',
      sibeConfirmtimeDis: 'Please select confirmation time',
      sibeConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      sibeSbpersonDis: 'Please select the applicant',
      sibeSbtimeDis: 'Please select the declaration time',
      sibeStatusDis: 'Please select a status',
      sibeSberrorDis: 'Please enter the reason for the failure of the declaration',
      sibeSbrecordDis: 'Please enter the declaration record',
      sibeCommentDis: 'Please enter comment',
      // --
      sibeReminder1: 'You have data not initialized, please initialize first!',
      sibeReminder2: 'Has been declared, can not repeat the declaration!',
      // button
      declareSucc: 'Declaration Successful',
      declareFair: 'Declaration failure',
      sibeload: 'To be declared',
    },
    benefitendInsurance: {
      sibeinsInsurance: 'Insurance',
      sibeinsBaseamt: 'Cardinal number',
      sibeinsCompratio: 'Company payment ratio (%)',
      sibeinsCompamt: 'Company payment amount',
      sibeinsPersratio: 'Individual contribution ratio (%)',
      sibeinsPersamt: 'Individual contribution amount',
      sibeEntrydate: 'Date of entry',
      sibeinsApplymonth: 'Application for deduce in month',
      sibeinsSuccmonth: 'Successful declaration month',
      sibeinsComment: 'Remarks',
      sibeinsInsuranceDis: 'Please choose insurance',
      sibeinsBaseamtDis: 'Please enter the payment base',
      sibeinsCompratioDis: 'Please enter the company\'s payment ratio',
      sibeinsCompamtDis: 'Please enter the company\'s payment amount',
      sibeinsPersratioDis: 'Please enter the personal contribution ratio',
      sibeinsPersamtDis: 'Please enter the amount of personal payment',
      sibeEntrydateDis: 'Please select the entry date',
      sibeinsApplymonthDis: 'Please enter the application registration month',
      sibeinsSuccmonthDis: 'Please enter the successful month of the declaration',
      sibeinsCommentDis: 'Please enter a note',
    },
    hfundadd: {
      baseTitle: 'The main table of hfundadd',
      subTitle: 'The insurance details of hfundadd',
      title1: 'The hfundadd application',
      title2: 'The hfundadd confirm',
      title3: 'The hfundadd result',
      sihfaBussource: 'Business source',
      sihfaBusdesc: 'Business brief',
      sihfaEmpgid: 'Unique code',
      sihfaEmpworkno: 'Employee number',
      sihfaCname: 'Chinese name',
      sihfaEmptype: 'Employee type',
      sihfaLastname: 'Last Name',
      sihfaFirstname: 'First Name',
      sihfaIdtype: 'ID Type',
      sihfaIdno: 'I.d.',
      sihfaCompany: 'Company',
      sihfaDept: 'Department',
      sihfaHfundlocation: 'Provident fund payment',
      sihfaEntrydate: 'Date of entry',
      sihfaHfundpolicy: 'Provident fund policy',
      sihfaHfundttype: 'Account category',
      sihfaStatus: 'Status',
      sihfaApplicant: 'Applicant',
      sihfaApplytime: 'Application time',
      sihfaConfirmer: 'Confirmor',
      sihfaConfirmtime: 'confirm time',
      sihfaConfirmrecord: 'Confirmation record',
      sihfaIsconfirm: 'Is confirm?',
      sihfaNocmreason: 'Unconfirmed reason',
      sihfaSbperson: 'Reporter',
      sihfaSbtime: 'Declaration time',
      sihfaSberror: 'Reason for failure',
      sihfaSbrecord: 'Declaration record',
      sihfaComment: 'Comment',
      // --
      sihfaBussourceDis: 'Please select a business source',
      sihfaBusdescDis: 'Please enter a business brief',
      sihfaEmpgidDis: 'Please enter a unique identification number',
      sihfaEmpworknoDis: 'Please enter the employee number',
      sihfaCnameDis: 'Please enter a Chinese name',
      sihfaEmptypeDis: 'Please select employee type',
      sihfaLastnameDis: 'Please enter Last Name',
      sihfaFirstnameDis: 'Please enter First Name',
      sihfaIdtypeDis: 'Please select the ID type',
      sihfaIdnoDis: 'Please enter the ID number',
      sihfaCompanyDis: 'Please select a company',
      sihfaDeptDis: 'Please select a department',
      sihfaHfundlocationDis: 'Please choose the contribution fund',
      sihfaEntrydateDis: 'Please select the entry date',
      sihfaHfundpolicyDis: 'Please choose a provident fund policy',
      sihfaHfundttypeDis: 'Please select the CPF account opening category',
      sihfaStatusDis: 'Please select a status',
      sihfaApplicantDis: 'Please select an applicant',
      sihfaApplytimeDis: 'Please select the application time',
      sihfaConfirmerDis: 'Please select a confirmer',
      sihfaConfirmtimeDis: 'Please select confirmation time',
      sihfaConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      sihfaIsconfirmDis: 'Please choose whether to confirm',
      sihfaNocmreasonDis: 'Please enter the reason for unconfirmed',
      sihfaSbpersonDis: 'Please select the applicant',
      sihfaSbtimeDis: 'Please select the declaration time',
      sihfaSberrorDis: 'Please enter the reason for the failure of the declaration',
      sihfaSbrecordDis: 'Please enter the declaration record',
      sihfaCommentDis: 'Please enter comment',
      // --
      sihfaReminder1: 'You have data not initialized, please initialize first!',
      sihfaReminder2: 'Has been declared, can not repeat the declaration!',
      // button
      declareSucc: 'Declaration Successful',
      declareFair: 'Declaration failure',
    },
    hfundaddInsurance: {
      sihfainsInsurance: 'Insurance',
      sihfainsBaseamt: 'Cardinal number',
      sihfainsCompratio: 'Company payment ratio (%)',
      sihfainsCompamt: 'Company payment amount',
      sihfainsPersratio: 'Individual contribution ratio (%)',
      sihfainsPersamt: 'Individual contribution amount',
      sihfaEntrydate: 'Date of entry',
      sihfainsApplymonth: 'Application for increase in month',
      sihfainsSuccmonth: 'Increased success month',
      sihfainsComment: 'Comment',
      // --
      sihfainsInsuranceDis: 'Please select insurance',
      sihfainsBaseamtDis: 'Please enter the base',
      sihfainsCompratioDis: 'Please enter the company\'s contribution ratio (%)',
      sihfainsCompamtDis: 'Please enter the company\'s payment amount',
      sihfainsPersratioDis: 'Please enter the personal contribution ratio (%)',
      sihfainsPersamtDis: 'Please enter the amount of personal payment',
      sihfaEntrydateDis: 'Please select the entry date',
      sihfainsApplymonthDis: 'Please select the application for the month of increase',
      sihfainsSuccmonthDis: 'Please choose to increase the success month',
      sihfainsCommentDis: 'Please enter comment',
    },
    hfundend: {
      baseTitle: 'The main table of hfundend',
      subTitle: 'The insurance details of hfundend',
      title1: 'The hfundend application',
      title2: 'The hfundend confirm',
      title3: 'The hfundend result',
      sihfeBussource: 'Business source',
      sihfeBusdesc: 'Business brief',
      sihfeEmpgid: 'Unique code',
      sihfeEmpworkno: 'Employee number',
      sihfeCname: 'Chinese name',
      sihfeEmptype: 'Employee type',
      sihfeLastname: 'Last Name',
      sihfeFirstname: 'First Name',
      sihfeIdtype: 'type of certificate',
      sihfeIdno: 'ID number',
      sihfeCompany: 'the company',
      sihfeDept: 'department',
      sihfeHfundlocation: 'Provident fund payment',
      sihfeLastemployday: 'Last hire date',
      sihfeHfundpolicy: 'Provident fund policy',
      sihfeHfundtype: 'Account category',
      sihfeApplicant: 'Applicant',
      sihfeApplytime: 'Application time',
      sihfeIsconfirm: 'Is confirm?',
      sihfeNocmreason: 'Unconfirmed reason',
      sihfeConfirmer: 'Confirmor',
      sihfeConfirmtime: 'confirm time',
      sihfeConfirmrecord: 'Confirmation record',
      sihfeSbperson: 'Reporter',
      sihfeSbtime: 'Declaration time',
      sihfeStatus: 'status',
      sihfeSberror: 'Reason for failure',
      sihfeSbrecord: 'Declaration record',
      sihfeComment: 'Comment',
      // --
      sihfeBussourceDis: 'Please select a business source',
      sihfeBusdescDis: 'Please enter business brief',
      sihfeEmpgidDis: 'Please enter unique code',
      sihfeEmpworknoDis: 'Please enter the employee number',
      sihfeCnameDis: 'Please enter a Chinese name',
      sihfeEmptypeDis: 'Please select employee type',
      sihfeLastnameDis: 'Please enter Last Name',
      sihfeFirstnameDis: 'Please enter First Name',
      sihfeIdtypeDis: 'Please select the ID type',
      sihfeIdnoDis: 'Please enter the ID number',
      sihfeCompanyDis: 'Please select a company',
      sihfeDeptDis: 'Please select a department',
      sihfeHfundlocationDis: 'Please choose the contribution fund',
      sihfeLastemploydayDis: 'Please select the last hire date',
      sihfeHfundpolicyDis: 'Please choose a provident fund policy',
      sihfeHfundtypeDis: 'Please select the CPF account opening category',
      sihfeApplicantDis: 'Please select an applicant',
      sihfeApplytimeDis: 'Please select the application time',
      sihfeIsconfirmDis: 'Please choose whether to confirm',
      sihfeNocmreasonDis: 'Please enter the reason for unconfirmed',
      sihfeConfirmerDis: 'Please select a confirmer',
      sihfeConfirmtimeDis: 'Please select confirmation time',
      sihfeConfirmrecordDis: 'Not submitted yet, no confirmation record!',
      sihfeSbpersonDis: 'Please select the applicant',
      sihfeSbtimeDis: 'Please select the declaration time',
      sihfeStatusDis: 'Please select a status',
      sihfeSberrorDis: 'Please enter the reason for the failure of the declaration',
      sihfeSbrecordDis: 'Please enter the declaration record',
      sihfeCommentDis: 'Please enter comment',
      // --
      sihfeReminder1: 'You have data not initialized, please initialize first!',
      sihfeReminder2: 'Has been declared, can not repeat the declaration!',
      // button
      declareSucc: 'Declaration Successful',
      declareFair: 'Declaration failure',
    },
    hfundendInsurance: {
      sihfeinsInsurance: 'Insurance',
      sihfeinsBaseamt: 'Cardinal number',
      sihfeinsCompratio: 'Company payment ratio (%)',
      sihfeinsCompamt: 'Company payment amount',
      sihfeinsPersratio: 'Individual contribution ratio (%)',
      sihfeinsPersamt: 'Individual contribution amount',
      sihfeLastemployday: 'Last hire date',
      sihfeinsApplymonth: 'Application for deduce in month',
      sihfeinsSuccmonth: 'Deduced success month',
      sihfeinsComment: 'Comment',
      // --
      sihfeinsInsuranceDis: 'Please select insurance',
      sihfeinsBaseamtDis: 'Please enter the base',
      sihfeinsCompratioDis: 'Please enter the company\'s contribution ratio (%)',
      sihfeinsCompamtDis: 'Please enter the company\'s payment amount',
      sihfeinsPersratioDis: 'Please enter the personal contribution ratio (%)',
      sihfeinsPersamtDis: 'Please enter the amount of personal payment',
      sihfeLastemploydayDis: 'Please select the Last hire date',
      sihfeinsApplymonthDis: 'Please select the application for the month of deduce',
      sihfeinsSuccmonthDis: 'Please choose to deduce the success month',
      sihfeinsCommentDis: 'Please enter comment',
    },
  },
}
