export default {
  'zh-CN': {
    sihfCalc: {
      title: '社保核算处理',
      sicalcPeriod: '期间',
      sicalcBfarea: '区域',
      sicalcRound: '轮次',
      sicalcPersttamt: '个人合计',
      sicalcCompttamt: '公司合计',
      sicalcTtamt: '缴纳总计',
      sicalcStatus: '状态',
      sicalcOptrecord: '操作记录',
      sicalcComment: '备注',
      siccempCompany: '公司',
      siccempDept: '部门',
      siccempEmpworkno: '员工工号',
      siccempEmpgid: '唯一标识号',
      siccempCname: '中文名',
      siccempIdtype: '证件类型',
      siccempIdno: '证件号码',
      siccempBflocation: '社保缴纳地',
      siccempBfpolicy: '社保政策',
      siccempBftype: '开户类别',
      siccempPersamt: '社保个人',
      siccempCompamt: '社保公司',
      siccempPersrpamt: '社保个人补缴',
      siccempComprpamt: '社保公司补缴',
      siccempPersajamt: '社保个人调整',
      siccempCompajamt: '社保公司调整',
      siccempPersttamt: '个人合计',
      siccempCompttamt: '公司合计',
      siccempComment: '备注',
      siccinsInsurance: '险种',
      siccinsCalcempid: '核算员工明细ID',
      siccinsCalctype: '缴费类型',
      siccinsBaseamt: '基数',
      siccinsCompratio: '公司缴纳比例(%)',
      siccinsCompamt: '公司缴纳金额',
      siccinsPersratio: '个人缴纳比例(%)',
      siccinsPersamt: '个人缴纳金额',
      siccinsRpmonth: '补缴月份',
      siccinsAjmonth: '调整月份',
      siccinsComment: '备注',
      emptitle: '员工核算明细',
      institle: '员工险种明细',
      btn_count: '核算',
    },
    sihfHfcalc: {
      title: '公积金核算处理',
      emptitle: '员工公积金明细',
      institle: '员工公积金险种',
      sihfcalcPeriod: '期间',
      sihfcalcBfarea: '区域',
      sihfcalcRound: '轮次',
      sihfcalcPersttamt: '个人合计',
      sihfcalcCompttamt: '公司合计',
      sihfcalcTtamt: '缴纳总计',
      sihfcalcStatus: '状态',
      sihfcalcOptrecord: '操作记录',
      sihfcalcComment: '备注',
      sihfccempCompany: '公司',
      sihfccempDept: '部门',
      sihfccempEmpworkno: '员工工号',
      sihfccempEmpgid: '唯一标识号',
      sihfccempCname: '中文名',
      sihfccempIdtype: '证件类型',
      sihfccempIdno: '证件号码',
      sihfccempHflocation: '公积金缴纳地',
      sihfccempHfpolicy: '公积金政策',
      sihfccempHftype: '开户类别',
      sihfccempPersamt: '公积金个人',
      sihfccempCompamt: '公积金公司',
      sihfccempPersrpamt: '公积金个人补缴',
      sihfccempComprpamt: '公积金公司补缴',
      sihfccempPersajamt: '公积金个人调整',
      sihfccempCompajamt: '公积金公司调整',
      sihfccempPersttamt: '个人合计',
      sihfccempCompttamt: ' 公司合计',
      sihfccempComment: '备注',
      sihfccinsInsurance: '险种',
      sihfccinsCalctype: '缴费类型',
      sihfccinsBaseamt: '基数',
      sihfccinsCompratio: '公司缴纳比例(%)',
      sihfccinsCompamt: '公司缴纳金额',
      sihfccinsPersratio: '个人缴纳比例(%)',
      sihfccinsPersamt: '个人缴纳金额',
      sihfccinsRpmonth: '补缴月份',
      sihfccinsAjmonth: '调整月份',
      sihfccinsComment: '备注',
      btn_count: '核算',
    },
  },
  'en-US': {
    sihfCalc: {
      title: 'Social security accounting management',
      sicalcPeriod: 'Period',
      sicalcBfarea: 'region',
      sicalcRound: 'Rotation',
      sicalcPersttamt: 'Individual aggregate',
      sicalcCompttamt: 'Company total',
      sicalcTtamt: 'Pay the total',
      sicalcStatus: 'state',
      sicalcOptrecord: 'Operation record',
      sicalcComment: 'Remarks',
      siccempCompany: 'company',
      siccempDept: 'department',
      siccempEmpworkno: 'Employee number',
      siccempEmpgid: 'Unique identification number',
      siccempCname: 'Chinese name',
      siccempIdtype: 'Document type',
      siccempIdno: 'Identification Number',
      siccempBflocation: 'Social security payment place',
      siccempBfpolicy: 'Social security policy',
      siccempBftype: 'Open account category',
      siccempPersamt: 'Social security individual',
      siccempCompamt: 'Social security company',
      siccempPersrpamt: 'Personal payment of social security',
      siccempComprpamt: 'Social security companies pay back',
      siccempPersajamt: 'Personal adjustment of social security',
      siccempCompajamt: 'Social security company adjustment',
      siccempPersttamt: 'Individual aggregate',
      siccempCompttamt: 'Company total',
      siccempComment: 'Remarks',
      siccinsInsurance: 'Type of insurance',
      siccinsCalcempid: 'Accounting staff details ID',
      siccinsCalctype: 'Payment type',
      siccinsBaseamt: 'base',
      siccinsCompratio: 'Company payment ratio(%)',
      siccinsCompamt: 'Company payment amount',
      siccinsPersratio: 'Personal payment ratio(%)',
      siccinsPersamt: 'Personal payment amount',
      siccinsRpmonth: 'Supplement month',
      siccinsAjmonth: 'Adjustment month',
      siccinsComment: 'Remarks',
      btn_count: 'count',
    },
    sihfHfcalc: {
      title: 'Provident fund accounting management',
      institle: 'Employee accumulation fund insurance',
      emptitle: 'Employee provident fund details',
      sihfcalcPeriod: 'Period',
      sihfcalcBfarea: 'region',
      sihfcalcRound: 'Rotation',
      sihfcalcPersttamt: 'Individual aggregate',
      sihfcalcCompttamt: 'Company total',
      sihfcalcTtamt: 'Pay the total',
      sihfcalcStatus: 'state',
      sihfcalcOptrecord: 'Operation record',
      sihfcalcComment: 'Remarks',
      sihfccempCompany: 'company',
      sihfccempDept: 'department',
      sihfccempEmpworkno: 'Employee number',
      sihfccempEmpgid: 'Unique identification number',
      sihfccempCname: 'Chinese name',
      sihfccempIdtype: 'Document type',
      sihfccempIdno: 'Identification Number',
      sihfccempHflocation: 'Provident fund reserve',
      sihfccempHfpolicy: 'Provident fund policy',
      sihfccempHftype: 'Open account category',
      sihfccempPersamt: 'Social security individual',
      sihfccempCompamt: 'Social security company',
      sihfccempPersrpamt: 'Personal payment of social security',
      sihfccempComprpamt: 'Social security companies pay back',
      sihfccempPersajamt: 'Personal adjustment of social security',
      sihfccempCompajamt: 'Social security company adjustment',
      sihfccempPersttamt: 'Individual aggregate',
      sihfccempCompttamt: ' Company total',
      sihfccempComment: 'Remarks',
      sihfccinsInsurance: 'Type of insurance',
      sihfccinsCalctype: 'Payment type',
      sihfccinsBaseamt: 'base',
      sihfccinsCompratio: 'Company payment ratio(%)',
      sihfccinsCompamt: 'Company payment amount',
      sihfccinsPersratio: 'Personal payment ratio(%)',
      sihfccinsPersamt: 'Personal payment amount',
      sihfccinsRpmonth: 'Supplement month',
      sihfccinsAjmonth: 'Adjustment month',
      sihfccinsComment: 'Remarks',
      btn_count: 'business accounting',
    },
  },
}
