export default {
  'zh-CN': {
    platRolecont: {
      title: '联系人角色管理',
      title2: '联系人角色定义',
      platRolecontCode: '角色编码',
      platRolecontCnname: '角色名称中文',
      platRolecontEnname: '角色名称英文',
      platRolecontDesc: '角色说明',
      platRolecontNotice: '接收通知方式',
      platRolecontPhone: '统一联系电话',
      platRolecontSms: '统一接收消息手机',
      platRolecontUnifiedcn: '统一联系人中文',
      platRolecontUnifieden: '统一联系人英文',
      platRolecontMail: '统一联系邮箱',
      platRolecontVaild: '是否有效',
      platRolecontNote: '备注',
      platRolecontCodeDis: '请输入角色编码',
      platRolecontCnnameDis: '请输入角色名称中文',
      platRolecontEnnameDis: '请输入角色名称英文',
      platRolecontDescDis: '请输入角色说明...',
      platRolecontNoticeDis: '选择接收通知方式',
      platRolecontPhoneDis: '请输入统一联系电话',
      platRolecontSmsDis: '请输入统一接收消息手机',
      platRolecontUnifiedcnDis: '请输入统一联系人中文',
      platRolecontUnifiedenDis: '请输入统一联系人英文',
      platRolecontMailDis: '请输入统一联系邮箱',
      platRolecontVaildDis: '请选择是否有效',
      platRolecontNoteDis: '请输入备注...',
    },
    platRole: {
      title: '联系人角色关联',
      platRolechildType: '联系人类型',
      platRolechildEmpid: '员工',
      platRolechildCnname: '联系人中文',
      platRolechildEnname: '联系人英文',
      platRolechildMail: '联系人邮箱',
      platRolechildTel: '联系人电话',
      platRolechildPhone: '联系人手机',
      platRolechildVailddate: '生效日期',
      platRolechildInvailddate: '失效日期',
      comment: '备注',
      platRolechildTypeDis: '请输入联系人类型',
      platRolechildEmpidDis: '请选择员工',
      platRolechildCnnameDis: '请输入联系人中文',
      platRolechildEnnameDis: '请输入联系人英文',
      platRolechildMailDis: '请输入联系人邮箱',
      platRolechildTelDis: '请输入联系人电话',
      platRolechildPhoneDis: '请输入联系人手机',
      platRolechildVailddateDis: '请选择生效日期',
      platRolechildInvailddateDis: '请选择失效日期',
      commentDis: '请输入备注...',
      searchColumn: {
        title: '业务上级经理',
        empCname: '员工姓名',
        empGid: '员工唯一标识',
      },
    },
    authTodofine: {
      title: '待办事项配置',
      autdNo: '事项编号',
      autdName: '事项名称',
      autdPlatform: '所属平台',
      autdProp: '事项属性',
      autdThread: '事项获取线程',
      autdValid: '是否有效',
      autdInvreason: '失效原因',
      autdComment: '备注',
      autdNoDis: '请输入事项编号',
      autdNameDis: '请输入事项名称',
      autdPlatformDis: '请选择所属平台',
      autdPropDis: '请输入事项属性',
      autdThreadDis: '请输入事项获取线程',
      autdValidDis: '请选择是否有效',
      autdInvreasonDis: '请输入失效原因',
      autdCommentDis: '请输入备注',
    },
  },
  'en-US': {
    platRolecont: {
      title: 'The contact role definition',
      title2: 'Contact role definition',
      platRolecontCode: 'Role Code',
      platRolecontCnname: 'Role Name Chinese',
      platRolecontEnname: 'Role Name English',
      platRolecontDesc: 'Role Description',
      platRolecontNotice: 'Receive Notification Method',
      platRolecontPhone: 'Unified Telephone Number',
      platRolecontSms: 'Uniformly Receiving SMS Mobile Phones',
      platRolecontUnifiedcn: 'Unified Contacts Chinese',
      platRolecontUnifieden: 'Unified contact English',
      platRolecontMail: 'Unified contact email',
      platRolecontVaild: 'Is it effective',
      platRolecontNote: 'comment',
      platRolecontCodeDis: 'Please enter the role code',
      platRolecontCnnameDis: 'Please enter a role name in Chinese',
      platRolecontEnnameDis: 'Please enter the role name in English',
      platRolecontDescDis: 'Please enter the role description...',
      platRolecontNoticeDis: 'Select receive notification method',
      platRolecontPhoneDis: 'Please enter a unified contact number',
      platRolecontSmsDis: 'Please enter unified receive SMS mobile phone',
      platRolecontUnifiedcnDis: 'Please enter a unified contact in Chinese',
      platRolecontUnifiedenDis: 'Please enter a unified contact English',
      platRolecontMailDis: 'Please enter a unified contact email',
      platRolecontVaildDis: 'Please select whether it is valid',
      platRolecontNoteDis: 'Please enter comment...',
    },
    platRole: {
      title: 'Contact Role Definition Sub-table',
      platRolechildType: 'Contact Type',
      platRolechildEmpid: 'Employee',
      platRolechildCnname: 'Contact Chinese',
      platRolechildEnname: 'Contact English',
      platRolechildMail: 'Contact Email',
      platRolechildTel: 'Contact Number',
      platRolechildPhone: 'Contact Telephone',
      platRolechildVailddate: 'Start Date',
      platRolechildInvailddate: 'End Date',
      comment: 'Comment',
      platRolechildTypeDis: 'Please enter contact type',
      platRolechildEmpidDis: 'Please select employees',
      platRolechildCnnameDis: 'Please enter contact chinese',
      platRolechildEnnameDis: 'Please enter contact English',
      platRolechildMailDis: 'Please enter the contact email',
      platRolechildTelDis: 'Please enter contact phone',
      platRolechildPhoneDis: 'Please enter contact phone',
      platRolechildVailddateDis: 'Please select start date',
      platRolechildInvailddateDis: 'Please select end date',
      commentDis: 'Please enter comment...',
      searchColumn: {
        title: 'Business manager',
        empCname: 'Employee Name',
        empGid: 'Employee Gid',
      },
    },
    authTodofine: {
      title: 'To-do configuration',
      autdNo: 'ItemNumber',
      autdName: 'ItemName',
      autdPlatform: 'SubordinatePlatform',
      autdProp: 'ItemProperties',
      autdThread: 'EventFetchThread',
      autdValid: 'IsValid?',
      autdInvreason: 'FailureReason',
      autdComment: 'Comment',
      autdNoDis: 'Please enter the item number',
      autdNameDis: 'Please enter the item name',
      autdPlatformDis: 'Please select your platform',
      autdPropDis: 'Please enter item attributes',
      autdThreadDis: 'Please enter a transaction to get a thread',
      autdValidDis: 'Please select whether it is valid',
      autdInvreasonDis: 'Please enter the cause of failure',
      autdCommentDis: 'Please enter remarks',
    },
  },
}
