import lang_authorization from './lang_authorization'
import lang_baseManage from './lang_baseManage'
import lang_payroll from './lang_payroll'
import lang_fileOperation from './lang_fileOperation'
import lang_platform from './lang_platform'
import lang_organization from  './lang_organization'
import lang_employee from  './lang_employee'
import lang_sihfPolicy from  './lang_sihfPolicy'
import lang_homePage from  './lang_homePage'
import lang_ansrptEmpSihf from  './lang_ansrptEmpSihf'
import lang_repayApply from  './lang_repayApply'
import lang_hfrepay from  './lang_hfrepay'
import lang_sihfCalc from  './lang_sihfCalc'
import lang_search from  './lang_search'
import lang_user from  './lang_user'
import lang_role from  './lang_role'
import lang_cmut from './lang_cmut'
import lang_lan from './lang_lan'
import lang_selfdef from './lang_selfdef'
import lang_platBusirel from './lang_platBusirel'
import lang_platdoc from './lang_platdoc'
import lang_sysform from './lang_sysform'
import lang_communication  from './lang_communication'
import lang_financialMan from './lang_financialMan'
import lang_operatmonitor from './lang_operatmonitor'
import lang_empManage from './lang_empManage'
import lang_evaluation from './lang_evaluation'
import lang_knowBase from './lang_knowBase'
import lang_flow  from './lang_flow'
import lang_personalfile from './lang_personalfile'
import lang_approval from './lang_approval'
import lang_root from './lang_root'

export default {
  'zh-CN': {
    title: '人力资源共享服务平台',
    home: '首页',
    user: {
      userCenter: '个人中心',
      quit: '退出登录',
    },
    pageTab: {
      title: '标签选项',
      keepNow: '关闭其他',
      closeAll: '关闭所有',
    },
    date: {
      week: {
        Sun: '周日',
        Mon: '周一',
        Tue: '周二',
        Wed: '周三',
        Thu: '周四',
        Fri: '周五',
        Sat: '周六',
      },
      month: {
        January: '一月',
        February: '二月',
        March: '三月',
        April: '四月',
        May: '五月',
        June: '六月',
        July: '七月',
        August: '八月',
        September: '九月',
        October: '十月',
        November: '十一月',
        December: '十二月',
      },
    },
    button: {
      add: '新增',
      upd: '修改',
      del: '删除',
      ser: '查询',
      view: '查看',
      imp: '导入',
      exp: '导出',
      opr: '操作',
      sav: '保存',
      cal: '取消',
      cle: '清空',
      cek: '检查',
      det: '明细',
      cop: '复制',
      all: '全部',
      ini: '初始化',
      edi: '编辑',
      gen: '生成',
      clo: '关闭',
      start: '发起',
      eva: '评价',
      ask: '提问',
      brw: '浏览',
      fai: '失效',
      refer: '查阅',
      hdl: '处理',
      eft: '生效',
      enabled: '启用',
      unenabled: '未启用',
      adjOrd: '调整顺序',
      selAll: '全选',
      reset: '重置',
      subm: '提交',
      submConfirm: '提交确认',
      confirm: '确认',
      back: '退回',
      seal: '封账',
      declS: '申报成功',
      declF: '申报失败',
      sealAccount: '封账',
      upl: '上传',
      dwl: '下载',
    },
    status: {
      draft: '编辑中',
      invalid: '失效',
      valid: '生效',
      all: '全部',
      waitupdate: '待更新',
    },
    reminder: {
      remind: '提示',
      err: '错误',
      suc: '成功',
      rig: '正确',
      addsuccess: '新增成功',
      updsuccess: '修改成功',
      savsuccess: '保存成功',
      submitsuccess: '提交成功',
      dataRational: '数据合理',
      isInit: '请确认重新初始化？',
      initSuccess: '初始化成功',
      borrowsuccess: '查阅成功',
      uploadsuccess: '上传成功',
      genersuccess: '生成成功',
      confirmDatasuccess: '确认数据成功',
      isDelete: '是否删除',
      noDelete: '不能删除',
      deletesuccess: '删除成功',
      errormessage: '网络错误',
      nodata: '无数据',
      noErrData: '无错误信息',
      noRightData: '没有符合条件的数据!',
      leastone: '请至少选择一条数据',
      confirmdelete: '请确定删除数据',
      confirmCopy: '请确定复制该条数据',
      confirmSubmit: '请确定提交',
      confirmData: '请先确认该条数据',
      confirmOper: '请确认执行该操作',
      confirmDataCheck1: '您有数据未确认，请先确认!',
      confirmDataCheck2: '您有数据进行否确认操作，或者没有填写未确认原因!',
      exportErr: '导出字段不能为空',
      dataExists: '信息已存在，请修改!',
    },
    lang_authorization: lang_authorization['zh-CN'],
    lang_baseManage: lang_baseManage['zh-CN'],
    lang_payroll: lang_payroll['zh-CN'],
    lang_fileOperation: lang_fileOperation['zh-CN'],
    lang_platform: lang_platform['zh-CN'],
    lang_organization: lang_organization['zh-CN'],
    lang_employee: lang_employee['zh-CN'],
    lang_sihfPolicy: lang_sihfPolicy['zh-CN'],
    lang_homePage: lang_homePage['zh-CN'],
    lang_ansrptEmpSihf: lang_ansrptEmpSihf['zh-CN'],
    lang_repayApply: lang_repayApply['zh-CN'],
    lang_hfrepay: lang_hfrepay['zh-CN'],
    lang_sihfCalc: lang_sihfCalc['zh-CN'],
    lang_search: lang_search['zh-CN'],
    lang_user: lang_user['zh-CN'],
    lang_role: lang_role['zh-CN'],
    lang_cmut: lang_cmut['zh-CN'],
    lang_lan: lang_lan['zh-CN'],
    lang_selfdef: lang_selfdef['zh-CN'],
    lang_platBusirel: lang_platBusirel['zh-CN'],
    lang_platdoc: lang_platdoc['zh-CN'],
    lang_sysform: lang_sysform['zh-CN'],
    lang_communication: lang_communication['zh-CN'],
    lang_financialMan: lang_financialMan['zh-CN'],
    lang_operatmonitor: lang_operatmonitor['zh-CN'],
    lang_empManage: lang_empManage['zh-CN'],
    lang_evaluation: lang_evaluation['zh-CN'],
    lang_knowBase: lang_knowBase['zh-CN'],
    lang_flow: lang_flow['zh-CN'],
    lang_personalfile: lang_personalfile['zh-CN'],
    lang_approval: lang_approval['zh-CN'],
    lang_root: lang_root['zh-CN'],
  },
  'en-US': {
    title: 'Human Resource Sharing Service Platform',
    home: 'Home',
    user: {
      userCenter: 'Personal Center',
      quit: 'Login Out',
    },
    pageTab: {
      title: 'TagOption',
      keepNow: 'Close Rest',
      closeAll: 'Close All',
    },
    date: {
      week: {
        Sun: 'Sun',
        Mon: 'Mon',
        Tue: 'Tue',
        Wed: 'Wed',
        Thu: 'Thu',
        Fri: 'Fri',
        Sat: 'Sat',
      },
      month: {
        January: 'January',
        February: 'February',
        March: 'March',
        April: 'April',
        May: 'May',
        June: 'June',
        July: 'July',
        August: 'August',
        September: 'September',
        October: 'October',
        November: 'November',
        December: 'December',
      },
    },
    button: {
      add: 'Add',
      upd: 'Update',
      del: 'Delete',
      ser: 'Search',
      view: 'View',
      imp: 'Import',
      exp: 'Export',
      opr: 'Operate',
      sav: 'Save',
      cal: 'Cancel',
      cle: 'Clear',
      cek: 'Check',
      cop: 'Copy',
      all: 'All',
      ini: 'Initialize',
      edi: 'Edit',
      gen: 'Generate',
      clo: 'Close',
      start: 'Sponsor',
      eva: 'Evaluate',
      ask: 'Questions',
      brw: 'Brower',
      fai: 'Disable',
      refer: 'Refer',
      hdl: 'Handle',
      det: 'Details',
      eft: 'Effect',
      enabled: 'Enabled',
      unenabled: 'Unenabled',
      adjOrd: 'Adjust Order',
      selAll: 'Select All',
      reset: 'Reset',
      subm: 'Submit',
      submConfirm: 'SubmitConfirm',
      confirm: 'Confirm',
      back: 'Back',
      seal: 'Seal',
      declS: 'Declare Success',
      declF: 'Failure To Declare',
      sealAccount: 'sealAccount',
      upl: 'upload',
      dwl: 'download',
    },
    status: {
      draft: 'Draft',
      invalid: 'Invalid',
      valid: 'Valid',
      all: 'All',
      waitupdate: 'To be updated',
    },

    reminder: {
      remind: 'Remind',
      err: 'Error',
      suc: 'Success',
      rig: 'Right',
      addsuccess: 'Added successfully',
      updsuccess: 'Update successfully',
      savsuccess: 'Saved successfully',
      submitsuccess: 'Submit successfully',
      dataRational: 'Data rational',
      isInit: 'Please confirm reinitialization？',
      initSuccess: 'Initialze successfully',
      borrowsuccess: 'Borrowing successfully',
      uploadsuccess: 'Uploaded successfully',
      genersuccess: 'Generate success',
      confirmDatasuccess: 'Confrim data success',
      isDelete: 'whether delete',
      noDelete: 'Cannot delete',
      deletesuccess: 'Delete success',
      errormessage: 'the network error',
      nodata: 'No data!',
      noErrData: 'No Error Data!',
      noRightData: 'There is no qualifying data!',
      leastone: 'Please select at least one data',
      confirmdelete: 'Please confirm delete this data',
      confirmCopy: 'Please be sure to confirm this data',
      confirmSubmit: 'Please be sure to submit this data',
      confirmData: 'Please confirm this data first',
      confirmOper: 'Please confirm the operation',
      confirmDataCheck1: 'You have data not confirmed, please confirm first!',
      confirmDataCheck2: 'You have data to confirm the operation, or did not fill in the unconfirmed reason!',
      exportErr: 'The export field cannot be empty',
      dataExists: 'The information already exists, please modify!',
    },
    lang_authorization: lang_authorization['en-US'],
    lang_baseManage: lang_baseManage['en-US'],
    lang_payroll: lang_payroll['en-US'],
    lang_fileOperation: lang_fileOperation['en-US'],
    lang_platform: lang_platform['en-US'],
    lang_organization: lang_organization['en-US'],
    lang_employee: lang_employee['en-US'],
    lang_sihfPolicy: lang_sihfPolicy['en-US'],
    lang_homePage: lang_homePage['en-US'],
    lang_ansrptEmpSihf: lang_ansrptEmpSihf['en-US'],
    lang_repayApply: lang_repayApply['en-US'],
    lang_hfrepay: lang_hfrepay['en-US'],
    lang_sihfCalc: lang_sihfCalc['en-US'],
    lang_search: lang_search['en-US'],
    lang_user: lang_user['en-US'],
    lang_role: lang_role['en-US'],
    lang_cmut: lang_cmut['en-US'],
    lang_lan: lang_lan['en-US'],
    lang_selfdef: lang_selfdef['en-US'],
    lang_platBusirel: lang_platBusirel['en-US'],
    lang_platdoc: lang_platdoc['en-US'],
    lang_sysform: lang_sysform['en-US'],
    lang_communication: lang_communication['en-US'],
    lang_financialMan: lang_financialMan['en-US'],
    lang_operatmonitor: lang_operatmonitor['en-US'],
    lang_empManage: lang_empManage['en-US'],
    lang_evaluation: lang_evaluation['en-US'],
    lang_knowBase: lang_knowBase['en-US'],
    lang_flow: lang_flow['en-US'],
    lang_personalfile: lang_personalfile['en-US'],
    lang_approval: lang_approval['en-US'],
    lang_root: lang_root['en-US'],
  },

}
