export default {
  'zh-CN': {
    platapprovallist: {
      title: '审批流程配置',
      aprvCode: '流程编号',
      aprvName: '流程名称',
      aprvStatus: '流程状态',
      aprvFormtype: '表单类型',
      aprvForm: '业务表单',
      aprvVersion: '版本号',
      aprvAfthd: '后置处理类',
      aprvComment: '备注',
      aprvCodeDis: '请输入流程编号',
      aprvNameDis: '请输入流程名称',
      aprvStatusDis: '请选择流程状态',
      aprvFormtypeDis: '请选择表单类型',
      aprvFormDis: '请选择业务表单',
      aprvVersionDis: '请输入版本号',
      aprvAfthdDis: '请输入后置处理类',
      aprvCommentDis: '请输入备注',
      //
      flowConfig: '流程配置',
      oprclosed: '操作完成',
      // searchList
      searchTitle: '系统表单',
      sformName: '表单名称',
      sformTbname: '物理表名',
      searchText: '请输入表单名称',
    },
    platapprovalbase: {
      title1: '流程详细信息',
      title2: '流程表单定义',
      title3: '流程邮件模板',
      title4: '流程短信模板',
      title5: '流程微信模板',
    },
    dataBlock: {
      title: '流程表单配置',
      aprvdbOrder: '序号',
      aprvdbType: '数据块类型',
      aprvdbTitlecn: '中文名称',
      aprvdbTitleen: '英文名称',
      aprvdbDisclms: '字段显示列',
      aprvdbComment: '备注',
      defineField: '字段定义',
      aprvdbOrderDis: '请输入序号',
      aprvdbTypeDis: '请输入数据块类型',
      aprvdbTitlecnDis: '请输入中文名称',
      aprvdbTitleenDis: '请输入英文名称',
      aprvdbDisclmsDis: '请输入字段显示列',
      aprvdbCommentDis: '请输入备注',
      // fieldDefintion
      fieldDeTitle: '表单字段分配',
      txtsize1: '可选择字段',
      txtsize2: '已选择字段',
      sffFieldName: '字段显示名',
      sffLayout: '布局类型',
      aprvdbfdField: '字段显示名',
      layouType: '布局类型',
      aprvdbfdDisdefault: '默认是否显示',
      aprvdbSubformtype: '子集表单类型',
      aprvdbSubform: '子集表单',
      aprvdbSubisupd: '子集是否可修改',
      aprvdbSubfilter: '子集数据过滤',
      p_aprvdbSubformtype: '请选择子集表单类型',
      p_aprvdbSubform: '请选择子集表单',
      p_aprvdbSubfilter: '请输入子集数据过滤',
    },
    mailList: {
      title: '流程邮件配置',
      aprvmlOrder: '序号',
      aprvmlObject: '邮件主题',
      aprvmlContent: '邮件内容',
      aprvmlSendstyle: '发送方式',
      aprvmlIsencrypt: '是否加密发送',
      aprvmlIsvalid: '是否有效',
      aprvmlInvreason: '失效原因',
      aprvmlReciever: '接收人',
      aprvmlCC: '抄送人',
      action: '配置接收人和抄送人',
      variab: '变量',
      aprvmlComment: '备注',
      aprvmlOrderDis: '请输入序号',
      aprvmlObjectDis: '请输入邮件主题',
      aprvmlContentDis: '请输入内容',
      aprvmlSendstyleDis: '请选择发送方式',
      aprvmlInvreasonDis: '请输入失效原因',
      aprvmlCommentDis: '请输入备注',
    },
    contract: {
      title: '邮件联系人',
      apmltoContact: '联系人',
      apmltoIsvalid: '是否有效',
      upsTitle: '联系人权限',
      apmltoCondition: '发送条件',
      apmltoConditionDis: '请设置发送条件',
      conditionSetting: '条件设置',
      contactMark: '联系人标识',
      contactName: '标识名称',
    },
    var: {
      title: '邮件变量',
      updTitle: '邮件变量配置',
      aprvarMark: '变量标识',
      aprvarName: '变量名称',
      aprvarMarkDis: '请输入变量标识',
    },
    smsList: {
      title: '流程短信配置',
      aprvsmsOrder: '序号',
      aprvsmsObject: '短信主题',
      aprvsmsContent: '短信内容',
      aprvsmsSendstyle: '发送方式',
      aprvsmsIsencrypt: '是否加密发送',
      aprvsmsIsvalid: '是否有效',
      aprvsmsInvreason: '失效原因',
      aprvsmsReciever: '接收人',
      aprvsmsCC: '抄送人',
      action: '配置接收人',
      variab: '变量',
      aprvsmsComment: '备注',
      aprvsmsOrderDis: '请输入序号',
      aprvsmsObjectDis: '请输入短信主题',
      aprvsmsContentDis: '请输入内容',
      aprvsmsSendstyleDis: '请选择发送方式',
      aprvsmsInvreasonDis: '请输入失效原因',
      aprvsmsCommentDis: '请输入备注',
    },
    smscontract: {
      title: '短信联系人',
      apsmstoContact: '联系人',
      apsmstoIsvalid: '是否有效',
      upsmsitle: '联系人权限',
      apsmstoCondition: '发送条件',
      apsmstoConditionDis: '请设置发送条件',
      conditionSetting: '条件设置',
      contactMark: '联系人标识',
      contactName: '标识名称',
    },
    smsvar: {
      title: '短信变量',
      updTitle: '短信变量配置',
      aprvarMark: '变量标识',
      aprvarName: '变量名称',
      aprvarMarkDis: '请输入变量标识',
    },
    wxList: {
      title: '流程配置',
      aprvwxOrder: '序号',
      aprvwxObject: '微信主题',
      aprvwxContent: '微信内容',
      aprvwxTitle: '微信标题',
      aprvwxLink: '微信链接',
      aprvwxType: '消息类型',
      aprvwxSendstyle: '发送方式',
      aprvwxIsencrypt: '是否加密发送',
      aprvwxIsvalid: '是否有效',
      aprvwxInvreason: '失效原因',
      aprvwxReciever: '接收人',
      aprvwxCC: '抄送人',
      action: '配置接收人',
      variab: '变量',
      aprvwxComment: '备注',
      aprvwxOrderDis: '请输入序号',
      aprvwxObjectDis: '请输入微信主题',
      aprvwxContentDis: '请输入内容',
      aprvwxTitleDis: '请输入微信标题',
      aprvwxLinkDis: '请输入微信链接',
      aprvwxSendstyleDis: '请选择发送方式',
      aprvwxInvreasonDis: '请输入失效原因',
      aprvwxCommentDis: '请输入备注',
    },
    wxcontract: {
      title: '微信联系人',
      apwxtoContact: '联系人',
      apwxtoIsvalid: '是否有效',
      upwxitle: '联系人权限',
      apwxtoCondition: '发送条件',
      apwxtoConditionDis: '请设置发送条件',
      conditionSetting: '条件设置',
      contactMark: '联系人标识',
      contactName: '标识名称',
    },
    wxvar: {
      title: '微信变量',
      updTitle: '微信变量配置',
      aprvarMark: '变量标识',
      aprvarName: '变量名称',
      aprvarMarkDis: '请输入变量标识',
    },
  },
  'en-US': {
    platapprovallist:{
      title: 'Approval process configuration',
      aprvCode: 'ApprovalCode',
      aprvName: 'ApprovalName',
      aprvStatus: 'Status',
      aprvFormtype: 'FormType',
      aprvForm: 'BusinessForm',
      aprvVersion: 'Version',
      aprvAfthd: 'AfterClass',
      aprvComment: 'Comment',
      aprvCodeDis: 'Please enter the approval code',
      aprvNameDis: 'Please enter the approval name',
      aprvStatusDis: 'Select the status',
      aprvFormtypeDis: 'Please select the form type',
      aprvFormDis: 'Select the business form',
      aprvVersionDis: 'Please enter the version number',
      aprvAfthdDis: 'Please enter the after class',
      aprvCommentDis: 'Please enter remarks',
      //
      flowConfig: 'Config',
      oprclosed: 'Operation is completed',
      // searchList
      searchTitle: 'SystemForm',
      sformName: 'FormName',
      sformTbname: 'TableName',
      searchText: 'Please enter the form name',
    },
    platapprovalbase: {
      title1: 'Flow details',
      title2: 'Flow form definition',
      title3: 'Flow mail template',
      title4: 'Flow sms template',
      title5: 'Flow wechat template',
    },
    dataBlock: {
      title: 'Systemform configuration',
      aprvdbOrder: 'Order',
      aprvdbType: 'DatablockType',
      aprvdbTitlecn: 'ChineseName',
      aprvdbTitleen: 'EnglishNames',
      aprvdbDisclms: 'DisplayColumn',
      aprvdbComment: 'Comment',
      defineField: 'FieldDefinition',
      aprvdbOrderDis: 'Please enter the serial number',
      aprvdbTypeDis: 'Please enter the data block type',
      aprvdbTitlecnDis: 'Please enter a Chinese name',
      aprvdbTitleenDis: 'Please enter English name',
      aprvdbDisclmsDis: 'Please enter the field to display the column',
      aprvdbCommentDis: 'Please enter remarks',
      // fieldDefintion
      fieldDeTitle: 'FormField assignment',
      txtsize1: 'Optional Field',
      txtsize2: 'Selected Field',
      sffFieldName: 'FieldDisplayName',
      sffLayout: 'LayoutType',
      aprvdbfdField: 'FieldDisplayName',
      layouType: 'LayoutType',
      aprvdbfdDisdefault: 'Is Display?',
      aprvdbSubformtype: 'subset form type',
      aprvdbSubform: 'subset form',
      aprvdbSubisupd: 'Is the subset editable',
      aprvdbSubfilter: 'subset data filtering',
      p_aprvdbSubformtype: 'Please select the subset form type',
      p_aprvdbSubform: 'Please select a subset form',
      p_aprvdbSubfilter: 'Please enter subset data filtering',
    },
    mailList: {
      title: 'Flow mail configuration',
      aprvmlOrder: 'OrderNumber',
      aprvmlObject: 'EmailSubject',
      aprvmlContent: 'EmailContent',
      aprvmlSendstyle: 'SendType',
      aprvmlIsencrypt: 'Is encrypted?',
      aprvmlIsvalid: 'Isvalid?',
      aprvmlInvreason: 'InversionReason',
      aprvmlReciever: 'Recipient',
      aprvmlCC: 'Ccpeople',
      action: 'ConfigureReceiverandcc',
      variab: 'Variable',
      aprvmlComment: 'Comment',
      aprvmlOrderDis: 'Please enter the order number',
      aprvmlObjectDis: 'Please enter mail subject',
      aprvmlContentDis: 'Please enter content',
      aprvmlSendstyleDis: 'Please select the sending method',
      aprvmlInvreasonDis: 'Please enter the reason of invaild',
      aprvmlCommentDis: 'Please enter comment',
    },
    contract: {
      title: 'EmailContact',
      apmltoContact: 'Contact',
      apmltoIsvalid: 'Is Valid?',
      upsTitle: 'ContactPermissions',
      apmltoCondition: 'SendCondition',
      apmltoConditionDis: 'Please set the send condition',
      conditionSetting: 'Setcondition',
      contactMark: 'ContractMark',
      contactName: 'MarkName',
    },
    var: {
      title: 'EmailVariable',
      updTitle: 'Mail variable configuration',
      aprvarMark: 'VariablesIdentify',
      aprvarName: 'VariablesName',
      aprvarMarkDis: 'Please enter the variable id',
    },
    smsList: {
      title: 'Flow sms configuration',
      aprvsmsOrder: 'OrderNumber',
      aprvsmsObject: 'SmsSubject',
      aprvsmsContent: 'SmsContent',
      aprvsmsSendstyle: 'SendType',
      aprvsmsIsencrypt: 'Is encrypted?',
      aprvsmsIsvalid: 'Isvalid?',
      aprvsmsInvreason: 'InversionReason',
      aprvsmsReciever: 'Recipient',
      aprvsmsCC: 'Ccpeople',
      action: 'ConfigureReceiver',
      variab: 'Variable',
      aprvsmsComment: 'Comment',
      aprvsmsOrderDis: 'Please enter the order number',
      aprvsmsObjectDis: 'Please enter sms subject',
      aprvsmsContentDis: 'Please enter content',
      aprvsmsSendstyleDis: 'Please select the sending method',
      aprvsmsInvreasonDis: 'Please enter the reason of invaild',
      aprvsmsCommentDis: 'Please enter comment',
    },
    smscontract: {
      title: 'SmsContact',
      apsmstoContact: 'Contact',
      apsmstoIsvalid: 'Is Valid?',
      upsmsitle: 'ContactPermissions',
      apsmstoCondition: 'SendCondition',
      apsmstoConditionDis: 'Please set the send condition',
      conditionSetting: 'Setcondition',
      contactMark: 'ContractMark',
      contactName: 'MarkName',
    },
    smsvar: {
      title: 'SMS variable',
      updTitle: 'SMS variable configuration',
      aprvarMark: 'VariablesIdentify',
      aprvarName: 'VariableName',
      aprvarMarkDis: 'Please enter the variables identify ',
    },
    wxList: {
      title: 'Flow wechat configuration',
      aprvwxOrder: 'OrderNumber',
      aprvwxObject: 'WechatSubject',
      aprvwxContent: 'WechatContent',
      aprvwxType: 'MessageType',
      aprvwxSendstyle: 'SendType',
      aprvwxTitle: 'WeChattitle',
      aprvwxLink: 'WeChatlink',
      aprvwxIsencrypt: 'Is encrypted?',
      aprvwxIsvalid: 'Isvalid?',
      aprvwxInvreason: 'InversionReason',
      aprvwxReciever: 'Recipient',
      aprvwxCC: 'Ccpeople',
      action: 'ConfigureReceiverandcc',
      variab: 'Variable',
      aprvwxComment: 'Comment',
      aprvwxOrderDis: 'Please enter the order number',
      aprvwxObjectDis: 'Please enter Wechat subject',
      aprvwxContentDis: 'Please enter content',
      aprvwxTitleDis: 'Please enter the WeChat title',
      aprvwxLinkDis: 'Please enter the WeChat link',
      aprvwxSendstyleDis: 'Please select the sending method',
      aprvwxInvreasonDis: 'Please enter the reason of invaild',
      aprvwxCommentDis: 'Please enter comment',
    },
    wxcontract: {
      title: 'WechatContact',
      apwxtoContact: 'Contact',
      apwxtoIsvalid: 'Is Valid?',
      upwxitle: 'ContactPermissions',
      apwxtoCondition: 'SendCondition',
      apwxtoConditionDis: 'Please set the send condition',
      conditionSetting: 'Setcondition',
      contactMark: 'ContractMark',
      contactName: 'MarkName',
    },
    wxvar: {
      title: 'Wechat variable',
      updTitle: 'Wechat variable configuration',
      aprvarMark: 'VariablesIdentify',
      aprvarName: 'VariableName',
      aprvarMarkDis: 'Please enter the variables identify ',
    },
  },
}
