export default {
  'zh-CN': {
    orgframe: {
      title: '组织信息管理',
      title1: '集团信息管理',
      unitCode: '组织编码',
      unitCode1: '公司编码',
      compFnameCnDis: '公司全称',
      compSnameCnDis: '公司简称',
      compFnameEnDis: '公司全称',
      compSnameEnDis: '公司简称',
      compCOrEName: '公司全称',
      unitTypeName: '组织类型',
      unitPname: '所属上级',
      validdate: '生效日期',
      invdate: '失效日期',
      unitAgentno: '纳税人识别号',
      unitDfcostcenter: '默认成本中心',
      unitDfhirecity: '默认雇佣地点',
      unitDfworkcity: '默认工作地点',
      invreason: '失效原因',
      orgList: '选择组织',
      comment: '备注',
      reminderErr: '部门节点下组织类型不能为公司',
      unitCodeInp: '请输入组织编码',
      unitCodeInp1: '请输入公司编码',
      compFnameCnDisInp: '请输入公司全称',
      compSnameCnDisInp: '请输入公司简称',
      compFnameEnDisInp: '请输入公司全称',
      compSnameEnDisInp: '请输入公司简称',
      compCOrENameInp: '请输入公司全称',
      unitTypeNameInp: '选择类型',
      unitPnameInp: '请选择上级组织',
      validdateInp: '选择生效日期',
      invdateInp: '选择失效日期',
      unitAgentnoInp: '请输入纳税人识别号',
      unitDfcostcenterInp: '请输入默认成本中心',
      unitDfhirecityInp: '请选择默认雇佣地点',
      unitDfworkcityInp: '请选择默认工作地点',
      invreasonInp: '请输入失效原因...',
      commentInp: '请输入备注...',
    },
    orgChart: {
      title: '组织架构图',
      savImg: '保存图片',
      horrization: '水平',
      vertical: '垂直',
      shrinkage: '收缩',
      expand: '展开',
      white: '白色',
      orange: '橙色',
      gold: '金色',
      gray: '灰色',
      lightpink: '粉色',
    },
    orgpost: {
      title: '岗位信息管理',
      postCode: '岗位编码',
      postFnameCnDis: '岗位全称',
      postSnameCnDis: '岗位简称',
      postFnameEnDis: '岗位全称',
      postSnameEnDis: '岗位简称',
      postUnitName: '所属组织',
      postDfcostcenterName: '默认成本中心',
      postDfpslevel: '默认职位级别',
      postDfsallevel: '默认薪资级别',
      postDftrvlevel: '默认差旅级别',
      validdate: '生效日期',
      invdate: '失效日期',
      invreason: '失效原因',
      comment: '备注',
      postCodeInp: '请输入岗位编码',
      postFnameCnDisInp: '请输入岗位全称',
      postSnameCnDisInp: '请输入岗位简称',
      postFnameEnDisInp: '请输入岗位全称',
      postSnameEnDisInp: '请输入岗位简称',
      postFCOrENameInp: '请输入岗位全称',
      postUnitNameInp: '请选择所属组织',
      postDfcostcenterNameInp: '请选择默认成本中心',
      postDfpslevelInp: '选择职位级别',
      postDfsallevelInp: '选择薪资级别',
      postDftrvlevelInp: '选择差旅级别',
      validdateInp: '选择生效日期',
      invdateInp: '选择失效日期',
      invreasonInp: '请输入失效原因...',
      commentInp: '请输入备注...',
    },
    orgcostcenter: {
      title: '成本中心管理',
      nameDis: '请输入成本中心名称',
      costcenterList: '选择成本中心',
      costCode: '成本中心编码',
      cname: '中文名称',
      ename: '英文名称',
      validdate: '生效日期',
      invdate: '失效日期',
      invreason: '失效原因',
      comment: '备注',
      costCodeDis: '请输入成本中心编码',
      cnameDis: '请输入中文名称',
      enameDis: '请输入英文名称',
      cOrENameDis: '请输入中/英文名称',
      validdateDis: '选择生效日期',
      invdateDis: '选择失效日期',
      invreasonDis: '请输入失效原因...',
      commentDis: '请输入备注...',
    },
    searchOrgCompany: {
      title: '所属公司',
      pmtypeCodeDis: '请输入公司名称',
      compFnameCnDis: '公司全称',
      compFnameEnDis: '公司全称',
      logType: '公司弹出框',
    },
  },
  'en-US': {
    orgframe: {
      title: 'Organization Management',
      title1: 'Organization Management',
      unitCode: 'Organization code',
      unitCode1: 'Organization code',
      compFnameCnDis: 'CN full name',
      compSnameCnDis: 'CN simple name',
      compFnameEnDis: 'EN full name',
      compSnameEnDis: 'EN simple name',
      compCOrEName: 'CN/EN full name',
      unitTypeName: 'Tissue types',
      unitPname: 'Affiliated superior',
      validdate: 'Start Date',
      invdate: 'End Date',
      unitDfcostcenter: 'Default cost center',
      unitDfhirecity: 'Default employment location',
      unitDfworkcity: 'Default working place',
      invreason: 'Reason for failure',
      orgList: 'Select units',
      comment: 'Comment',
      reminderErr: 'The organization type under the department node cannot be the company',
      unitCodeInp: 'Please enter the organization name',
      unitCodeInp1: 'Please enter the organization name',
      compFnameCnDisInp: 'Please enter the full name of the company in Chinese',
      compSnameCnDisInp: 'Please enter company\'s Chinese abbreviation',
      compFnameEnDisInp: 'Please enter the full name of the company in English',
      compSnameEnDisInp: 'Please enter company abbreviation',
      compCOrENameInp: 'Please enter company full eName or cName',
      unitTypeNameInp: 'Choose a type',
      unitPnameInp: 'Please select parent organization',
      validdateInp: 'Select Start date',
      invdateInp: 'Select End date',
      unitAgentnoInp: 'Please enter the taxpayer identification number',
      unitAgentno: 'Taxpayer Identification Number',
      unitDfcostcenterInp: 'Please enter the default cost center',
      unitDfhirecityInp: 'Please select the default employment location',
      unitDfworkcityInp: 'Please select a default location',
      invreasonInp: 'Please enter invalidation reason...',
      commentInp: 'Please enter comment...',
    },
    orgChart: {
      title: 'Organization Chart',
      savImg: 'Save ChartPicture',
      horrization: 'Horizontal',
      vertical: 'Vertical',
      shrinkage: 'Shrinkage',
      expand: 'Expend',
      white: 'White',
      orange: 'Orange',
      gold: 'Golden',
      gray: 'Gray',
      lightpink: 'Pink',
    },
    orgpost: {
      title: 'Post Information Management',
      postCode: 'Post Code',
      postFnameCnDis: 'Chinese Full Name',
      postSnameCnDis: 'Chinese Simple Name',
      postFnameEnDis: 'English Full Name',
      postSnameEnDis: 'English Full Name',
      postUnitName: 'Affiliation',
      postDfcostcenterName: 'Default cost center',
      postDfpslevel: 'Default position level',
      postDfsallevel: 'Default salary level',
      postDftrvlevel: 'Default travel level',
      validdate: 'Start Date',
      invdate: 'End Date',
      invreason: 'Reason for failure',
      comment: 'Comment',
      postCodeInp: 'Please enter the post code',
      postFnameCnDisInp: 'Please input full Chinese name',
      postSnameCnDisInp: 'Please enter Chinese abbreviation',
      postFnameEnDisInp: 'Please input full name in English',
      postSnameEnDisInp: 'Please enter English abbreviation',
      postFCOrENameInp: 'Please enter chinese name or english name',
      postUnitNameInp: 'Please select your organization',
      postDfcostcenterNameInp: 'Please select the default cost center',
      postDfpslevelInp: 'Select position level',
      postDfsallevelInp: 'Select salary level',
      postDftrvlevelInp: 'Choose travel level',
      validdateInp: 'Select Start date',
      invdateInp: 'Select End date',
      invreasonInp: 'Please enter invalidation reason...',
      commentInp: 'Please enter comment...',
    },
    orgcostcenter: {
      title: 'Cost Center Management',
      nameDis: 'Please enter cost center name',
      costcenterList: 'Select Costcenter',
      costCode: 'Cost Center Code',
      cname: 'Chinese Name',
      ename: 'English Name',
      validdate: 'Start Date',
      invdate: 'End Date',
      invreason: 'Invalidate Reason',
      comment: 'Comment',
      costCodeDis: 'Please enter cost code',
      cnameDis: 'Please enter chinese name',
      enameDis: 'Please enter english name',
      cOrENameDis: 'Please enter Chinese/English',
      validdateDis: 'Select start date',
      invdateDis: 'Select end date',
      invreasonDis: 'Please enter invalidate reason...',
      commentDis: 'Please enter comment...',
    },
    searchOrgCompany: {
      title: 'Subordinate Company',
      pmtypeCodeDis: 'Please enter company name',
      compFnameCnDis: 'Company Chinese full name',
      compFnameEnDis: 'Company English full name',
      logType: 'Company pop-up',
    },
  },
}
