/* eslint-disable no-dupe-keys */
export default {
  'zh-CN': {
    allotWorkOrder: {
      title: '咨询工单分配',
      menuTitle: '处理状态',
      noAllotTotal: '待分配',
      yesallot: '已分配',
      cmwdCode: '工单编号',
      cmwdDesc: '工单描述',
      cmwdType: '工单类型',
      cmwdPriority: '优先级',
      createTime: '提交时间',
      cmwdExpfeedbacktime: '期望反馈时间',
      cmwdAuthor: '提交人',
      cmwdMobile: '手机号',
      cmwdStatus: '工单状态',
      allot: '分配',
      // searchColumns
      searchTitle: '分配工单',
      cmstmUserid: '姓名',
      cmstmStid: '团队',
      remindMessage: '分配成功!',
      // 工单详情页面
      detailTitle: '工单详情',
      dealPeople: '处理人',
      questionTitle: '问题标题',
      cmwdProperty: '工单属性',
      cmwdContent: '沟通记录',
      cmwdAttach: '附件信息',
      cmwdConfidentialinfo: '机密信息',
      handlePeople: '工程师',
      cmwdrdAttach: '附件信息',
      number: '号',
      browerImage: '浏览大图',
    },
    handleWorkOrder: {
      title: '咨询工单处理',
      menuTitle: '处理状态',
      noHandleTotal: '待接单',
      handleing: '处理中',
      yeshandle: '已处理',
      cmwdCode: '工单编号',
      cmwdDesc: '工单描述',
      cmwdType: '工单类型',
      cmwdPriority: '优先级',
      createTime: '提交时间',
      cmwdExpfeedbacktime: '期望反馈时间',
      cmwdAuthor: '提交人',
      cmwdMobile: '手机号',
      cmwdStatus: '工单状态',
      // button
      cmwdOrder: '接单',
      cmwdTranfer: '转接',
      // remind
      confirmOrder: '请确认是否转接该工单？',
      tranferSuccess: '转单成功！',
      OrderSuccess: '接单成功！',
      errReminder: '文件大小超出最大范围！',
      errReminder2: '暂不支持该格式文件！',
      backSuccess: '反馈成功，请等待处理！',
      // detail
      detailTitle: '工单详情',
      questionTitle: '问题标题',
      cmwdProperty: '工单属性',
      cmwdContent: '沟通记录',
      cmwdConfidentialinfo: '机密信息',
      handlePeople: '工程师',
      number: '号',
      cmwdrdAttach: '附件信息',
      evaluated: '已评价!',
      cmwdEvaluate: '整体评价',
      level: '星',
      cmwdIssolved: '问题是否解决',
      cmwdEvaluatedesc: '评价内容',
      browerImage: '浏览大图',
      feedback: '我要反馈',
      Message: '留言',
      UploadAttach: '上传附件',
      uploadCondition1: '最多可上传5个附件',
      uploadCondition2: '每个附件大小不得超过8M。附件支持的格式有：\'jpg\',\'gif\',\'png\',\'jpeg\',\'txt\',\'doc\',\'docx\',\'xlsx\',\'xls\',\'pdf\'',
      MessageDis: '请填写留言信息',
      // button
      back: '反馈',
      confirm: '确认',
      waitBack: '提交(待您反馈)',
      waitConfirm: '提交(待您确认)',
    },
    workorderSearch: {
      title: '工单信息查询',
      cmwdCode: '工单编号',
      cmwdDesc: '工单描述',
      cmwdType: '工单类型',
      cmwdProperty: '工单属性',
      cmwdAuthor: '提交人',
      createTime: '提交时间',
      cmwdStatus: '工单状态',
      // dis
      cmwdCodeDis: '请输入工单编号',
      cmwdDescDis: '请输入工单描述',
      cmwdTypeDis: '请选择工单类型',
      cmwdPropertyDis: '请选择工单属性',
      cmwdkeyWordDis: '请输入关键字',
      abroTitle: '请输入标题',
      plaabroTitle: '请输入标题',
      abroDatesta: '开始日期',
      plaabroDatesta: '请输入开始日期',
      abroDestination: '目的地',
      plaabroDestination: '请输入目的地',
      // seachColumns
      defaTitle: '选择类型',
      serchTitle: '选择工单类型',
      searchText: '请输入类型编码或名称',
      cmutKntypeCode: '工单类型编码',
      cmutKntypeName: '工单类型名称',
      // detail
      detailTitle: '工单详情',
      orderTitle: '工单标题',
      endOrder: '确认结单',
      cmwdRecord: '沟通记录',
      cmwdAttach: '附件信息',
      cmwdrdConfidentialinfo: '机密信息',
      handlePeople: '工程师',
      number: '号',
      cmwdrdAttach: '附件信息',
      evaluated: '已评价!',
      level: '星',
      cmwdEvaluate: '整体评价',
      cmwdIssolved: '工单是否解决',
      cmwdEvaluatedesc: '评价内容',
      browerImage: '浏览大图',
      IfeedBack: '我要反馈',
      Message: '留言',
      cmwdrdConfidentialinfoNo: '机密信息(非必填项)',
      UploadAttach: '上传附件',
      uploadCondition1: '最多可上传5个附件',
      uploadCondition2: '每个附件大小不得超过8M。附件支持的格式有',
      waitEvaluate: '待您评价',
      cmwdEvaluate1: '再接再厉哦',
      cmwdEvaluate2: '服务态度好',
      cmwdEvaluate3: '业务能力强',
      cmwdEvaluate4: '问题解决很及时',
      cmwdEvaluate5: '服务很全面',
      solved: '已解决',
      nosolve: '未解决',
      cmwdrdDescDis: '若提交密码或AccessKey等信息,请通过\'机密信息\'方式添加,并在问题处理完毕后及时修改',
      cmwdrdConfidentialinfoDis: '请在此处填写实例名、账号、密码等机密信息,提交后机密信息将做加密处理',
      cmwdEvaluatedescDis: '感谢您对我们的肯定，为了给您带来更好的服务体验，请告诉我们您最满意的点',
      errorRemind1: '请对本次服务评价',
      messageDis: '请填写留言信息',
      confirmRemind1: '当您确认工单问题已经得到解决，您可关闭工单。关闭工单后如果有新的问题，您可以提交新的工单咨询',
      successRemind1: '已结束该工单！',
      confirmRemind2: '删除后，您将无法恢复和查看该工单，请谨慎操作',
      successRemind2: '删除成功！',
      errorRemind2: '文件大小超出最大范围！',
      errorRemind3: '暂不支持该格式文件！',
      successRemind3: '反馈成功，请等待处理！',
      successRemind4: '感谢您的评价！',
    },
    // 工单状态
    workStatus: {
      cmwdStatus1: '待分派',
      cmwdStatus2: '处理中-已分派',
      cmwdStatus3: '处理中/正在为您处理',
      cmwdStatus4: '处理中-转交待待分配',
      cmwdStatus5: '待您反馈',
      cmwdStatus6: '待您确认',
      cmwdStatus7: '待您评价',
      cmwdStatus8: '已关闭',
      cmwdStatus9: '待处理',
      cmwdStatus10: '处理中',
      cmwdStatus11: '待您处理',
      cmwdStatus12: '已受理',
      cmwdStatus13: '已处理',
      cmwdStatus14: '已评价',
      content1: '系统正在为您分派',
      content2: '实际处理时长',
      minute: '分钟',
    },
    // 业务工单详情
    commonFlowUpdate: {
      optuser: '操作人:',
      opttime: '更新时间:',
      pflowst0: '未开启',
      pflowst1: '待处理',
      pflowst2: '处理中',
      pflowst3: '已完成',
      confirmRemind: '是否确认关闭？',
      sumitRemind: '是否确认提交？',
      SubmittedSuccess: '提交成功',
      saveSuccess: '保存成功',
      editForm: '编辑表单',
      mailInformation: '邮件信息',
    },
    // 薪资工单详情
    commonFlowUpdate2: {
      payproSalset: '薪资账套',
      payproPeriod: '期间',
      payerrRound: '当前轮次',
      payerrCompid: '雇佣公司',
      payerrErrortype: '错误类型',
      payerrResperson: '负责人',
      payerrDealstatus: '处理状态',
      payerrDealperson: '处理人',
      payerrDealtime: '处理时间',
      payproContactComp: '包含公司及联系人',
      payproContact: '薪资联系人',
      paylink1: '薪资计划已发布，查看请点击',
      payPlan: '薪资计划',
      paylink2: '已完成薪资账套薪资数据的上传及维护',
      paylink3: '已完成福利数据的上传及维护',
      mailRecord: '邮件发送记录',
      paylink4: '已完成福利数据的上传及维护',
      payproPlandate: '日期时间',
      payReport: '薪资报告',
      errList: '错误列表',
      errTotal: '总错误数量',
      nohandErrTotal: '待处理错误数量',
      operator: '操作人',
      operatatetime: '操作时间',
      paylink5: '最后一轮薪资确认',
      batchConfirm: '批量确认',
      cmpbank: '招行',
      platDctpAffix: '付款凭证',
      payproBankcomment: '备注',
      lookInfo: '查看联系人信息',
      payssPhone: '联系电话',
      contract: '联系人',
      updateTime: '更新时间',
      payproBankcommentDis: '请输入内容',
      payRemind: '请选择薪资确认',
      pacemCnameDis: '请输入员工姓名或工号',
      ppcCompanyscopeDis: '请输入公司范围',
      // reminder
      advanceHandle: '请先处理错误数据',
      advaceSelect: '请先勾选最后一轮薪资确认',
    },
    myWorkOrderNew: {
      title: '我的工单管理',
      paneTitle1: '咨询工单',
      pTitle2: '我的工单提醒',
      ranTimeLeftDis: '请选择发起时间',
      ranTimeRightDis: '请选择结束时间',
      cmwdkeyWord: '关键字',
      cmwdkeyWordDis: '请输入关键字',
      businessOrder: '业务工单',
      businessOrderType: '业务工单类型',
      // remind
      deleteRemind: '删除后，您将无法恢复和查看该工单，请谨慎操作!',
    },
    commitWorkOrder: {
      title: '创建工单',
      step1: '第一步 选择工单大类',
      step2: '第二步 选择工单类型',
      step3: '第三步 推荐解决方案',
      step4: '第四步 在线客服/创建工单',
      step2Title: '请选择您遇到的工单分类：',
      hotArticle: '热点文章：',
      attach: '附件：',
      quickTitle: '您还可以通过以下渠道提交您的工单：',
      label1: '专业顾问及时处理，将尽快为您解答',
      onlineQues: '在线咨询',
      label2: 'HR智能助理、专业顾问在线解决您的疑问',
      priorityCommon: '业务咨询或普通业务受影响，需要协助',
      priorityImport: '关键业务受影响，需要紧急协助',
      impportReason: '重要原因',
      impportReasonDis: '请填写重要原因',
      cmwdMobileDis: '请输入手机号码',
      cmwdSmsprom: '接收短信提醒',
      email: '邮箱',
      emailDis: '请输入邮箱',
      cmwdDescDis: '请填写工单信息',
      cmwdExpfeedbacktimeDis: '请选择反馈时间',
      cmwdMobileDis: '请填写您的手机号码',
      cmwdImportantreasonDis: '请填写重要原因',
      saveRemind: '保存成功，请等待处理！',
      startRemind: '请选择业务工单类型',
    },
    archiveFlow: {
      title: '档案入档工单',
      entEmpName: '雇员',
      entHirecom: '雇用公司',
      entClaName: '档案分类',
      entEmpNameDis: '请选择雇员',
      entHirecomDis: '请选择雇用公司',
      entClaNameDis: '请选择档案分类',
    },
    archborFlow: {
      title: '档案查阅工单',
      borBorrower: '查阅人',
      borBorrowerDis: '请选择查阅人',
    },
    proFlow: {
      title: '员工转正工单',
      flowWorkno: '员工工号',
      pladCompany: '雇用公司',
      pladDept: '部门',
      flowCName: '中文名',
      flowWorknoDis: '请输入员工工号',
      pladCompanyDis: '请输入雇用公司',
      pladDeptDis: '请输入部门',
      flowCNameDis: '请输入中文名',
    },
    interFlow: {
      title: '员工调动工单',
      flowWorkno: '员工工号',
      pladCompany: '雇用公司',
      pladDept: '部门',
      flowCName: '中文名',
      flowWorknoDis: '请输入员工工号',
      pladCompanyDis: '请输入雇用公司',
      pladDeptDis: '请输入部门',
      flowCNameDis: '请输入中文名',
    },
    contextFlow: {
      title: '合同续签工单',
      title2: '护照签证工单',
      flowWorkno: '员工工号',
      pladCompany: '雇用公司',
      pladDept: '部门',
      flowCName: '中文名',
      flowWorknoDis: '请输入员工工号',
      pladCompanyDis: '请输入雇用公司',
      pladDeptDis: '请输入部门',
      flowCNameDis: '请输入中文名',
    },
    dimFlow: {
      title: '员工离职工单',
      flowWorkno: '员工工号',
      pladCompany: '雇用公司',
      pladDept: '部门',
      flowCName: '中文名',
      flowWorknoDis: '请输入员工工号',
      pladCompanyDis: '请输入雇用公司',
      pladDeptDis: '请输入部门',
      flowCNameDis: '请输入中文名',
    },
    entryFlow: {
      title: '员工入职工单',
      flowWorkno: '员工工号',
      pladCompany: '雇用公司',
      pladDept: '部门',
      flowCName: '中文名',
      flowWorknoDis: '请输入员工工号',
      pladCompanyDis: '请输入雇用公司',
      pladDeptDis: '请输入部门',
      flowCNameDis: '请输入中文名',
    },
    processFlow: {
      title: '薪资核算工单',
      payproSalset: '薪资帐套',
      period: '财年期间',
      payproRound: '轮次',
      payproSalsetDis: '请选择薪资帐套',
      periodDis: '请选择财年期间',
      payproRoundDis: '请选择轮次',
    },
    cmutImmsgLog: {
      title: '在线咨询日志',
      imsgSender: '发送人',
      imsgReceiver: '接收人',
      imsgGroup: '消息组',
      imsgSendtime: '发送时间',
      imsgMessagetype: '消息类型',
      imsgContype: '内容类型',
      imsgContent: '消息内容',
      imsgIsread: '是否已读',
      imsgSTime: '选择开始时间',
      imsgEtime: '选择结束时间',
      imsgSenderDis: '请选择发送人',
      imsgKeyword: '请输入内容关键字',
      // searchTable
      searchTitle: '选择用户',
      name: '姓名',
      mobileNo: '电话号码',
      email: '邮箱',
      nameDis: '请输入用户姓名',
    },
    abroad: {
      title: '出国申报工单',
      orderTypeDis: '请输入工单类型',
    },
    userWorkderStaisfaction: {
      title: '工单处理分析',
      orderType: '工单类型',
      allWorkoder: '工单总数',
      closeOrder: '已处理总数',
      avgEvaluate: '平均满意度',
      orderTypeDis: '请输入工单类型',
    },
    visareturn: {
      title: '回国管理工单',
      empName:  '员工姓名',
      empNameDis:  '请输入员工姓名',
    },
  },
  'en-US': {
    abroad: {
      title: '工单处理分析',
      orderTypeDis: '请输入工单类型',
    },
    allotWorkOrder: {
      title: 'Consultation Workorder allocation',
      menuTitle: 'Processing state',
      noAllotTotal: 'Noallocate',
      yesallot: 'Allocated',
      cmwdCode: 'OrderNumber',
      cmwdDesc: 'OrderDescription',
      cmwdType: 'OrderType',
      cmwdPriority: 'OrderPriority',
      createTime: 'Submittime',
      cmwdExpfeedbacktime: 'Expected feedback time',
      cmwdAuthor: 'Submiter',
      cmwdMobile: 'Mobile phone no.',
      cmwdStatus: 'Workorder status',
      allot: 'Allot',
      // searchColumns
      searchTitle: 'Allot Workorder',
      cmstmUserid: 'Name',
      cmstmStid: 'Team',
      remindMessage: 'Distribution successful!',
      // 工单详情页面
      detailTitle: 'Workorder details',
      dealPeople: 'Dealing with people',
      questionTitle: 'Question title',
      cmwdProperty: 'The repair order properties',
      cmwdContent: 'Communication record',
      cmwdAttach: 'The attachment information',
      cmwdrdConfidentialinfo: 'Confidential information',
      handlePeople: 'The engineer',
      cmwdrdAttach: 'The attachment information',
      number: 'number',
      browerImage: 'View a larger version',
    },
    handleWorkOrder: {
      title: 'Consultation Workorder processing',
      menuTitle: 'Processing state',
      noHandleTotal: 'WaitingList',
      handleing: 'Handleing',
      yeshandle: 'Handled',
      cmwdCode: 'Ordernumber',
      cmwdDesc: 'OrderDescription',
      cmwdType: 'OrderType',
      cmwdPriority: 'OrderPriority',
      createTime: 'Submit time',
      cmwdExpfeedbacktime: 'Expected feedback time',
      cmwdAuthor: 'Submiter',
      cmwdMobile: 'Mobile phone no.',
      cmwdStatus: 'Workorder status',
      // button
      cmwdOrder: 'Order',
      cmwdTranfer: 'Tranfer',
      // remind
      confirmOrder: 'Please confirm whether to transfer the Workorder?',
      tranferSuccess: 'Order transfer successful!',
      OrderSuccess: 'Order received successfully!',
      errReminder: 'File size out of maximum range!',
      errReminder2: 'This format file is not supported yet!',
      backSuccess: 'Feedback successful, please wait for processing!',
      // detail
      detailTitle: 'Workorder details',
      questionTitle: 'Question title',
      cmwdProperty: 'The repair order properties',
      cmwdContent: 'Communication record',
      cmwdConfidentialinfo: 'Confidential information',
      handlePeople: 'The engineer',
      number: 'No.',
      cmwdrdAttach: 'The attachment information',
      evaluated: 'Have evaluation!',
      cmwdEvaluate: 'The overall evaluation',
      level: 'star',
      cmwdIssolved: 'Whether the problem is solved',
      cmwdEvaluatedesc: 'Evaluation content',
      browerImage: 'View a larger version',
      feedback: 'I want to feedback',
      Message: 'Leave a message',
      UploadAttach: 'To upload attachments',
      uploadCondition1: 'Up to 5 attachments can be uploaded',
      uploadCondition2: 'The size of each attachment shall not exceed 8M.The formats supported by attachments are：\'jpg\',\'gif\',\'png\',\'jpeg\',\'txt\',\'doc\',\'docx\',\'xlsx\',\'xls\',\'pdf\'',
      MessageDis: 'Please fill in the message',
      // button
      back: 'Feedback',
      confirm: 'Confirm',
      waitBack: 'Submit(waitingfeedback)',
      waitConfirm: 'Submit(waitConfirm)',
    },
    workorderSearch: {
      title: 'Workorder search',
      cmwdCode: 'OrderNumber',
      cmwdDesc: 'OrderDescription',
      cmwdType: 'OrdeType',
      cmwdProperty: 'OrderProperties',
      cmwdAuthor: 'Submiter',
      createTime: 'Submittime',
      cmwdStatus: 'OrderStatus',
      // dis
      cmwdCodeDis: 'Please enter the Workorder number',
      cmwdDescDis: 'Please enter the description of Workorder',
      cmwdTypeDis: 'Please select Workorder type',
      cmwdPropertyDis: 'Select the Workorder attribute',
      cmwdkeyWordDis: 'Please enter the keyword',
      abroTitle: 'title',
      plaabroTitle: 'Please enter the title',
      abroDatesta: 'Start date',
      plaabroDatesta: 'Please enter the start date',
      abroDestination: 'destination',
      plaabroDestination: 'Please enter destination',
      // seachColumns
      defaTitle: 'Choose the type',
      serchTitle: 'Select Workorder type',
      searchText: 'Please enter a type code or name',
      cmutKntypeCode: 'Workorder type coding',
      cmutKntypeName: 'Workorder type name',
      // detail
      detailTitle: 'Workorder details',
      orderTitle: 'Order title',
      endOrder: 'End the Order',
      cmwdRecord: 'Communication record',
      cmwdAttach: 'Attachment information',
      cmwdrdConfidentialinfo: 'Confidential information',
      handlePeople: 'The engineer',
      number: 'No.',
      cmwdrdAttach: 'Attachment information',
      evaluated: 'Evaluated!',
      level: 'star',
      cmwdEvaluate: 'The overall evaluation',
      cmwdIssolved: 'Whether the Workorder is solved',
      cmwdEvaluatedesc: 'Evaluation content',
      browerImage: 'View a larger version',
      IfeedBack: 'I want to feedback',
      Message: 'Leave a message',
      cmwdrdConfidentialinfoNo: 'Confidential information (optional)',
      UploadAttach: 'To upload attachments',
      uploadCondition1: 'Up to 5 attachments can be uploaded',
      uploadCondition2: 'The size of each attachment shall not exceed 8M.The formats supported by attachments are',
      waitEvaluate: 'Forward to your evaluation',
      cmwdEvaluate1: 'Keep up the good work',
      cmwdEvaluate2: 'Good service attitude',
      cmwdEvaluate3: 'Strong business ability',
      cmwdEvaluate4: 'The problem was solved promptly',
      cmwdEvaluate5: 'The service is comprehensive.',
      solved: 'resolved',
      nosolve: 'Not solved',
      cmwdrdDescDis: 'If you submit information such as password or AccessKey, please add it in the way of \'confidential information\' and modify it timely after the problem is solved',
      cmwdrdConfidentialinfoDis: 'Please fill in the instance name, account number, password and other confidential information here. The confidential information will be encrypted after submission',
      cmwdEvaluatedescDis: 'Thank you for your recognition of us. In order to bring you a better service experience, please tell us what you are most satisfied with',
      errorRemind1: 'Please comment on this service',
      messageDis: 'Please fill in the message',
      confirmRemind1: 'When you confirm that the Workorder problem has been solved, you can close the Workorder.If there are any new problems after closing the Workorder, you can submit the new Workorder for consultation',
      successRemind1: 'The Workorder has been finished!',
      confirmRemind2: 'After deletion, you will not be able to recover and view the Workorder. Please take care',
      successRemind2: 'Delete successful!',
      errorRemind2: 'File size out of maximum range!',
      errorRemind3: 'This format file is not supported yet!',
      successRemind3: 'Feedback successful, please wait for processing!',
      successRemind4: 'Thank you for your comments!',
    },
    workStatus: {
      cmwdStatus1: 'Waiting',
      cmwdStatus2: 'Processing-dispatched',
      cmwdStatus3: 'In process/in process for you',
      cmwdStatus4: 'Processing-transfer to order receiving',
      cmwdStatus5: 'To be feedback ',
      cmwdStatus6: 'To be confirmed ',
      cmwdStatus7: 'To be evaluated',
      cmwdStatus8: 'Closed',
      cmwdStatus9: 'Waiting',
      cmwdStatus10: 'Processing',
      cmwdStatus11: 'For you to deal with',
      cmwdStatus12: 'Accepted',
      cmwdStatus13: 'Handled',
      cmwdStatus14: 'Evaluated',
      content1: 'The system is dispatching for you',
      content2: 'Actual processing time',
      minute: 'minute',
    },
    commonFlowUpdate: {
      optuser: 'Operator:',
      opttime: 'Updatetime:',
      pflowst0: 'Did not open',
      pflowst1: 'To be processed',
      pflowst2: 'In the processing',
      pflowst3: 'Has been completed',
      confirmRemind: 'Are you sure to close?',
      sumitRemind: 'Is the submission confirmed?',
      SubmittedSuccess: 'Submitted successfully',
      saveSuccess: 'Save success',
      editForm: 'Edit Form',
      mailInformation: 'Email Messages',
    },
    // 薪资工单详情
    commonFlowUpdate2: {
      payproSalset: 'Salary set',
      payproPeriod: 'Period',
      payerrRound: 'CurrentRounds',
      payerrCompid: 'Hirecompany',
      payerrErrortype: 'ErrorType',
      payerrResperson: 'Responsibility',
      payerrDealstatus: 'DealStatus',
      payerrDealperson: 'DealPerson',
      payerrDealtime: 'DealTime',
      payproContactComp: 'Includes company and contacts',
      payproContact: 'Payroll contact',
      paylink1: 'Salary plan has been released, please click to view',
      payPlan: 'Payroll plan',
      paylink2: 'Completed the upload and maintenance of salary data of salary account set',
      paylink3: 'Completed the upload and maintenance of welfare data',
      mailRecord: 'Mailing record',
      paylink4: 'Completed the upload and maintenance of welfare data',
      payproPlandate: 'Date/time',
      payReport: 'Salary report',
      errList: 'Error list',
      errTotal: 'Total number of errors',
      nohandErrTotal: 'Number of errors to be processed',
      operator: 'Operator',
      operatatetime: 'Operating time',
      paylink5: 'Final salary confirmation',
      batchConfirm: 'BatchConfirmation',
      cmpbank: 'China merchants',
      platDctpAffix: 'Proof of payment',
      payproBankcomment: 'Comment',
      lookInfo: 'View contact information',
      payssPhone: 'Contact phone number',
      contract: 'Contract',
      updateTime: 'Updatetime',
      payproBankcommentDis: 'Please enter content',
      payRemind: 'Please select salary confirmation',
      pacemCnameDis: 'Please enter employee name or workno',
      ppcCompanyscopeDis: 'Please enter company scope',
      // reminder
      advanceHandle: 'Please handle the error data first',
      advaceSelect: 'Please check the last round of salary confirmation first',
    },
    myWorkOrderNew: {
      title: 'My work order management',
      paneTitle1: 'ConsultionOrder',
      pTitle2: 'Reminder of my work order',
      ranTimeLeftDis: 'Please select the launch time',
      ranTimeRightDis: 'Please select the end time',
      cmwdkeyWord: 'keyword',
      cmwdkeyWordDis: 'Please enter the keyword',
      businessOrder: 'BusinessOrder',
      businessOrderType: 'Business work order type',
      // remind
      deleteRemind: 'After deletion, you will not be able to recover and view the work order, please be careful!',
    },
    commitWorkOrder: {
      title: 'Create work order',
      step1: 'Step1: Order category',
      step2: 'Step2: Order type',
      step3: 'Step3: Recommend',
      step4: 'Step4: Consultion/Order',
      step2Title: 'Please select the category of work order you encounter:',
      hotArticle: 'Hot article:',
      attach: 'Attach:',
      quickTitle: 'You can also submit your work order through the following channels:',
      label1: 'The professional consultant.',
      onlineQues: 'Online consulting',
      label2: 'HR intelligent assistant',
      priorityCommon: 'Business advisory or general business is affected and assistance is required',
      priorityImport: 'Critical operations are affected and require urgent assistance',
      impportReason: 'Import Reason',
      impportReasonDis: 'Please fill in the important reasons',
      cmwdMobileDis: 'Please enter your mobile phone number',
      cmwdSmsprom: 'Receive SMS alerts',
      email: 'Email',
      emailDis: 'Please enter email address',
      cmwdDescDis: 'Please fill in the work order information',
      cmwdExpfeedbacktimeDis: 'Please select a feedback time',
      cmwdMobileDis: 'Please fill in your mobile phone number',
      cmwdImportantreasonDis: 'Please fill in the important reasons',
      saveRemind: 'Save successfully, please wait for processing!',
      startRemind: 'Please select the type of business order',
    },
    archiveFlow: {
      title: 'File entry form',
      entEmpName: 'Employees',
      entHirecom: 'Hirecompany',
      entClaName: 'Classification',
      entEmpNameDis: 'Please select employee',
      entHirecomDis: 'Please select the company to hire',
      entClaNameDis: 'Please select file category',
    },
    archborFlow: {
      title: 'File access worksheet',
      borBorrower: 'Borrower',
      borBorrowerDis: 'Please select borrower',
    },
    proFlow: {
      title: 'Employees Probation WorkOrder',
      flowWorkno: 'EmployeeNO',
      pladCompany: 'Hirecompany',
      pladDept: 'Department',
      flowCName: 'Name',
      flowWorknoDis: 'Please enter the employee number',
      pladCompanyDis: 'Please enter employment company',
      pladDeptDis: 'Please enter department',
      flowCNameDis: 'Please enter Chinese name',
    },
    interFlow: {
      title: 'Employee Tranfer Order ',
      flowWorkno: 'EmployeeNO',
      pladCompany: 'Hirecompany',
      pladDept: 'Department',
      flowCName: 'Name',
      flowWorknoDis: 'Please enter the employee number',
      pladCompanyDis: 'Please enter employment company',
      pladDeptDis: 'Please enter department',
      flowCNameDis: 'Please enter Chinese name',
    },
    contextFlow: {
      title: 'Contract renewal WorkOrder',
      flowWorkno: 'EmployeeNO',
      pladCompany: 'Hirecompany',
      pladDept: 'Department',
      flowCName: 'Name',
      flowWorknoDis: 'Please enter the employee number',
      pladCompanyDis: 'Please enter employment company',
      pladDeptDis: 'Please enter department',
      flowCNameDis: 'Please enter Chinese name',
    },
    dimFlow: {
      title: 'Employee dimiss WorkOrder',
      flowWorkno: 'EmployeeNO',
      pladCompany: 'Hirecompany',
      pladDept: 'Department',
      flowCName: 'Name',
      flowWorknoDis: 'Please enter the employee number',
      pladCompanyDis: 'Please enter employment company',
      pladDeptDis: 'Please enter department',
      flowCNameDis: 'Please enter Chinese name',
    },
    entryFlow: {
      title: 'Employee Entry WorkOrder',
      flowWorkno: 'EmployeeNO',
      pladCompany: 'Hirecompany',
      pladDept: 'Department',
      flowCName: 'Name',
      flowWorknoDis: 'Please enter the employee number',
      pladCompanyDis: 'Please enter employment company',
      pladDeptDis: 'Please enter department',
      flowCNameDis: 'Please enter Chinese name',
    },
    processFlow: {
      title: 'Payroll processing workOrder',
      payproSalset: 'PaySalSet',
      period: 'Period',
      payproRound: 'Rounds',
      payproSalsetDis: 'Please select salary account package',
      periodDis: 'Please select the fiscal year period',
      payproRoundDis: 'Please select rotation',
    },
    cmutImmsgLog: {
      title: 'Online consultation journal',
      imsgSender: 'Sender',
      imsgReceiver: 'Recipient',
      imsgGroup: 'MessageGroups',
      imsgSendtime: 'Sendtime',
      imsgMessagetype: 'MessageType',
      imsgContype: 'ContentType',
      imsgContent: 'MessageContent',
      imsgIsread: 'Is Read?',
      imsgSTime: 'Select start time',
      imsgEtime: 'Select end time',
      imsgSenderDis: 'Please select sender',
      imsgKeyword: 'Please enter content keyword',
      // searchTable
      searchTitle: 'Select the user',
      name: 'Name',
      mobileNo: 'Telephone Number',
      email: 'Mail',
      nameDis: 'Please enter user name',
    },
    userWorkderStaisfaction: {
      title: 'Work order processing and analysis',
      orderType: 'OrderType',
      allWorkoder: 'OrderTotals',
      closeOrder: 'OrderClosed',
      avgEvaluate: 'AverageSatisfaction',
      orderTypeDis: 'Please enter work order type',
    },
    visareturn: {
      title: '回国管理工单',
      empName:  '员工姓名',
      empNameDis:  '请输入员工姓名',
    },
  },
}
