export default {
  'zh-CN': {
    empmaster: {
      title: '员工信息管理',
      title1: '员工基本信息',
      title2: '员工公司信息',
      title3: '员工合同信息',
      title4: '薪资社保信息',
      title5: '最高学历信息',
      title6: '联系地址信息',
      imgAlt: '暂无头像',
      empCname: '中文名',
      companyName: '公司',
      deptName: '部门',
      empidTypeName: '证件类型',
      empGenderDis: '性别',
      empcompPostDis: '岗位',
      empGid: '员工GID',
      empidNo: '证件号码',
      empcompEntrydate: '入职日期',
      empkiWorkno: '员工工号',
      empkiEmptypeName: '员工类型',
      empCnameDis: '请输入员工姓名',
      empkiWorknoDis: '请输入员工工号',
      empPostDis: '请选择部门信息！',
      empHireCompDis: '请选择雇佣公司信息！',
    },
    empmasterCheck: {
      baseGid: '请输入唯一标识号',
      baseCname: '请输入中文姓名',
      baseLastname: '请输入Last Name',
      baseFirstname: '请输入First Name',
      idsType: '请输入证件类型',
      idsNo: '请输入证件号码',
      baseBirthdate: '请输入出生日期',
      baseGender: '请选择性别',
      baseMarriage: '请选择婚育状况',
      baseNation: '请选择民族',
      basePolitical: '请选择政治面貌',
      baseTechnicaltitle: '请选择职称',
      baseTechspec: '请输入职称专业',
      baseFirstworkdate: '请输入参加工作时间',
      baseTechdate: '请输入职称取得时间',
      pkiWorkno: '请输入员工工号',
      pkiEmptype: '请选择员工类型',
      compHirecompany: '请选择雇佣公司',
      compDept: '请选择部门',
      compPost: '请选择岗位',
      compCostcenter: '请选择成本中心',
      compHirelocation: '请选择雇佣地点',
      compWorklocation: '请选择工作地点',
      compBuspmp: '请选择业务上级经理',
      compFunpmp: '请选择功能上级经理',
      compEntrydate: '请选择入职日期',
      compServicedate: '请选择服务年限计算开始日期',
      compCertificatedate: '请选择证书年限计算开始日期',
      compHr: '请选择HR顾问',
      ctContracttype: '请选择合同类别',
      ctContractperiod: '请选择合同期限',
      ctContractsdate: '请选择合同开始日期',
      ctContractedate: '请选择合同到期日期',
      ctContractprom: '请选择合同到期通知时间',
      ctConfidential: '请选择保密协议',
      ctContractworktime: '请选择合同工作时间',
      ctSigndate: '请选择签署日期',
      ctProbation: '请选择试用期限',
      ctProbationdate: '请选择试用到期时间',
      ctProbationprom: '请选择试用到期通知时间',
      salPostlevel: '请选择职位级别',
      salSalarylevel: '请选择薪资级别',
      salTravellevel: '请选择差旅级别',
      salAdminlevel: '请选择薪资级别',
      salSalaryset: '请选择薪资套装',
      bkBank: '请选择开户银行',
      bkAccount: '请输入银行账号',
      bkAccnane: '请输入开户名',
      sbBenefitlocation: '请选择社保缴纳地',
      sbHfundlocatio: '请选择公积金缴纳地',
      sbBenefitpolicy: '请选择社保政策',
      sbBenefittype: '请选择社保开户类别',
      edEducationlevel: '请选择教育程度',
      edCuntry: '请选择国家',
      edSchool: '请输入学校',
      edDegree: '请输入学位',
      edSpecialty: '请输入专业',
      edSdate: '请选择开始时间',
      edEdate: '请选择结束时间',
      ctaMobile: '请输入手机号',
      ctaPhone: '请输入联系电话',
      ctaPersmail: '请输入个人邮箱',
      ctaCompmail: '请输入公司邮箱',
      ctaQq: '请输入QQ号',
      ctaWechat: '请输入微信号',
      ctaEmergcontact: '请输入紧急联系人姓名',
      ctaEmcrelation: '请选择紧急联系人关系',
      ctaEmcphone: '请输入紧急联系电话',
      ctaEmcaddr: '请输入紧急联系地址',
      addCuntry: '请选择国家',
      addProvince: '请选择居住省份',
      addCity: '请选择居住城市',
      addStreet: '请输入居住详细地址',
      addZip: '请输入居住邮编',
      addrCuntry: '请选择户籍国家',
      addrProvince: '请选择户籍省分',
      addrCity: '请选择户籍城市',
      addrStreet: '请输入户籍详细地址',
      addrRegisterproperty: '请选择户籍性质',
      addrZip: '请输入户籍邮编',
      sbHfundpolicy: '请选择公积金政策',
      sbHfundtype: '请选择公积金开户类别',
    },
    baseInfo: {
      title: '基本信息',
      baseGid: '唯一标识号',
      baseCname: '中文姓名',
      baseAlias: '别名/曾用名',
      baseLastname: 'Last name',
      baseFirstname: 'First name',
      idsType: '证件类型',
      idsNo: '证件号码',
      baseBirthdate: '出生日期',
      baseGender: '性别',
      baseMarriage: '婚育状况',
      baseNation: '民族',
      basePolitical: '政治面貌',
      baseTechnicaltitle: '职称',
      baseTechspec: '职称专业',
      baseFirstworkdate: '参加工作时间',
      baseTechdate: '职称取得时间',
      baseGidDis: '请输入唯一标识号..',
      baseCnameDis: '请输入中文姓名',
      baseAliasDis: '请输入别名/曾用名',
      baseLastnameDis: '请输入Last name',
      baseFirstnameDis: '请输入First name',
      idsNoDis: '请输入证件号码',
      baseBirthdateDis: '请选择出生日期',
      baseNationDis: '请选择民族',
      baseTechspecDis: '请输入职称专业',
      baseFirstworkdateDis: '请选择参加工作时间',
      baseTechdateDis: '请选择职称取得时间',
    },
    companyInfo: {
      title: '公司信息',
      pkiWorkno: '员工工号',
      pkiEmptype: '员工类型',
      compHirecompany: '雇佣公司',
      compDept: '部门',
      compPost: '岗位',
      compCostcenter: '成本中心',
      compHirelocation: '雇佣地点',
      compWorklocation: '工作地点',
      compBuspmp: '业务上级经理',
      compFunpmp: '功能上级经理',
      compEntrydate: '入职日期',
      compServicedate: '服务年限计算开始日期',
      compCertificatedate: '证书年限计算开始日期',
      compHr: 'HR顾问',
      pkiWorknoDis: '请输入员工工号',
      compHirecompanyDis: '请选择雇佣公司',
      compDeptDis: '请选择部门',
      compPostDis: '请选择岗位',
      compCostcenterDis: '请选择成本中心',
      compHirelocationDis: '请选择雇佣地点',
      compWorklocationDis: '请选择工作地点',
      compBuspmpDis: '请选择业务上级经理',
      compFunpmpDis: '请选择功能上级经理',
      compEntrydateDis: '请选择入职日期',
      compServicedateDis: '请选择服务开始日期',
      compCertificatedateDis: '请选择证书日期',
      compHrDis: '请选择HR顾问',
    },
    contractInfo: {
      title: '合同信息',
      ctContracttype: '合同类别',
      ctContractperiod: '合同期限',
      ctContractsdate: '合同开始日期',
      ctContractedate: '合同到期日期',
      ctContractprom: '合同到期通知时间(天数)',
      ctConfidential: '保密协议',
      ctContractworktime: '合同工作时间',
      ctSigndate: '签署日期',
      ctProbation: '试用期限',
      ctProbationdate: '试用到期时间',
      ctProbationprom: '试用到期通知时间(天数)',
      ctContractsdateDis: '请选择合同开始日期',
      ctContractedateDis: '请选择合同到期日期',
      ctSigndateDis: '请选择合同签署日期',
      ctProbationdateDis: '请选择试用到期时间',
    },
    payInfo: {
      title: '薪资社保信息',
      salPostlevel: '职位级别',
      salSalarylevel: '薪资级别',
      salTravellevel: '差旅级别',
      salAdminlevel: '行政级别',
      salSalaryset: '薪资帐套',
      bkBank: '开户银行',
      bkAccount: '账号',
      bkAccnane: '户名',
      sbBenefitlocation: '社保缴纳地',
      sbHfundlocatio: '公积金缴纳地',
      sbBenefitpolicy: '社保政策',
      sbHfundpolicy: '公积金政策',
      sbBenefittype: '社保开户类别',
      sbHfundtype: '公积金开户类别',
      bkBankDis: '请选择开户银行',
      bkAccountDis: '请输入银行账号',
      bkAccnaneDis: '请输入开户名',
      sbBenefitlocationDis: '请选择社保缴纳地',
      sbHfundlocatioDis: '请选择公积金缴纳地',
      sbBenefitpolicyDis: '请选择社保政策',
      sbHfundpolicyDis: '请选择公积金政策',
      sbHfundtypeDis: '请选择公积金开户类别',
    },
    educationInfo: {
      title: '最高学历信息',
      edEducationlevel: '教育程度',
      edCuntry: '国家',
      edSchool: '学校',
      edDegree: '学位',
      edSpecialty: '专业',
      edSdate: '开始时间',
      edEdate: '结束时间',
      edSchoolDis: '请输入学校',
      edDegreeDis: '请输入学位',
      edSpecialtyDis: '请输入专业',
      edSdateDis: '请选择开始时间',
      edEdateDis: '请选择结束时间',
    },
    addressInfo: {
      title: '联系地址信息',
      ctaMobile: '手机号',
      ctaPhone: '联系电话(固定)',
      ctaPersmail: '个人邮箱',
      ctaCompmail: '公司邮箱',
      ctaQq: 'QQ',
      ctaWechat: '微信号',
      ctaEmergcontact: '紧急联系人',
      ctaEmcrelation: '紧急联系人关系',
      ctaEmcphone: '紧急联系电话',
      ctaEmcaddr: '紧急联系地址',
      addCuntry: '居住国家',
      addProvince: '居住省份',
      addCity: '居住城市',
      addStreet: '居住详细地址',
      addZip: '居住邮编',
      addrCuntry: '户籍国家',
      addrProvince: '户籍省份',
      addrCity: '户籍城市',
      addrStreet: '户籍详细地址',
      addrRegisterproperty: '户籍性质',
      addrZip: '户籍邮编',
      ctaMobileDis: '请输入手机号',
      ctaPhoneDis: '请输入联系电话',
      ctaPersmailDis: '请输入个人邮箱',
      ctaCompmailDis: '请输入公司邮箱',
      ctaQqDis: '请输入QQ号',
      ctaWechatDis: '请输入微信号',
      ctaEmergcontactDis: '请输入紧急联系人姓名',
      ctaEmcphoneDis: '请输入紧急联系电话',
      ctaEmcaddrDis: '请输入紧急联系地址',
      addProvinceDis: '请选择居住省份',
      addCityDis: '请选择居住城市',
      addStreetDis: '请输入居住详细地址',
      addZipDis: '请输入居住邮编',
      addrProvinceDis: '请输入户籍省份',
      addrCityDis: '请输入户籍城市',
      addrStreetDis: '请输入户籍详细地址',
      addrZipDis: '请输入户籍邮编',
    },
    searchColumn: {
      lanCn: '参数中文',
      lanEn: '参数英文',
      nationCn: '中文名称',
      nationEn: '英文名称',
      nationName: '选择民族',
      nationNameDis: '请输入中/英文名称',
      bankCname: '选择银行',
      bankCnameDis: '请输入开户银行名称',
      unitCodeCompany: '公司编码',
      compCnFullName: '公司名称',
      compEnFullName: '公司名称',
      unitCodeDepart: '部门编码',
      departCnFullName: '部门名称',
      departEnFullName: '部门名称',
      postCode: '岗位编码',
      postFnameCnDis: '岗位名称',
      postFnameEnDis: '岗位名称',
      sbPolicy: '社保政策',
      sbPolicyDis: '请输入社保政策',
      hireCompany: '雇佣公司',
      searchCompany: '选择公司',
      hireCompanyDis: '请输入公司名称',
      depart: '部门',
      selectDepart: '选择部门',
      departDis: '请输入部门名称',
      post: '选择岗位',
      postDis: '请输入岗位编码',
      inputDis: '请输入员工姓名',
      cityNameDis: '请输入城市名称',
      searchTitle: '选择民族',
    },
    searchTableTitle: {
      hirelocation: '雇佣地点',
      worklocation: '工作地点',
      benefitlocation: '社保缴纳地',
      hfundlocatio: '公积金缴纳地',
      hfundpolicy: '公积金政策',
      benefitpolicy: '社保政策',
      province: '居住省份',
      city: '居住城市',
      rProvince: '户籍省份',
      rCity: '户籍城市',
      manger: '业务上级经理',
      gManger: '功能上级经理',
      compHR: 'HR顾问',
    },
    employeeView: {
      empName: '姓名',
      empcompHirecompanyDis: '公司',
      empcompDeptDis: '部门',
      empcompPostDis: '岗位',
      empidTypeDis: '证件类型',
      empidNo: '证件号码',
      empcompEntrydate: '入职日期',
      empkiWorkno: '员工工号',
      empkiEmptypeDis: '员工类型',
    },
    empContractList: {
      title: '员工劳动合同',
      empctWorkNo: '员工工号',
      empctName: '员工姓名',
      empctHirecompany: '公司',
      empctDept: '部门',
      empctContracttype: '合同类别',
      empctContractperiod: '合同期限',
      empctContractsdate: '合同开始日',
      empctContractedate: '合同到期日',
      empctContractprom: '合同到期通知天数',
      empctConfidential: '保密协议',
      empctProbation: '试用期限',
      empctProbationdate: '试用到期日',
      empctSdate: '生效日期',
      empctEdate: '失效日期',
      empctComment: '备注',
      empctWorkNoDis: '请输入员工工号',
      empctNameDis: '请输入员工姓名',
      empctHirecompanyDis: '请输入公司',
      empctDeptDis: '请输入部门',
      empctContracttypeDis: '请输入合同类别',
      empctContractperiodDis: '请输入合同期限',
      empctContractsdateDis: '请输入合同开始日',
      empctContractedateDis: '请输入合同到期日',
      empctContractpromDis: '请输入合同到期通知天数',
      empctConfidentialDis: '请输入保密协议',
      empctProbationDis: '请输入试用期限',
      empctProbationdateDis: '请输入试用到期日',
      empctSdateDis: '请输入生效日期',
      empctEdateDis: '请输入失效日期',
      empctCommentDis: '请输入备注',
    },
  },
  'en-US': {
    empmaster: {
      title: 'Employee Master Data',
      title1: 'Basic Information Of Employees',
      title2: 'Employee Company Information',
      title3: 'Employee Contract Information',
      title4: 'Payroll Social Security Information',
      title5: 'Top Academic Information',
      title6: 'Basic Information Of Employees',
      imgAlt: 'No picture',
      empCname: 'Chinese Name',
      empGenderDis: 'Gender',
      empcompPostDis: 'Post',
      empGid: 'Employee GID',
      companyName: 'Company',
      deptName: 'Department',
      empidTypeName: 'Type Of Certificate',
      empidNo: 'Document Number',
      empcompEntrydate: 'Entry Date',
      empkiWorkno: 'Employee Number',
      empkiEmptypeName: 'Employee Type',
      empCnameDis: 'Please enter employee name',
      empkiWorknoDis: 'Please enter employee number',
      empPostDis: 'Please select department information！',
      empHireCompDis: 'Please select employment company information！',
    },
    baseInfo: {
      title: 'Basic Information',
      baseGid: 'Unique Identifed number',
      baseCname: 'Chinese Name',
      baseAlias: 'Alias / previous name',
      baseLastname: 'Last name',
      baseFirstname: 'First name',
      idsType: 'Type Of Certificate',
      idsNo: 'Document Number',
      baseBirthdate: 'Birthdate',
      baseGender: 'Gender',
      baseMarriage: 'Marriage Status',
      baseNation: 'Ethnic',
      basePolitical: 'Political Status',
      baseTechnicaltitle: 'Job Title',
      baseTechspec: 'Title Professional',
      baseFirstworkdate: 'Start Worktime',
      baseTechdate: 'Job Title Acquisition Time',
      baseGidDis: 'Please enter a unique identification number..',
      baseCnameDis: 'Please enter Chinese name',
      baseAliasDis: 'Please enter alias/previous name',
      baseLastnameDis: 'Please enter last name',
      baseFirstnameDis: 'Please enter first name',
      idsNoDis: 'Please enter the certificate number',
      baseBirthdateDis: 'Please select date of birth',
      baseNationDis: 'Please choose a nation',
      baseTechspecDis: 'Please enter title professional',
      baseFirstworkdateDis: 'Please choose to participate in working hours',
      baseTechdateDis: 'Please select job title acquisition time',
    },
    companyInfo: {
      title: 'Company Information',
      pkiWorkno: 'Employee Number',
      pkiEmptype: 'Employee Type',
      compHirecompany: 'Employment Company',
      compDept: 'Department',
      compPost: 'Post',
      compCostcenter: 'Cost Center',
      compHirelocation: 'Employment Location',
      compWorklocation: 'Work Place',
      compBuspmp: 'Business Manager',
      compFunpmp: 'Functional Manager',
      compEntrydate: 'Entry Date',
      compServicedate: 'Service Life Calculation Start Date',
      compCertificatedate: 'Certificate Date Calculation Start Date',
      compHr: 'HR Consultant',
      pkiWorknoDis: 'Please enter employee number',
      compHirecompanyDis: 'Please select employee company',
      compDeptDis: 'Please select department',
      compPostDis: 'Please choose post',
      compCostcenterDis: 'Please select a cost center',
      compHirelocationDis: 'Please select the place of employment',
      compWorklocationDis: 'Please select a place of work',
      compBuspmpDis: 'Please select the business manager',
      compFunpmpDis: 'Please select functional superior manager',
      compEntrydateDis: 'Please select the entry date',
      compServicedateDis: 'Please select the service start date',
      compCertificatedateDis: 'Please select a certificate date',
      compHrDis: 'Please select HR consultant',
    },
    contractInfo: {
      title: 'Contract Information',
      ctContracttype: 'Contract Type',
      ctContractperiod: 'Contract Period',
      ctContractsdate: 'Contract Start Date',
      ctContractedate: 'Contract End Date',
      ctContractprom: 'Contract end notice time (days)',
      ctConfidential: 'Confidentiality agreement',
      ctContractworktime: 'Contract work time',
      ctSigndate: 'Signing Date',
      ctProbation: 'Trial period',
      ctProbationdate: 'Trial Expiration Time',
      ctProbationprom: 'Trial end notice time (days)',
      ctContractsdateDis: 'Please select the contract start date',
      ctContractedateDis: 'Please select the contract end date',
      ctSigndateDis: 'Please select the contract signing date',
      ctProbationdateDis: 'Please select trial end time',
    },
    payInfo: {
      title: 'Payroll Social Security Information',
      salPostlevel: 'Post Level',
      salSalarylevel: 'Salary Level',
      salTravellevel: 'Travel Level',
      salAdminlevel: 'Admin Level',
      salSalaryset: 'Salary Set',
      bkBank: 'Bank Account',
      bkAccount: 'Account Number',
      bkAccnane: 'Household Name',
      sbBenefitlocation: 'Social Security Payment',
      sbHfundlocatio: 'Provident Fund Payment Place',
      sbBenefitpolicy: 'Social Security Policy',
      sbBenefittype: 'Social Insurance Account Category',
      bkBankDis: 'Please select your bank',
      bkAccountDis: 'Please enter your bank account number',
      bkAccnaneDis: 'Please enter account name',
      sbBenefitlocationDis: 'Please select the social security payment place',
      sbHfundlocatioDis: 'Please select the place where the CPF is paid',
      sbBenefitpolicyDis: 'Please choose social security policy',
      sbHfundpolicy: 'Please enter the provident fund policy',
      sbHfundtype: 'Please enter the account type of provident fund',
      sbHfundpolicyDis: 'Please enter the provident fund policy',
      sbHfundtypeDis: 'Please enter the account type of provident fund',
    },
    educationInfo: {
      title: 'Top academic information',
      edEducationlevel: 'Education Level',
      edCuntry: 'Country',
      edSchool: 'School',
      edDegree: 'Degree',
      edSpecialty: 'Profession',
      edSdate: 'Starting time',
      edEdate: 'End Time',
      edSchoolDis: 'Please enter school',
      edDegreeDis: 'Please enter degree',
      edSpecialtyDis: 'Please enter professional',
      edSdateDis: 'Please select start time',
      edEdateDis: 'Please select the end time',
    },
    addressInfo: {
      title: 'Contact address information',
      ctaMobile: 'Phone Number',
      ctaPhone: 'Contact phone(fixed)',
      ctaPersmail: 'Personal Mailbox',
      ctaCompmail: 'Company Email',
      ctaQq: 'QQ',
      ctaWechat: 'Wechat Number',
      ctaEmergcontact: 'Emergency Contact',
      ctaEmcrelation: 'Emergency Contact Relationship',
      ctaEmcphone: 'Emergency Telephone Number',
      ctaEmcaddr: 'Emergency contact address',
      addCuntry: 'Country of Residence',
      addProvince: 'Living Province',
      addCity: 'Living City',
      addStreet: 'Residence detailed address',
      addZip: 'Resident zip code',
      addrCuntry: 'Household country',
      addrProvince: 'Household Province',
      addrCity: 'Household registration city',
      addrStreet: 'Household registration details',
      addrRegisterproperty: 'Household nature',
      addrZip: 'Household Zip code',
      ctaMobileDis: 'Please enter phone number',
      ctaPhoneDis: 'Please type your phone number',
      ctaPersmailDis: 'Please enter your personal email',
      ctaCompmailDis: 'Please enter company email',
      ctaQqDis: 'Please enter QQ number',
      ctaWechatDis: 'Please enter the WeChat number',
      ctaEmergcontactDis: 'Please enter emergency contact name',
      ctaEmcphoneDis: 'Please enter emergency contact number',
      ctaEmcaddrDis: 'Please enter emergency contact address',
      addProvinceDis: 'Please select a province of residence',
      addCityDis: 'Please select a city of residence',
      addStreetDis: 'Please enter the address of your residence',
      addZipDis: 'Please enter the residential zip code',
      addrProvinceDis: 'Please enter the province of the household registration',
      addrCityDis: 'Please enter the household city',
      addrStreetDis: 'Please enter the detailed address of the residence',
      addrZipDis: 'Please enter the household registration code',
    },
    searchColumn: {
      lanCn: 'Parameter Chinese',
      lanEn: 'Parameter English',
      nationCn: 'Chinese Name',
      nationEn: 'English Name',
      nationName: 'Select nation',
      nationNameDis: 'Please enter Chinese name',
      bankCname: 'Select bank',
      bankCnameDis: 'Please enter bank account name',
      unitCodeCompany: 'Company Code',
      compCnFullName: 'Company Chinese Name',
      compEnFullName: 'Company English Name',
      unitCodeDepart: 'Depart Code',
      departCnFullName: 'Depart Chinese Name',
      departEnFullName: 'Depart English Name',
      postCode: 'Post Code',
      postFnameCnDis: 'Post Chinese Name',
      postFnameEnDis: 'Post English Name',
      sbPolicy: 'Social Security Policy',
      sbPolicyDis: 'Please enter Social Security Policy',
      hireCompany: 'Employment company',
      searchCompany: 'Select company',
      hireCompanyDis: 'Please enter company name',
      depart: 'Department',
      selectDepart: 'Select department',
      departDis: 'Please enter the department name',
      post: 'Select Post',
      postDis: 'Please enter post code',
      inputDis: 'Please enter',
      cityNameDis: 'Please enter city name',
      searchTitle: 'Select nation',
    },
    searchTableTitle: {
      hirelocation: 'Employment Location',
      worklocation: 'Work Location',
      benefitlocation: 'Social Security Payment',
      hfundlocatio: 'Provident Fund Payment Place',
      province: 'Living Province',
      city: 'Living City',
      rProvince: 'Household Registration',
      rCity: 'Household Registration City',
      manger: 'Business Manager',
      gManger: 'Functional Manager',
      compHR: 'HR Consultant',
      hfundpolicy: 'Provident fund policy',
      benefitpolicy: 'social security policy',
    },
    employeeView: {
      empName: 'Name',
      empcompHirecompanyDis: 'Company',
      empcompDeptDis: 'Department',
      empcompPostDis: 'Post',
      empidTypeDis: 'ID type',
      empidNo: 'ID No',
      empcompEntrydate: 'Date of entry',
      empkiWorkno: 'Work No',
      empkiEmptypeDis: 'Employee type',
    },
    empContractList: {
      title: 'Employees labor contract',
      empctWorkNo: 'Employee number',
      empctName: 'Employee name',
      empctHirecompany: 'The company',
      empctDept: 'department',
      empctContracttype: 'The contract category',
      empctContractperiod: 'The contract deadline',
      empctContractsdate: 'Contractstart date',
      empctContractedate: 'Expiration date',
      empctContractprom: 'Contractprom days',
      empctConfidential: 'Confidentiality agreement',
      empctProbation: 'Trial period',
      empctProbationdate: 'Expiry date',
      empctSdate: 'Effective date',
      empctEdate: 'Expiry date',
      empctComment: 'note',
      empctWorkNoDis: 'Please enter the employee number',
      empctNameDis: 'Please enter the employee name',
      empctHirecompanyDis: 'Please enter company',
      empctDeptDis: 'Please enter the department',
      empctContracttypeDis: 'Please enter the contract category',
      empctContractperiodDis: 'Please enter the contract term',
      empctContractsdateDis: 'Please enter the contract start date',
      empctContractedateDis: 'Please enter the expiration date of the contract',
      empctContractpromDis: 'Please enter the date of expiry notice',
      empctConfidentialDis: 'Please enter the confidentiality agreement',
      empctProbationDis: 'Please enter a trial period',
      empctProbationdateDis: 'Please enter the trial expiration date',
      empctSdateDis: 'Please enter the effective date',
      empctEdateDis: 'Please enter the expiration date',
      empctCommentDis: 'Please enter remarks',
    },
  },
}
