export default {
  'zh-CN': {
    monitorBoard: {
      title: '出国统计看板',
      subTitle1: '当前目的地出国统计',
      subTitle2: '当前各公司出国统计',
      subTitle3: '逾期未回国统计',
      // subTitle4: '按照公司统计业务流程总数量、已完成数量',
      // subTitle5: '按照业务流程统计总数量、已完成数量',
      // subTitle6: '统计流程平均处理时间,标准处理时间',
      selectFlow1: '员工入职工单',
      selectFlow2: '员工转正工单',
      selectFlow3: '内部调动工单',
      selectFlow4: '员工离职工单',
      selectFlow5: '合同续签工单',
      legend1: '工单总数量',
      legend2: '已处理数量',
      legend3: '流程总数量',
      legend4: '处理中数量',
      legend5: '已完成数量',
      legend6: '标准处理时间',
      legend7: '平均处理时间',
      pointMax: '最大值',
      pointMin: '最小值',
      areaZoom: '区域缩放',
      areaZoomRes: '区域缩放后退',
      series1: '当前目的地出国统计',
      series2: '当前各公司出国统计',
      series3: '逾期未回国人数统计',
    },
    orderCountStatistic: {
      title: '工单数量分析',
      title2: '工单满意分析',
      title3: '工单执行分析',
      authorComp: '提交公司',
      orderType: '工单类型',
      handleTeam: '处理团队',
      allOrder: '提交数量',
      dealingNum: '处理数量',
      avgEvaluate: '平均满意度',
      stdDltime: '标准处理时间',
      activeTime: '平均处理时间',
      minHandletime: '最小处理时间',
      maxHandletime: '最大处理时间',
      authorCompDis: '请选择提交公司',
      orderTypeDis: '请输入工单类型',
    },
    flowBusinesStatistic: {
      title: '业务工单分析',
      title2: '工单执行分析',
      title3: '警示记录分析',
      flowCode: '流程编码',
      flowName: '流程名称',
      stepDis: '流程步骤',
      stddealtime: '标准处理时间',
      avgdealtime: '平均处理时间',
      mindealtime: '最小处理时间',
      maxdealtime: '最大处理时间',
      flstepCaudealtime: '预警处理时间',
      platWarningDealtime: '已处理时间',
      platWarningHirecompany: '雇佣公司',
      platWarningDealpeople: '处理人',
      flowTotal: '总数量',
      flowDealCount: '处理中',
      flowClosedCount: '已完成',
      searhText: '请输入流程编码或名称',
    },
  },
  'en-US': {
    monitorBoard: {
      title: 'Operation monitoring board',
      subTitle1: 'Work orders according to the company',
      subTitle2: 'Work orders according to the work order category',
      subTitle3: 'Average satisfaction to work orders',
      subTitle4: 'Work orders according to the company',
      subTitle5: 'Work orders according to the business process',
      subTitle6: 'Statistical process average processing time, standard processing time',
      selectFlow1: 'Entry Order',
      selectFlow2: 'Probation Order',
      selectFlow3: 'Tranfer Order',
      selectFlow4: 'Dismiss Order',
      selectFlow5: 'Rennew Order',
      legend1: 'WorkOrder Totals',
      legend2: 'WorkOrders Handled',
      legend3: 'Flow Totals',
      legend4: 'Flow Handling',
      legend5: 'Flow Handled',
      legend6: 'Standard handle time',
      legend7: 'Average handle time',
      pointMax: 'Maximum',
      pointMin: 'Minimum',
      areaZoom: 'Regional scale',
      areaZoomRes: 'Region zoom back',
      series1: 'Work order category work order quantity statistics',
    },
    orderCountStatistic: {
      title: 'Work order quantity analysis',
      title2: 'Work order satisfaction analysis',
      title3: 'Work order execution analysis',
      authorComp: 'Submitted company',
      orderType: 'Workorder type',
      handleTeam: 'Team\'s Name',
      allOrder: 'Submits',
      dealingNum: 'Number of handling',
      avgEvaluate: 'Average satisfaction',
      stdDltime: 'Standard time',
      activeTime: 'Average time',
      minHandletime: 'Minimum time',
      maxHandletime: 'Maximum time',
      authorCompDis: 'Please select submit company',
      orderTypeDis: 'Please enter work order type',
    },
    flowBusinesStatistic: {
      title: 'Business order analysis',
      title2: 'Work order execution analysis',
      title3: 'Alert record analysis',
      flowCode: 'FlowCode',
      flowName: 'FlowName',
      stepDis: 'Flow Steps',
      stddealtime: 'Standard time',
      avgdealtime: 'Mean time',
      mindealtime: 'Minimum time',
      maxdealtime: 'Maximum time',
      flstepCaudealtime: 'Warning time',
      platWarningDealtime: 'Handled time',
      platWarningHirecompany: 'Hire company',
      platWarningDealpeople: 'Deal people',
      flowTotal: 'FlowTotal',
      flowDealCount: 'Flow DealCount',
      flowClosedCount: 'Flow ClosedCount',
      searhText: 'Please enter the process code or name',
    },
  },
}
